### PR TITLE
LPS-64881 refresh product menu portlet on update layout to maintain consistency of layout tree

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/12. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/8c652a7~1...8c652a7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
