### PR TITLE
LPS-60244 Add lang key

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @evannagayama, could you please take a look at these Poshi errors? Looks to me like this could be a test error. Are we using the title property (minus one character) to identify the editor? That might explain the error we're seeing in those...

**Comment by evannagayama** [comment]
@jbalsas just looking at it quickly it looks like the html for the alloy editor was changed. I think it is a test fix. Can you send me a pull request and we'll fix the tests? Thanks

**Comment by jbalsas** [comment]
Hey @evannagayama, of course, it was changed to have a proper title attribute, but because of this: https://github.com/jbalsas/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/portal/util/liferayselenium/WebDriverHelper.java#L547 it will fail to find the editor instance.

Using `@title` as the id for the editor sounds like a really bad idea :sweat_smile: 

Couldn't we just use the `id` attribute?

**Comment by jbalsas** [comment]
I've resent it to you [here](https://github.com/evannagayama/liferay-portal/pull/508) :relaxed: 

Thanks!

**Comment by evannagayama** [comment]
Yeah I'm not exactly sure why we chose the title instead of id. I'm assuming it's because the id was really vague and not unique. I'll look into it and see if we can switch it. Thanks!

**Pull request closed without merging**
