### PR TITLE
LPS-60718, LPS-61118

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-60718 and https://issues.liferay.com/browse/LPS-61118.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey guys, I sent this one to Brian [here](https://github.com/brianchandotcom/liferay-portal/pull/33596).

If I'm not mistaken, this is also a new taglib, so I dropped the deprecation commmit and removed the breaking change entry.

Thanks!!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33597. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/b843f6e~1...b843f6e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
I had to rebase and resend :joy: 

@mjbradford89, @jonmak08, @thektan, keep in mind that some taglibs have `js` modules as well. Those should be migrated to the taglib module. Take a look at https://github.com/brianchandotcom/liferay-portal/commit/b843f6ef8f8e08d6ecfa0159c748165d929a1387

Ideally, we should also move the related `css`, but we don't have all the needed infrastructure in place, so we'll have to leave that for another time :wink:

**Comment by mjbradford89** [comment]
Thanks for catching that @jbalsas!  I'll make sure to migrate any js modules as well for future migrations.

**Pull request closed without merging**
