### PR TITLE
LPS-114611 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
> About the name of the tag, I think "languages" is a bit too generic. FI should have the last word on this, but I think we should use something that better describes what the tag is doing (group-language-selector, group-language-settings, etc.).
> @jbalsas any thoughts about the naming?

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @ambrinchaudhary, @victorvalle, do we have a LEXI ticket for this? I only see Figma mockups from @victorvalle, but not a Lexicon definition from @drakonux... just to figure out if this is a Lexicon component or a custom DXP one...

**Comment by drakonux** [comment]
Hi everyone, this is a DXP pattern made by team-lima. At the same time, the lexicon team was studying the dual list component and we requested a study including the language pattern - table list (see [DESRES-24](https://issues.liferay.com/browse/DESRES-24)) to @MiriamManso (research department).  

Some problems were detected, and we proposed some changes that have been already implemented. So... from our point of view @jbalsas the pattern is valid but specific from DXP.

**Comment by jbalsas** [comment]
Thanks @drakonux! For the future... it would be benefitial for Frontend Infra to be involved earlier on for components that the team knows upfront will be sent to us.

/cc @adolfopa

**Comment by ambrinchaudhary** [comment]
Closing PR... We are not changing the language selector in Sites, so no taglib is needed. Will keep the changes only for Asset Libraries (depot). Thanks everyone.

**Pull request closed without merging**
