### PR TITLE
LPS-67821 Emit adapted events also in the host

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by carloslancha** [comment]
squash: 
Implement new translation manager in journal
Add componentId to translationManager use of taglib in journal

con la descripción de Implement new translation manager in journal.

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/carloslancha/liferay-portal/pull/82. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
