### PR TITLE
LPS-104039 Update Clay3 packages to 3.1.x

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, can you send me a new PR with these (and new) changes?

Thanks!! :)

**Pull request closed without merging**
