### PR TITLE
LPS-73579 Indicate and select by the tag-selected class rather than the strong tag

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @jbalsas 

I changed the solution like you suggested in https://github.com/jbalsas/liferay-portal/pull/1026#issuecomment-369193543

I tested it, and it works the same way as the previous version with the strong tag.

Best regards,
István

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @IstvanD, I assume by adding the class we also get the `selected` bold look and feel and the strong tag is no longer needed?

**Comment by IstvanD** [comment]
Hey @jbalsas that is right, the look will be the same as with the strong tag.

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/55747. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Awesome! I've just forwarded it to brian.

Thanks! 👍

**Comment by IstvanD** [comment]
Thanks a lot @jbalsas!

**Pull request closed without merging**
