### PR TITLE
[TECHNICAL-SUPPORT] LPS-92572

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @holatuwol:

> https://issues.liferay.com/browse/LPS-92572
> 
> The issue is that IE11 doesn't handle media queries well if the transition is done using the same approach that senna.js uses, causing the page to render incorrectly.
> 
> The senna.js team believes there is nothing that can be done on the senna.js side to resolve the issue, and it affects more than just Liferay .css files (third-party .css loaded on the page is also affected).
> 
> Additionally, there was a page rendering time performance regression introduced by https://github.com/liferay/senna.js/issues/124 (to summarize, a side-effect of that fix is that IE11 will always re-download every CSS file on every senna-managed page navigation), which means that pages load more slowly with senna.js in IE11 than without it.
> 
> Given all that, it makes sense to simply disable senna.js on IE11.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @jonathanmccann, @holatuwol, how does this actually help the IE11 case?

What I understand is that there's currently an issue that causes us to download more code than expected (and produces wrong behaviours on media-queries). Then, the solution is to always make it slow to every customer regardless of any other consideration?

As Lee points out in the comment, if this is a more common problem than previously analyzed, I feel we could put some additional thought into it. Maybe we could pre-process css for IE11 in a different way (so it would be a tooling matter). Or we could try to see if we can post-process it in a different way (making it a runtime matter, perhaps in senna).

I'd like to exhaust some additional options before saying we need to disable this for IE11. Have we compared IE11 with and without SPA? Have we shown it to a customer? It's hard for me to understand the argument on how the non-spa version is at least as good as the spa one since it's flashing all the time and the page blanks out on every navigation before showing back the content... if anything, even if they're both as slow, the spa version should at least deliver a better perceived performance.

**Comment by holatuwol** [comment]
*Then, the solution is to always make it slow to every customer regardless of any other consideration?*

It is better to be slightly slower but always correct than slightly faster and always incorrect.

**Comment by jbalsas** [comment]
> However, the reality is that IE11 with SPA is slightly slower and always incorrect, while IE11 without SPA is slightly faster and always correct. Therefore, the dilemma you've presented doesn't apply in this case.

If that's the case, I would totally agree. Can you have those metrics and the way you've conducted them with us so we can try to reproduce?

In our experience and past tests, IE11 with SPA was more than slightly better off than without. As IE11 is the slower browser, it was the one the benefitted the most from the improvements and not the other way around, so I'd like to double check that claim and see where it might've gone wrong.

**Comment by brunobasto** [comment]
> However, the reality is that IE11 with SPA is slightly slower and always incorrect, while IE11 without SPA is slightly faster and always correct. Therefore, the dilemma you've presented doesn't apply in this case.

If @diegonvs or @matuzalemsteles have the time, I'd be interested in see that backed up by some numbers. I remember doing some performance analysis some time ago, but I didn't test in IE11. I assumed that the numbers would be similar since the principle of operation is the same. With senna, we would avoid all the bootstrapping that happens whenever a page is loaded. But given the mysterious ways IE11 operates, it's possible that it makes it actually slower.

Maybe from that study we can make a better informed decision on wether it's worth it to invest time in this issue or if our users would be better served with senna off for IE11. If the analysis does prove that senna doesn't help performance at all, we can decide if we are willing to make it faster and reliable for IE11 or if it's better to just disable it.

**Comment by jbalsas** [comment]
Hey @david-truong, do you think we could drop support SPA support entirely for IE11? Regardless of the speed tests result, it's true that dropping it would cut many of our support and maintenance costs.

**Comment by jbalsas** [comment]
@holatuwol, assuming we move forward disabling SPA for IE11. Would you mind adding a configuration for it? That way we can disable it by default in `master` and future versions and backport it enabled by default to older branches where we can easily ask customers to opt-in. That way we cover all of our bases and don't change the current behaviour.

**Comment by holatuwol** [comment]
> Can you share those specific metrics and the way you've conducted them with us so we can try to reproduce? ... As IE11 is the slower browser, it was the one the benefitted the most from the improvements and not the other way around, so I'd like to double check that claim and see where it might've gone wrong.

We don't have measurements. We just have feedback from customers telling us that disabling senna.js in IE11 has worked for them.

Back in May, a customer asked us why IE11 was so slow, we investigated and found that https://github.com/liferay/senna.js/issues/124 caused IE to re-download every CSS file on every page load. After exhausting various other potential issues (developer tools, compatibility mode, etc.), we disabled senna.js on IE11 for that customer to see if that changed their perception, and they reported that IE11 was finally rendering pages more quickly (none of the other changes helped as much as simply disabling senna.js).

In https://github.com/liferay/senna.js/issues/301 another customer has recently reported that they also perceive pages as loading faster without senna.js enabled (in addition to experiencing fewer page rendering issues in IE11) and they are also asking for a configuration option to disable it.

> Assuming we move forward disabling SPA for IE11. Would you mind adding a configuration for it?

I'll do what's needed to get this change through review. I don't think we should allow you to configure it because of the severity of the bugs with IE11 and senna.js, notably that pages will render as if you were using a mobile device while browsing on a desktop machine.

**Comment by jbalsas** [comment]
Hey @holatuwol, I would propose the following:
- Add a `disable-spa-in-ie11` (or `enable-spa-in-ie11`) flag
- Set it to false by default (or true) so that we preserve the current behaviour in the original commit

We can safely merge this to master and then start the backport process.

During the backport process, I think it's reasonable that support makes the call of what value to set and how to communicate it. You could discuss this with @antonio-ortega, @dsanz and whoever else should be in the loop. I'm sure whatever you decide will be the right call for our customers.

**Comment by holatuwol** [comment]
> During the backport process, I think it's reasonable that support makes the call on what value to set and how to communicate it.

We need to use whatever value is set in master, or it will fail during backport review, so I'll respect the decision that you and your team have made with regards to default behavior. I've sent a pull request making it a configuration option which defaults to leaving senna.js enabled.

https://github.com/jbalsas/liferay-portal/pull/1946

**Comment by holatuwol** [comment]
ci:close

**Comment by holatuwol** [comment]
Oops, I forgot to switch the default value, will resend it.

**Pull request closed without merging**
