### PR TITLE
Lps 69753 new

### PR DESCRIPTION
**Pull request by shuyangzhou**
Just hit the home page, you will see the comboservlet error, thanks @jbalsas !

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @jonmak08

**Comment by shuyangzhou** [comment]
ci:reopen
Pushed up the unit test fix which is not related to this issue at all. But every other failures are caused by this comboservlet issue.

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @shuyangzhou, I've been taking a look, and the problem is that for some reason, the metal-web module (and others as well, I have the feeling) is not getting tracked.

If I add some traces in the [`addingService`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/JSLoaderModulesTracker.java#L68) I never see the `com.liferay.frontend.js.metal.web_1.0.13` show up, even though it has a registered `ServletContext`: _    {javax.servlet.ServletContext}={osgi.web.contextpath=/o/frontend-js-metal-web-1.0.13, osgi.web.symbolicname=com.liferay.frontend.js.metal.web, osgi.web.version=1.0.13, osgi.web.contextname=frontend-js-metal-web-1.0.13, service.id=8122, service.bundleid=290, service.scope=singleton}_

**Comment by shuyangzhou** [comment]
Yes, I noticed that too, I think I find out the reason now, trying to work on a fix. Thanks @jbalsas ! I will update the pull with I will find out.

**Comment by jbalsas** [comment]
Awesome! Let me know and I can retest and verify anything you want!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/45787
The problem is an OSGi classloader visibility issue, I have to use the bootdelegation to bypass it.

Thanks @jbalsas !

**Comment by jbalsas** [comment]
Awesome, thanks @shuyangzhou!

**Pull request closed without merging**
