### PR TITLE
LPS-69571 ImageEditor carousel

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:retest

**Comment by carloslancha** [comment]
ci:reopen

**Comment by carloslancha** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51470. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f56cd3d~1...f56cd3d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51474. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f7b4365~2...f7b4365) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
