### PR TITLE
LPS-114411 Ask browser only if no values present

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hi @adolfopa, thanks for sending this over!!

In order to improve our review workflow, we ask that you help us out by following some these recomendations:
- [Frontend Infrastructure Team code review process](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/code_review.md)
- [Pull Request Etiquette](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/pull_requests.md)

Most importantly:
- Send the PR to the @liferay-frontend user (✖️)
- Provide a meaningful PR title (✖️)
- Provide a meaningful PR description (✖️)
    - Describe the observed problem
    - Add a technical explanation of the issue
    - Describe the solution and why it's the right one
    - Comment any technical considerations, things you tried, cases you considered...
- Include a test plan (✖️)

While some of these might seem redundant and the information might be in the LPS, writing all that down here helps us focus on the review and track everything better through the workflow, so we really appreciate you taking the time to make this easier for us 🤗 

Would you be so kind as to send this to the @liferay-frontend user following some of those suggestions? 

I can do it for you if you want me to 😘

**Comment by adolfopa** [comment]
Oops ... :-D

I'll follow the proper procedure and resend it to liferay-frontend.

Thanks!

**Comment by ambrinchaudhary** [comment]
@adolfopa I think you finally did not forwarded this pull to @liferay-frontend, so I'm going to do that for you ;-)

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Pull request closed without merging**
