### PR TITLE
LPS-85134 - Fix aria controls ID

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
@john-co, could you check the failures here? Do they seem relevant?

**Comment by john-co** [comment]
@jbalsas, the unique failures are not related to the code changes when comparing with latest acceptance tests at head. The /lpkg-base-jdk8 is also an unrelated error that is currently being fixed.

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/63216. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
