### PR TITLE
LPS-95554

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas this is just for LPS-95554

Can you do this the "right" way? And send me a fix? Or delegate it to someone on your team. Thx. But I'd like this change for 7.2.x.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, this is a bit irregular... what is this change expected to do and why is it needed? The LPS contains no information whatsoever about the decision or the expected result of whatever changes are happening here...

I've talked to @adolfopa because his team is the one that handles these components so he's aware that some type of redesign is happening. This might affect how the component behaves and presents in many different places.

In any case, while we figure it out, @eduardoallegrini and @marcoscv-work will take a look to at least try to clear this out.

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
@brianchandotcom @ssmith353 Tomorrow we'll show this to some of the UX people, to make sure it is aligned with Lexicon and tweak it a bit if necessary.

**Comment by eduardoallegrini** [comment]
@jbalsas The main change in this commit is a new design for the stars rating system
before:
image
after:
image

For the code, I would suggest to use classes instead of inline-styles. If we know where the stars-rating-component is used we can use the utility classes from Bootstrap
https://getbootstrap.com/docs/4.3/utilities/display/

**Comment by jbalsas** [comment]
Talked offline with @adolfopa. They'll take over this and create another rating style "stacked-stars" or sth like that, keeping the old styling as default.

**Pull request closed without merging**
