### PR TITLE
LPS-104350 Wraps content in a surface div to avoid unnecessary reflow

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
A lot of the test failures are due to lfr SPA loading failing to load. The personal menu bar avatar disappears in the screenshots such as in: https://testray.liferay.com/reports/production/logs/test-1-19/1573220082286/test-portal-acceptance-pullrequest(master)/5351/functional-tomcat90-mysql57-jdk8/39/0/LocalFile.CPDynamicdatalists_AddFormTemplate/index.html.gz

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Pull request closed without merging**
