### PR TITLE
LPS-61157, LPS-61157, LPS-61192 - Migrate ui:social-activities taglib to social-taglib module

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Sergio,

Attached are changes for [LPS-60911](https://issues.liferay.com/browse/LPS-60911), [LPS-61192](https://issues.liferay.com/browse/LPS-61192), and [LPS-61157](https://issues.liferay.com/browse/LPS-61157).

Let me know if you want me to split these changes up into separate pulls, but this is the pattern we've been following so far with other taglibs.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
@sergiogonzalez @jbalsas,  I think the conflict in here is just in the breaking changes markdown file.  Let me know if you need me to resolve it and I can resend.  Thanks!

**Comment by jbalsas** [comment]
Hey @mjbradford89, the reason I asked @sergiogonzalez to send it back to me in the frist place was to work on the `Freemarker` integration.

We need to make taglibs available to the `Freemarker` engine. For every `my-app-taglib` module we need a corresponding `my-app-taglib-freemarker-contributor` one. Could you please create it for this one as well? You can check how to do it in [site-navigation-taglib-freemarker-contributor](https://github.com/liferay/liferay-portal/tree/master/modules/apps/site-navigation/site-navigation-taglib-freemarker-contributor) or in [frontend-taglib-freemarker-contributor](https://github.com/liferay/liferay-portal/tree/master/modules/frontend/frontend-taglib-freemarker-contributor).

Could you please:

- Rebase and drop the `Import Package` and `Require-Capability` from the `bnd` files in the process. (Those shouldn't be needed anymore, and some of those changes could actually be causing some rebase conflicts)
- Create the `social-taglib-freemarker-contributor` module.

If I remember correctly, this still depends on some changes in the plugins SDK to work properly, so resend to me and I'll push it forward as soon as that gets resolved.

Thanks a lot!

**Comment by mjbradford89** [comment]
Hey @jbalsas,  I'll start working on those issues for this one right now and keep them in mind for future taglibs I migrate. Thanks!

**Comment by mjbradford89** [comment]
New pull here: https://github.com/jbalsas/liferay-portal/pull/331,  Thanks!

**Comment by jonmak08** [comment]
This has been fixed with https://github.com/liferay/liferay-portal/commit/14e15420d4658a59ef7d918d7ae3021c226050af

**Pull request closed without merging**
