### PR TITLE
LPS-103247 Update variables to correct element/class retrieval from Lexicon 2.0 upgrade

### PR DESCRIPTION
**Pull request by KYoungLR**
Hey @jbalsas,

Here is the follow-up on [LPS-103247](https://issues.liferay.com/browse/LPS-103247)
Previous PR: https://github.com/jbalsas/liferay-portal/pull/2057

**Main Issue:** During the Lexicon 2.0 upgrade [(LPS-103247)](https://issues.liferay.com/browse/LPS-103247), specific classes that were being targeted by the ‘_focusInvalidFieldTab’ function were replaced, causing variables to become null.  

**Three Main Points**
- The lfr-nav class was replaced with the “mb-3 mb-lg-4” classes, which caused the formTabs variable to become null.  This caused the issue since the ‘_focusInvalidFieldTab’ function was still targeting that specific class. Should we add in the previous .lfr-nav class or create a brand new class which is not tied to any previous CSS since it was removed in the previous Lexicon 2.0 upgrade
  - Also thought about targeting the mb-3 and mb-4 classes but felt they were too generic and could be reused with other elements in the future
- The tab class was updated to nav-item during the Lexicon 2.0 upgrade, causing the ‘_focusInvalidFieldTab’ not able to pass the conditional check since the tabs variable was undefined.
  - Confirmed throughout other modules to make sure that changing formTabs.all(‘.tabs’) to formTabs.all(‘.nav-item’) would not affect other validation checks since no other files were using the tabs class anymore
    - Or should we add in the tabs class to the nav-item element, without replacing, since it was replaced during the Lexicon 2.0 upgrade
- Targeting the wrapping fieldset elements to make the fieldWrapper variable no longer null fixed the issue, which was also changed in the Lexicon 2.0 upgrade.  Tested with other inputs without any issues.  

For additional details, please see below.  Please let me know what you think or if any additional changes are needed. Thanks!

/cc @ericyanlr @achaparro

---
**Additional Details Leading up to Findings**
- Found that the .lfr-nav class was changed in LPS-92099 to update the markup to work with Lexicon 2.0
  - https://issues.liferay.com/browse/LPS-92099
    - The lfr-nav class was replaced with the “mb-3 mb-lg-4” classes, which caused the formTabs variable to become null.  This caused the issue since the ‘_focusInvalidFieldTab’ function was still targeting that specific class. We could change the logic in the function to target mb-3 or mb-lg-4, but felt those 2 classes were too generic and could be reused elsewhere
      - PR: https://github.com/brianchandotcom/liferay-portal/pull/70121/commits/5bec4bf4a463b7eacb000b50a02c4c9997326573
  - Adding in the .lfr-nav class to 71x and master fixes the issue, however the bug still exists after adding in .lfr-nav class to master
    - There is a conditional that is causing the tab issue, since both fieldWrapper and formTabs have to be true
      - Master: fieldWrapper = null / formTabs = null
      - 71x: fieldWrapper = Y_Node (True)
        - var fieldWrapper = field.ancestor('form > div')
    - Compared field node object to see why field.ancestor(‘form > div’) was getting undefined in master and not 71x
- Using the console, found that 71x was not undefined because it was able to find the specific div
  - In master, it was undefined since the html was changed and the specific div from 71x was now enclosed in a fieldset element
    - Adding the fieldset element in to the field.ancestor() method fixed the issue
      - To make sure this would not affect other pages using the ‘_focusInvalidFieldTab’ function, tested other validation forms to make sure the field.ancestor(‘form > div’) div was also now wrapped in a fieldset element
- After satisfying the fieldWrapper and formTabs conditional, I looked in to why the tabs variable was becoming undefined with formTabs.all(‘.tabs’)
  - Found that .tabs was changed to .nav-item in the list items, causing tabs to be undefined, causing the tab switch function to error out and not switch the tabs to the error field
    - This change was also due to LPS-92099, updating the tabs markup to Lexicon 2.0
      - https://issues.liferay.com/browse/LPS-92099
    - Previously <li class=”<%= cssClassName %>” changed to <li class=”nav-item”
- Confirmed throughout other modules to make sure that changing formTabs.all(‘.tabs’) to formTabs.all(‘.nav-item’) would not affect other validation checks since no other files were using the tabs class anymore

### CODE REVIEW

**Comment by jbalsas** [comment]
Thanks a lot @KYoungLR, this looks much cleaner and less scary!!

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co! Can you monitor test results here to see if anything suspicious pops up?

Thanks!

**Comment by john-co** [comment]
Hi @zhangyan0701 can you analyze the test results here?

**Comment by zhangyan0701** [comment]
Just start reviewing.

**Comment by zhangyan0701** [comment]
No related failures.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83633. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83636. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/ec31722c3190~1...ec31722c3190) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
