### PR TITLE
LPS-115551 - Add border color light in admin and classic themes

### PR DESCRIPTION
**Pull request by marcoscv-work**
New design for control-menu-light version, with bottom border in light color:

image

To use the same border in modals and navbars with management-bar below, developers will need to add to navbar the class called `border-bottom` (actually they are currently doing this).

To validate the design you can go to navigate to any section of applications (Global menu).

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @marcoscv-work, I'm not sure I follow this:

> To use the same border in modals and navbars with management-bar below, developers will need to add to navbar the class called border-bottom (actually they are currently doing this).

Do developers want that different border-bottom or not? Why are they different? Do we need to change them all?

In any case, please resend to the `liferay-frontend` user and detail there as we've discussed in the team channel so we can centralize reviews there. 

Thanks!

**Comment by marcoscv-work** [comment]
resend: https://github.com/jbalsas/liferay-portal/pull/2217

**Comment by wincent** [comment]
> resend: #2217

https://github.com/liferay-frontend/liferay-portal/pull/19

**Pull request closed without merging**
