### PR TITLE
LPS-88303 Updates Clay dependencies to v2.5.0

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
@jbalsas real SF issue here - alphabetize https://github.com/jbalsas/liferay-portal/pull/1545/commits/5cc5590d2f9a4a05472c8900226ac6e314a80838#diff-7603cee0b201a4202a31df645194cbaaR39
```
     [java] 1: ./modules/apps/frontend-taglib/frontend-taglib-clay/package.json expected:<...: "2.5.0",
     [java] 		"clay-m[odal": "2.5.0",
     [java] 		"clay-multi-select]": "2.5.0",
     [java] 		"clay-...> but was:<...: "2.5.0",
     [java] 		"clay-m[ulti-select": "2.5.0",
     [java] 		"clay-modal]": "2.5.0",
     [java] 		"clay-...>
```
We'll take a look at the rest of the failures as well.

**Comment by jbalsas** [comment]
🙈

**Comment by patriciajeanperez** [comment]
Hi @jbalsas, it seems like the failing functional tests are all test fixes. @brianchiu and I are currently working on fixing them.

**Comment by jbalsas** [comment]
Hey @patriciajeanperez, does that mean that they’re unrelated to these changes, or that we need to fix tests in order to send this through?

**Comment by brianchiu** [comment]
Hey @jbalsas, the test failures are related, so we just need to update those tests in order to send this through.

**Comment by brianchiu** [comment]
Patricia sent me a pull here: https://github.com/brianchiu/liferay-portal/pull/1738

**Comment by jbalsas** [comment]
Thanks!

**Pull request closed without merging**
