### PR TITLE
LPS-102088 - Deactivate breadcrumbs in compatibility layer

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @marcoscv-work, I see a lot of places with `.breadcrumb .breadcrumb-item`... are we sure those won't be affected by this?

**Comment by marcoscv-work** [comment]
I've taken after and before screenshots of breadcrumbs portlet in its three different ADT:

image

image

**Comment by jbalsas** [comment]
Why don't we disable it in `admin` as well?

**Comment by marcoscv-work** [comment]
Resend: https://github.com/jbalsas/liferay-portal/pull/2007

**Pull request closed without merging**
