### PR TITLE
LPS-104003 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-104003

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co, I think this is already getting in at https://github.com/brianchandotcom/liferay-portal/pull/80410 with other changes... wonder how we missed it, but certainly, SF not running on everything in PRs is very unfortunate :(

Closing for now here so we don't get conflicting PRs

**Pull request closed without merging**
