### PR TITLE
LPS-85193 - Fix title hierarchy

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
image

**Comment by jbalsas** [comment]
Hey @marcoscv-work, how does this markup change impact screenreaders and other outline related mechanisms?

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/63218. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
