### PR TITLE
Archive youtube

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jpince** [comment]
@preston-crary do we need to fix this error (and similar) for apps being moved to the archived folder? Or can it be ignored? I'm not even sure why SF is complaining about it now, it's passing in upstream as-is.
`     [java] 1: Attribute 'mvcc-enabled' should always be set in service.xml. Preferably, set 'mvcc-enabled="true"'.: ././modules/apps/archived/microblogs-service/service.xml (SourceCheck:XMLServiceFileCheck)`

**Comment by jbalsas** [comment]
I think I might've deleted the SF suppressions. Should be just a matter of readding them

**Comment by jpince** [comment]
@jbalsas that makes a lot more sense :relieved:

**Comment by jpince** [comment]
@jbalsas oh, I see it now - the suppression files previously lived in the app dir (e.g. [unit-converter/source-formatter-suppressions.xml](https://github.com/liferay/liferay-portal/blob/master/modules/apps/unit-converter/source-formatter-suppressions.xml), so they'll all need to be squashed into one file, `archived/source-formatter-suppressions.xml`

@preston-crary nevermind, thanks!

**Comment by jpince** [comment]
@jbalsas update: Peter Shin is going to make SF ignore the `archived` folder entirely, see https://issues.liferay.com/browse/LPS-106428. I will run `ci:test:sf` again for this PR if his change gets merged today.

**Comment by jbalsas** [comment]
Sounds good, @jpince!

I've added some additional commits for correctness in any case. @petershin, the last one got autogenerated after the changes, which I assume is to be expected.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
one last time 🤞

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
yeah

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Well... we can at least confirm that `archived` gets compiled on CI but not locally (since `ant all` didn't fail for me).

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Push-forced fixes to the dependencies paths. Retesting...

**Comment by jpince** [comment]
@jbalsas Here's a summary of what we'd need to make bookmarks work, or you could leave it alone, up to you.
1. Modify tests in asset to not use bookmarks
2. Export-import tests using bookmarks - I think we are still supporting export/import in 7.3, so these tests would need to be fixed also
```
modules/apps (master) $ git grep ":bookmarks:"
asset/asset-link-test/build.gradle:     testIntegrationCompile project(":apps:bookmarks:bookmarks-api")
asset/asset-link-test/build.gradle:     testIntegrationCompile project(":apps:bookmarks:bookmarks-test-util")
asset/asset-test/build.gradle:  testIntegrationCompile project(":apps:bookmarks:bookmarks-api")
asset/asset-test/build.gradle:  testIntegrationCompile project(":apps:bookmarks:bookmarks-test-util")
...
export-import/export-import-test/build.gradle:  testIntegrationCompile project(":apps:bookmarks:bookmarks-api")
export-import/export-import-test/build.gradle:  testIntegrationCompile project(":apps:bookmarks:bookmarks-test-util")
```

**Comment by jbalsas** [comment]
I've rebased and added some fixes. Sent to https://github.com/jbalsas/liferay-portal/pull/2083

**Pull request closed without merging**
