### PR TITLE
LPS-102093 Turn off dropdown in compatibility layer

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
💪🏻

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Investigate further manually:
ExportImport#ImportCorruptedFile - possible regression?
WorkflowCalendar#ApproveEventWithInvitedUser - possible fluke?

Fluke
CPRolesPGDocumentsandmedia#AddDMDocumentRegRoleDefaultPermissions
Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=865574706&testrayRunIdA=866179404&statusB=2

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Previous possible regressions and flukes are passing in last `ci test relevant` run.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80781. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
