### PR TITLE
LPS-94714 | Modernize Portlet URL Utility

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey, Greg told me to forward this to you so you can take a look.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, could you analyze this PR? We'd like to merge and backport, so I'd like to make sure it's safe.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @jbalsas @kresimir-coko,

There's some failing tests related to this pull:
1. Clicking Select button when creating a DDL brings up a pop up with a Product Menu sidebar when there shouldn't be a Product Menu.
DDL_select

2. Trying to click "+" to repeat a repeatable DDL data definition doesn't do anything
DDL_notRepeatable

3. Clicking on Select button on an Image Structure in Web Content doesn't do anything
WC_ImageSelectButton

4. Published Calendar Events do NOT display
CalendarEventsDoNOTDisplay

**Comment by kresimir-coko** [comment]
I'll check this today to see why these things arent working correctly with my PR

**Comment by jbalsas** [comment]
Hey @kresimir-coko, did you have the chance to look into this?

**Comment by kresimir-coko** [comment]
Hey @jbalsas I'm looking into it atm.

I couldn't get to the exact location as shown in the 2nd case, fixed the other 2 and working on the Calendar one right now. It exposed some interesting use cases which made the code more robust. As soon as I'm done I'll make sure to add on to the PR and let you know

**Comment by jbalsas** [comment]
Awesome, great to know @kresimir-coko! 💪

**Comment by kresimir-coko** [comment]
@jbalsas I've force pushed one additional commit to the PR that will hopefully result in a green light :)

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Previous failing tests are now passing, and the unique functional test failure is unrelated to this pull. :tada: :heavy_check_mark:

**Comment by kresimir-coko** [comment]
I've added one more commit to the PR, it concerns only the modern variant of the utility, adding the support for urls without the proper beginning and tests for that.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
let's see how this looks! ;)

**Comment by kresimir-coko** [comment]
I see what the problem is, force pushing a commit with the fix.

I didn't add the mocked function to the 3 smaller test files, I assumed wrong.

**Comment by jbalsas** [comment]
Still seeing a lot of failures here to feel confident... testing one more time. @john-co, could you please analyze when results come in?

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @jbalsas, the failures look unrelated to the pull. :heavy_check_mark: 

cc/ @kresimir-coko

**Comment by john-co** [comment]
Failures look unrelated :heavy_check_mark:

Breadcrumb#DisableShowCurrentSite is a flaky test
Other failures are present in upstream

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1840. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Forwarded to myself for a final pass and review!

**Pull request closed without merging**
