### PR TITLE
LPS-112464 Clay 3.x IconTag, BadgeTag, LabelTag and StickerTag

### PR DESCRIPTION
**Pull request by jbalsas**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/89227 with the following changes:
- Replaced `className` attribute by `cssClass` to follow old pattern
- Replace usages of `className` in JSPs inside `clay:` tags

On top of that, this PR contains:

### `clay:icon`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation

### `clay:badge`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation
- Replacement of raw html usages. This should be fine performance-wise now... 🤞 

### `clay:label`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation
- Replacement of raw html usages. This should be fine performance-wise now... 🤞 

### `clay:sticker`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation
- Replacement of raw html usages. This should be fine performance-wise now... 🤞

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, does this make any sense? how can we get 167 out of 170 tests passing but a compileJSP failure that should make `ant all` fail? Can you help me understand how's this possible?

I'm going to retry one last time.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Comment by john-co** [comment]
Yes, this doesn't seem to make sense...It's possible that there's a fluke in the modules-compile-jdk8 job. I believe `ant all` is run in a master node and the other test batches run in separate nodes.

@gaborlovasdotcom can you investigate the error in https://github.com/jbalsas/liferay-portal/pull/2173#issuecomment-634869291 ?

cc/ @xbrianlee have you seen this before?

```
     [exec] > Task :apps:oauth2-provider:oauth2-provider-web:compileJSP
     [exec] 
     [exec] > Task :apps:oauth2-provider:oauth2-provider-web:compileJSP FAILED
     [exec] > Task :apps:oauth2-provider:oauth2-provider-web:zipZippableResources UP-TO-DATE
     [exec] > Task :apps:oauth2-provider:oauth2-provider-web:jarSources
     [exec] > Task :apps:fragment:fragment-web:jar
     [exec] > Task :apps:fragment:fragment-web:autoUpdateXml SKIPPED
     [exec] > Task :apps:fragment:fragment-web:downloadJSDoc SKIPPED
     [exec] > Task :apps:oauth2-provider:oauth2-provider-web:jarSourcesCommercial
     [exec] > Task :apps:oauth2-provider:oauth2-provider-web:copyTLDDocResources NO-SOURCE
     [exec] > Task :apps:oauth2-provider:oauth2-provider-web:validateTLD
     [exec] > Task :apps:fragment:fragment-web:jsdoc
     [exec] > Task :apps:fragment:fragment-web:jarJSDoc
     [exec] > Task :apps:fragment:fragment-web:jarJSP
     [exec] > Task :apps:fragment:fragment-web:jarSources
     [exec] > Task :apps:fragment:fragment-web:jarSourcesCommercial
     [exec] > Task :apps:fragment:fragment-web:assemble
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/mapper/ScopeMapper.java:29: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/mapper/ScopeMapper.java:41: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/matcher/ScopeMatcher.java:49: warning - Tag @link: reference not found: com.liferay.oauth2.provider.scope.spi.prefixhandler.PrefixHandler
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/matcher/ScopeMatcher.java:49: warning - Tag @link: reference not found: com.liferay.oauth2.provider.scope.spi.scopemapper.ScopeMapper
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/matcher/ScopeMatcher.java:49: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/matcher/ScopeMatcher.java:61: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/matcher/ScopeMatcher.java:79: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/matcher/ScopeMatcherFactory.java:27: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/matcher/ScopeMatcherFactory.java:36: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/descriptor/ScopeDescriptor.java:28: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/descriptor/ScopeDescriptor.java:38: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/prefix/handler/PrefixHandler.java:27: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/prefix/handler/PrefixHandler.java:34: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/prefix/handler/PrefixHandler.java:56: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/prefix/handler/PrefixHandler.java:66: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/prefix/handler/PrefixHandlerFactory.java:31: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/prefix/handler/PrefixHandlerFactory.java:41: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/finder/ScopeFinder.java:29: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/scope/finder/ScopeFinder.java:37: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/application/descriptor/ApplicationDescriptor.java:28: warning - @review is an unknown tag.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-spi/src/main/java/com/liferay/oauth2/provider/scope/spi/application/descriptor/ApplicationDescriptor.java:37: warning - @review is an unknown tag.
```

**Comment by john-co** [comment]
I fetched this branch and ran `gradlew compileJSP` on `oauth2-provider-web` and `modules` but could not reproduce the issue. My guess is it was a fluke on a slave node that ran the module-compile test batch.

**Comment by xbrianlee** [comment]
@john-co This failure didn't come up in our test analysis today. Could this failure be related to the changes to `oauth2-provider-web` in this PR?

```
     [exec] > Task :apps:fragment:fragment-web:zipZippableResources UP-TO-DATE
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-web/build/jspc/org/apache/jsp/admin/assign_005fscopes_005ftree_jsp.java:529: error: variable _jspx_temp0 is already defined in method _jspService(HttpServletRequest,HttpServletResponse)
     [exec]             javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new assign_005fscopes_005ftree_jspHelper( 1, _jspx_page_context, _jspx_th_oauth2$1tree_tree_0, null);
```

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Will push this directly to BChan.

**Comment by john-co** [comment]
Pushed to https://github.com/brianchandotcom/liferay-portal/pull/89310

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
