### PR TITLE
LPS-76263 DO NOT MERGE: provide side by side comparison of jsp taglib and soy taglib

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

Here is the first pass at migrating the `version-diff-comparator` tag. What I did for this initial PR was left the original tag in place and created an entirely new tag so that both could be used side by side so that it's easy to compare the behavior between the two (obviously not intended for merging).

Some things to take note of:

1) `msg` tag doesn't appear to translate on the server side.

Not sure if this is a known issue or not, but when using Soy's `msg` tag you will see a flash of the unformatted language key. In the mean time I'm just passing an object of [translated keys](https://github.com/jbalsas/liferay-portal/pull/917/commits/41936ee915b42f6136e287fabbf945014d74a19e#diff-fa995d6875a3bef24a6765670bf303ceR10) to the template.

2) `html` params are passed to the template differently between server and client side.

For the [diffHtmlResults](https://github.com/jbalsas/liferay-portal/pull/917/commits/41936ee915b42f6136e287fabbf945014d74a19e#diff-f9a94578d6f7fa811c351acd86fe9f84R205), it's correctly passed as an html string on the server. On the client side however, it is passed as an object with the real value nested. Because of this discrepancy I had to use a [setter](https://github.com/jbalsas/liferay-portal/pull/917/commits/41936ee915b42f6136e287fabbf945014d74a19e#diff-312ede4f6e02fb1c3851c1b1a41c3b76R119) for that property to resolve the value when it is passed as an object.

3) Markup

I left the markup pretty much how it was. I have a feeling that this component could better implement Lexicon design patterns, but I didn't think this issue is the right place for those changes.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53928. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/820f5edbf107~2...820f5edbf107) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53968. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/25ad459bee9e~3...25ad459bee9e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53983. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/c7839624266c~4...c7839624266c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
