### PR TITLE
LPS-78673 Removes unecessary title attribute from alloyeditor element

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @diegonvs, this is a change I've always been resisting to apply. The title helps users on screenreaders to know what's going on. Could you check before and after to see how things sound when interacting with the editor with a ScreenReader enabled?

A technique that could be used would be to move the `title` attribute to `data-title` on mouseover and back to `title` on mouseout.

Could you explore those 2 things and let me know how it looks?

Thanks!

**Comment by diegonvs** [comment]
Hey, @jbalsas I'm using [Chrome Vox](http://www.chromevox.com/) as screenreader and I have the same behavior from current master implementation. I've made some markup tests and I've noticed that is `aria-label` attribute it's the most significative to the screen reader. `title` attribute has the same behavior of `aria-label` but shows up a tooltip with a value. Using `title` against `aria-label` sounds redundant and `aria-label` is most significative.

**Comment by jbalsas** [comment]
Awesome, @diegonvs! Thanks so much for checking!

I'll push this forward then! 👍

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59487. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
