### PR TITLE
LPS-86127 Update lockfiles

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2008. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/9397bdb6ee10~3...9397bdb6ee10) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1543. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/ae58667ff7ea~5...ae58667ff7ea) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65718. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f32f005b431b~6...f32f005b431b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2009. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f32f005b431b~6...f32f005b431b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
