### PR TITLE
LPS-81147, LPS-81148

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hey @robertoDiaz,

Attached is an update for http://issues.liferay.com/browse/LPS-81147 and https://issues.liferay.com/browse/LPS-81148.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @sergiogonzalez based on how big this is, I'd wait until after release to push this through... what do you think?

**Comment by sergiogonzalez** [comment]
Sounds good to me @jbalsas

**Comment by jbalsas** [comment]
Hey @jonmak08, I'm going to be closing this for now to give my OCD a little rest 😂 

We'll revisit this after release and figure out if we can reuse this PR :)

Thanks!

**Pull request closed without merging**
