### PR TITLE
LPS-91967 Enable yarn-offline-mirror

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
@jpince - Are the failures in this pull known issues or specific to this pull?

**Comment by jpince** [comment]
@petershin backend test results are consistent with upstream, and upgrades tests are also failing in upstream

please contact @john-co if you're concerned about functional test failures

**Comment by john-co** [comment]
@petershin the compile failures look unique to this pull.

The first 2 formatting errors look unique against upstream:
 ```    [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Add the string ' ' to the previous literal string: ./modules/apps/document-library/document-library-asset-auto-tagger-google-cloud-natural-language/src/main/java/com/liferay/document/library/asset/auto/tagger/google/cloud/natural/language/internal/GoogleCloudNaturalLanguageDocumentAssetAutoTagProvider.java 239 (Checkstyle:ConcatCheck)
     [java] 2: When concatenating multiple literal strings, only the first literal string can start with ' ': ./modules/apps/document-library/document-library-asset-auto-tagger-google-cloud-natural-language/src/main/java/com/liferay/document/library/asset/auto/tagger/google/cloud/natural/language/internal/GoogleCloudNaturalLanguageDocumentAssetAutoTagProvider.java 239 (Checkstyle:ConcatCheck)
```

also compile-jsp looks unique
```[exec] * Exception is:
     [exec] org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':apps:frontend-editor:frontend-editor-ckeditor-web:buildCKEditorScayt'.```

I don't see any related functional errors.

cc/ @jpince

**Comment by jpince** [comment]
@john-co SF errors were fixed in upstream after Peter sent the pull https://github.com/liferay/liferay-portal/commit/ae1dfd86dab26691fd1c3906619376a76a46dadd

thanks for seeing the compile-jsp error.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70297. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
