### PR TITLE
LPS-75754 Allow video tag in blogs

### PR DESCRIPTION
**Pull request by martamedio**
Hey @jbalsas 

I'm sending you a possible solution for [LPS-75754](https://issues.liferay.com/browse/LPS-75754). Please, validate it because I understand it's something that depends on the frontend team.

Although the issue indicates that the problem it is related to AntiSamy I think that is not the case and it's a problem in the editor.
When including the `<video>` tag at HTML view, is deleted when switching to preview mode; and it looks like it's something we should allow. 
I have added in the configuration of the editor the [necessary code to accept the tag](https://github.com/jbalsas/liferay-portal/pull/1793/commits/06b245684c449fbbc4ce64b184cf7697f80673e7).

Please, let me know if I'm missing something.
Thanks! 

cc/ @julien

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @martamedio, this is a specific blogs configuration, so it's up to the Collaboration team to decide. We only control the general configuration, which blogs overrides here based on their product requirements. Please, would you mind sending this over to @adolfopa?

Thanks!

**Comment by martamedio** [comment]
Sure @jbalsas 

Thanks and sorry for the inconvenience, I thought it was up to your team.

**Comment by jbalsas** [comment]
No worries, @martamedio, just want to make sure that we don't override specific product decisions without the required knowledge! :)

**Pull request closed without merging**
