### PR TITLE
Lps 79216 example

### PR DESCRIPTION
**Pull request by mtambara**
@jbalsas This is an example of using `DynamicSectionTag`. Two customizations are included: `DispatchDynamicSection` and `TextDynamicSection`. `DispatchDynamicSection` shows how you can dispatch to a JSP and then return the output back to `DynamicSectionUtil` for further customization. It also uses the `useOriginalBody` attribute, which will use the original body from the first usage of the `DynamicSectionTag`. `TextDynamicSection` shows how you can add simple headers and footers in java without dispatching to a JSP.

Let me know if you have any questions or want to modify the design

cc @shuyangzhou

### CODE REVIEW

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/4300. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1561. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @mtambara, the first question that comes to mind is, why creating another bundle for this? Wouldn't this make more sense inside `liferay-frontend-taglib`, so we'd haver `liferay-frontend:dynamic-section`? We should probably also move in there `dynamic-include` so it becomes `liferay-frontend:dynamic-include`. This would bring some nice symmetry to the tags.

What do you think?

**Comment by mtambara** [comment]
Hi @jbalsas, that all sounds good to me. I'll move dynamic-include in a separate ticket. I'm also going to add a new interface in case a customer wants to completely replace the content of a `dynamic-section` tag which will skip evaluating the body. This is just meant to be a performance improvement for an edge case

**Pull request closed without merging**
