### PR TITLE
[TS] LPS-88124 The notification message only appears at the first time when upload exceeded size file or invalid extension file

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @jbalsas ,

I've just resolved conflicts, Can you please review it?
/cc @natocesarrego

Thanks in advance.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by ling-alan-huang** [comment]
ci:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
Hi @jbalsas ,

I just edited the Reproduction Steps, could you review it again?
https://issues.liferay.com/browse/LPS-88124

Thank you so much,
Alan

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/julien/liferay-portal/pull/83. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
