### PR TITLE
LPS-61847 - migrate control-menu styles to theme contributor

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Chema,

Attached are the changes to migrate the control-menu styles to a theme contributor. I included the styles from the control-menu-taglib in 469091c.

Next I'm going to start exploring adding an 'active' state to contributors, and possibly the 'exclusive' vs 'additive' states.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/juliocamarero/liferay-portal/pull/3924. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @mjbradford89, thanks a lot for working on this!

I've forwarded it to @juliocamarero since we are moving the theme contributors from `frontend-theme-contributor` to their specific apps, and because it will conflict with other styling fixes they're currently applying. He will take care of merging the changes and moving the contributor to its final destination.

Thanks again!

**Pull request closed without merging**
