### PR TITLE
LPS-77241 - Compat modal footer buttons separation

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

image

**Comment by marcoscv-work** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54816. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54914. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/eeaadbbdb73f~3...eeaadbbdb73f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54915. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/8a3ecec61651~3...8a3ecec61651) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
