### PR TITLE
LPS-76265 Fixes smoke test. Title content is uppercase

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @alee8888, could you please get someone to take a look at these functional test failures? I fixed one, but it's hard for me to decipher what the errors actually mean... :(

**Comment by jbalsas** [comment]
Hey @ale8888 I'm working on https://github.com/jbalsas/liferay-portal/pull/916 which is basically the same theme, but removing all the uppercase modifiers, so we can move on without major delays and figure out the uppercase transform later.

**Comment by alee8888** [comment]
ci:reopen

**Comment by alee8888** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @alee8888, I'm going to keep this one closed so we don't inadvertently send it over. Remember #916 is the one we want to push forward!

**Pull request closed without merging**
