### PR TITLE
[TECHNICAL-SUPPORT] LPS-87348

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim 

Notes from Brian
> https://issues.liferay.com/browse/LPS-87348
> 
> The issue here is that, browsers will by default try to download or open files.
> 
> This default behavior of browsers become an issue when a user is creating content or editing existing content through Liferay's AlloyEditor. If a user drops a media file, for ex. an image or a video, but accidentally drops the said file into non-editable areas where AlloyEditor's drag&drop listeners are not triggered, the default browser behavior will be triggered and the file will be opened in the browser.
> 
> The problem with this is that users will lose all unsaved progress.
> 
> My fix is an implementation of the suggestion made here: liferay/alloy-editor#903 (comment). If a file is dropped in non-editable areas, an alert will ask the user whether they would like to proceed and warn that unsaved changes will be lost.
> 
> For the language key message itself, we have to implictly tell users that the default browser behavior will be triggered if the content is dropped on non-editable areas. The current iteration of the message was an attempt to minimize the potential wordiness and still retain the clarity.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @SamZiemer, @brianikim, I think this needs a lot more thought. What I said is that this is not an `AlloyEditor` issue. 
- It happens too if you go to the `Document Library` and try to drag/drop files to upload, either on the general view or while using the `multiple upload` feature.
- It happens in Blogs (cover-image) or other places where you have image selectors that allow drag-dropping

We need to analyze if we want to prevent this as a general rule. Enabling this only when an editor is on the page will cause some frustration and unexpected behaviour.

I'm cc'ing @antonio-ortega so we can go over this soon.

**Comment by antonio-ortega** [comment]
Hi @brianikim , @SamZiemer ,

In case you get stuck developing the solution proposed by Chema, I would suggest you to open a PTR and assign it to SME Frontend Infra, so I can help you to find out the way to do it.

Thanks.

Regards.

Ps: And regarding a more general case, if you are not completely sure about some pull request, you can send it to me just for a first review, so maybe I can help you ;)

**Comment by brianikim** [comment]
Hello @jbalsas,

I understand your concerns here. As @antonio-ortega has mentioned, I will open up a PTR so that we can have clear, defined scope for the potential implementation.

Sincerely,
Brian Kim

**Pull request closed without merging**
