### PR TITLE
LPS-79411 Add fetch method to PortletBase

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
@jbalsas yep, I was destroying the global fetch function :sweat:

**Comment by p2kmgcl** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56906. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
