### PR TITLE
LPS-99144 Fix for ES5 that doesn't support shorthand code causing IE11 compile error

### PR DESCRIPTION
**Pull request by mclomello**
@jbalsas Could you review this pr?

I already talked to @matuzalemsteles about this change. 
Basically the Internet Explorer 11 doesn't support ES6 and this change is to fix it.

Best regards,

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@jbalsas can you please review? This is a blocker for 7.2.

cc/@esthersanz

**Comment by brianchandotcom** [comment]
@mclomello @jbalsas I merged this after talking to Chema on Slack.

**Comment by brianchandotcom** [comment]
@mclomello I also sorted it in 87d3cd8 

I asked @jbalsas and he said it was OK to sort it. I always like to sort.

**Comment by brianchandotcom** [comment]
ci:close

**Pull request closed without merging**
