### PR TITLE
LPS-77392

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi @jbalsas ,

As you can see I've prepended the CDN to the **base** parameter of the element. This works, but I'm not sure if the **root** parameter should look the same. According to the documentation I've found:

https://yuilibrary.com/yui/docs/api/classes/Loader.html

in my opinion the CDN url fits better in **base**. Please feel free to make any changes (or ask me to make them).

Thanks in advance :)

**Comment by jbalsas** [comment]
Hey @crodriguezy, I think base is fine, but what about all other js modules? Are they being loaded correctly through the CDN? This PR should imply that they aren't...

Maybe we should fix [themeDisplay.setPathJavaScript](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/events/ServicePreAction.java#L789-L791) so that [PATH_JAVASCRIPT](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/modules.js#L12) contains the CDN for all modules?

**Comment by crodriguezy** [comment]
Hi @jbalsas, 
According to my tests, adding the CDN host to the general javascript path fails when conatenation happens. See the example:

_Loading failed for the <script> with source “http://cdn.local:8080/combo/?browserId=firefox&minifierType=&languageId=en_US&b=7100&t=1516877466083**&http://cdn.local:8080/**o/frontend-js-web/aui/escape/escape-min.js**&http://cdn.local:8080**/o/frontend-js-web/aui/base-core/base-core-min.js**&http://cdn.local:8080/**o/frontend-js-web/aui/base-observable/base-observable-min.js&http://cdn.local:8080/o/frontend-js-web/aui/aui-widget-cssclass/aui-widget-cssclass-min.js**&http://cdn.local:8080/**o/frontend-js-web/aui/aui-widget-toggle/aui-widget-toggle-min.js**&http://cdn.local:8080/**o/frontend-js-web/aui/timers/timers-min.js”_

Have you considered this? I've been thinking about other possibilities, but in my opinion it is not a trivial change and should be studied more deeply. So I decided to apply a solution only for that specific module, which is the one the client requires.

Thank you!

**Comment by jbalsas** [comment]
I'm closing here, since @izaera will pick this up

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
