### PR TITLE
LPS-104565 - General card padding fix

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
**LPS-104583**
image

**LPS-104565**
image

image

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80938. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
