### PR TITLE
LPS-91967 Yarn

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by jbalsas** [comment]
🙈😭😭 @john-co, please analyze and advice

**Comment by john-co** [comment]
@petershin @jbalsas The functional tests look unrelated.

However, the npmBuild errors we're seeing seem to be caused by downstream servers that cannot find liferay-npm-scripts. Something I've noticed is that this is resolved consistently when I run ant all locally. Ant all is not run in downstream servers but rather minimal commands to setup files. So from what I'm able to gather, there must be something that ant all does to prepare liferay-npm-scripts and yarn stuff available that's not being run on the downstream servers. I'm not familiar with npm repos or ant all process enough to accurately diagnose how it's being generated at this point. Currently, I'm trying to see if I can get the exact steps that downstream servers run to reproduce the issue.

**Comment by john-co** [comment]
@jbalsas I think we've narrowed down the issue. `ant compile` seems to set up the yarn dependencies such as `liferay-npm-scripts`. Since the downstream servers don't run this command, QAE will see if someone can add this into the build process.

**Comment by yichenroy** [comment]
@jbalsas @petershin 
This commit will need to be added to resolve the npm issues on missing liferay-npm-scripts command or similar errors that happened on the compile-jsp-jdk8 and deprecated-module-smoke-jdk8 batches (and any other batches that could have failed on the same problem).

https://github.com/yichenroy/liferay-portal/commit/8d476a40c9b5f2caadd97dce55a2f5e86d05f15c

This is because, as @john-co explained above, CI does not run _ant compile_ on the downstream batch jobs so the yarn dependencies were never set up on the VMs.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1699. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/c981a07f8fb8~1...c981a07f8fb8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
