### PR TITLE
LPS-79709 Migrate frontend-js-node-shims to new bundler

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:step

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58320. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/ee79d5fde6e6~1...ee79d5fde6e6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
