### PR TITLE
LPS-96291 | Horizontal scrolling in a permissions popup v2

### PR DESCRIPTION
**Pull request by markocikos**
Hey @jbalsas ,

This PR is a rework of the solution in https://github.com/jbalsas/liferay-portal/pull/1838. It almost entirely relies on CSS to achieve the goal, which results in simpler code and better performance. The only addition to JS is the sync between the horizontal scroll and the fixed header scroll; I believe the sync approach is better than math-based transforms. But, to achieve this I needed to add a bit of HTML to the fixed header, so that it too can have CSS-based scrolling.

Please review the code.

Thank you!

/cc @travisrcory

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @drewbrokke, @travisrcory would you mind taking a look see what you think?

**Comment by travisrcory** [comment]
@markocikos you are a true CSS whiz. @jbalsas this looks good to me!

**Comment by drewbrokke** [comment]
@markocikos @jbalsas it works wonderfully. Thanks for the help with this! 

Just to verify, this also works in IE? I see that you didn't use `sticky` in the CSS, so it seems like it should be fine, but I thought I'd double-check. 

If so then LGTM 👍

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Looks pretty good to me too! Passing some tests and then sending to @eduardoallegrini for final inspection!

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
> Just to verify, this also works in IE? I see that you didn't use `sticky` in the CSS, so it seems like it should be fine, but I thought I'd double-check.

@drewbrokke I tested it on IE11 and it does work.

**Comment by markocikos** [comment]
See https://github.com/eduardoallegrini/liferay-portal/pull/23

**Pull request closed without merging**
