### PR TITLE
LPS-89612 New fragments colors

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
The classes names are:

```
bg-fragment-blue
bg-fragment-indigo
bg-fragment-purple
bg-fragment-pink
bg-fragment-red
bg-fragment-orange
bg-fragment-yellow
bg-fragment-green
bg-fragment-teal
bg-fragment-cyan
bg-fragment-white
bg-fragment-gray
bg-fragment-gray-dark

text-fragment-blue
text-fragment-indigo
text-fragment-purple
text-fragment-pink
text-fragment-red
text-fragment-orange
text-fragment-yellow
text-fragment-green
text-fragment-teal
text-fragment-cyan
text-fragment-white
text-fragment-gray
text-fragment-gray-dark
```

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
SF update in:
modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/application/_fragments.scss

We need a tabulation

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67432. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/ee61b4f39d31~1...ee61b4f39d31) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67433. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/b655f9ef6748~1...b655f9ef6748) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
