### PR TITLE
LPS-82336

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-82336.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @jonmak08, @joshuacords, @SamZiemer, @RobTangLR, thanks for sending this over. As you might be aware, we're halting some PRs until after the release to minimize the risk of regressions.

I'll be processing this for `master` and `7.1.x` in a couple of weeks at most. If you need to expedite it, I think there's a process by which it can be directly sent to `7.0.x` and forward-ported after.

Thanks!

**Comment by joshuacords** [comment]
Hello @jbalsas,

Do you need this rebased or anything else to review this?

**Comment by jbalsas** [comment]
Hey @joshuacords, sorry for the lack of updates. I think this should be fine rebase-wise.

I actually took a brief look yesterday and shared this with @antonio-ortega. We have some doubts regarding the solution, so we need some extra time to evaluate it. If you could walk us through what you tried, that might help us.

Thanks!

**Comment by joshuacords** [comment]
Hello @jbalsas,

Here's the description of the problem and approach from a previous pull:

> Problem: When a user's session is shared between 2 browser windows, extending the session on one window will reset the timestamp cookie (which the other window will see) but will not reset the sessionState in the other window. This makes it so the other window's warning will not reappear when the extend warning should appear on both windows.
> 
> Solution: Keep track of the current timestamp locally, and update the sessionState and the timestamp if the session is extended on another page.

Let me know if you have any further questions or needs.

**Comment by joshuacords** [comment]
Hello @jbalsas, have you come to a conclusion about this? Is there something else I could provide you?

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61389. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/0fc58accf446~1...0fc58accf446) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
