### PR TITLE
LPS-86130 SF

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2048. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f8be4d4b22a7~1...f8be4d4b22a7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
