### PR TITLE
LPS-100959 Updates icons in legacy aui-treeview component

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
@john-co, I think this looks good, right?

**Comment by john-co** [comment]
Looks good to me! :+1:

**Comment by jbalsas** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/79660

**Pull request closed without merging**
