### PR TITLE
LPS-66534 Image editor tests

### PR DESCRIPTION
**Pull request by kenjiheigel**
@jbalsas, this includes @ithildir's review as well as the shrinkwraps regenerated using the new gradlew npmShrinkwrap command. Sending this over to you to continue the review process. Let us know if you have any questions!

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @kenjiheigel, @Ithildir, I want to work on this (and add something on top of it), but there are already a lot of changes and it's going to be hard to review when it goes to Brian.

Would you mind if I squash all these commits per-module so it will make more sense in the final history?

**Comment by kenjiheigel** [comment]
@jbalsas, that sounds fine to me. Whatever makes it easier!

**Pull request closed without merging**
