### PR TITLE
LPS-114143 Autogenerates iframeProps.id from props.id in case none is provided

### PR DESCRIPTION
**Pull request by jbalsas**
Hey myself, and @markocikos!

Task history:
- https://github.com/wincent/liferay-portal/pull/295
- https://github.com/wincent/liferay-portal/pull/303
- https://github.com/wincent/liferay-portal/pull/304
- https://github.com/jbalsas/liferay-portal/pull/2178
- https://github.com/markocikos/liferay-portal/pull/188
https://github.com/jbalsas/liferay-portal/pull/2195

Changes from https://github.com/jbalsas/liferay-portal/pull/2195
- Autogenerated `iframeProps.id` from `{$id}_iframe_` so we can provide a more obvious API (`id` vs `iframeProps.id`) while still allowing `iframeProps` when needed. This also reduces the need for always passing `iframeProps.id` even when `id` is passed.

Changes from https://github.com/markocikos/liferay-portal/pull/188:
- In two cases where we are opening modal in modal, we are invoking utility with `Liferay.Util.getOpener().Liferay.Util.openModal`. This results in inner modal rendering as a sibling of opener modal. CI test should now work normally, and there are no style issues. I tried to make this an inner mechanism of utility, by adding check if we are in modal, setting variable `document` and `window`. I don't think this is possible. `document` and `window` are global read-only objects, used by not only in utility but by Clay and / or React. The solution in PR can be a good enough solution for now, the proper solution is to redesign into avoiding modal in modal.
- Extended API with `iframeProps`
- Set `iframeProps.id` in two cases CI tests expects them, reverted all changes on CI tests.
- Updated unit tests.

Please review the code.

Thank you!

/cc @wincent @austinchiang

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @markocikos, as usual, I messed this up 😂 

Do you mind picking this up, rebasing and testing to make sure this is good to go?

Thanks!

**Comment by markocikos** [comment]
Followup in https://github.com/jbalsas/liferay-portal/pull/2197

**Comment by markocikos** [comment]
ci:close

**Pull request closed without merging**
