### PR TITLE
LPS-63038 Generated URLs to access CSS contents from CKEditor or TinyMCE that do not include themeId parameter may lead to use the default theme or another theme instead of the current theme

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:retest

**Comment by dacousalr** [comment]
ci:retest

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43996. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
