### PR TITLE
[Lex][Mig][Dep] TranslationManager

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Chema,

Attached is an update for the following: [LPS-60722](https://issues.liferay.com/browse/LPS-60722), [LPS-60665](https://issues.liferay.com/browse/LPS-60665), [LPS-61115] (https://issues.liferay.com/browse/LPS-61115).

I labeled this pull as '[Lex][Mig][Dep] TranslationManager' because it contains the following:

-Lexicon changes
-Migration changes
-Deprecation/removal changes

Please let me know if I've labeled it incorrectly.

In this pull I've addressed what you mentioned in the last pull (https://github.com/jbalsas/liferay-portal/pull/297#issuecomment-167959007).  This includes:

-Update liferay-aui.xml instead of liferay-aui.tld, and then running ant build-taglibs to update the tld.
-Merge BaseTranslationManagerTag and TranslationManagerTag into one class.
-Migrated the corresponding JavaScript
-Migrated the lang keys unique to this taglib.

Please let me know if there are any other issues.

Thanks!

/cc @jonmak08

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/1076. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/d8c308e~2...d8c308e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @mjbradford89, thanks a lot for this, great work! Just a couple of comments:

- The `JS-Config` property needs to point to the `config.js` file. This is loaded in the beginning to properly configure the loaders.
- I forgot to mention that we should create the Freemarker Taglib Contributor for this bundle. We need to have this to make sure all taglibs are available to templates
- The translation extraction was not quite right. Instead of moving the keys from one place to another, running `buildLang` generates them again (you can verify this by the _(Automatic Translation)_ part), so any user-created translations will be lost. For the extraction, we do the following:
    - Extract the general keys from `portal-impl` to the module
    - Update and execute the attached groovy script
    - Run (this can be done by Brian) `ant build-lang`

Thanks a lot!

[language-properties.groovy.zip](https://github.com/jbalsas/liferay-portal/files/78292/language-properties.groovy.zip)

**Comment by jbalsas** [comment]
BTW, awesome labelling skills!! :wink:

**Comment by mjbradford89** [comment]
Hey @jbalsas, thanks for fixing those issues! I'm not sure what was going through my head when I set that js config property that way. I think all the recent time off has turned my brain to mush :)

**Pull request closed without merging**
