### PR TITLE
LPS-57148

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@natecavanaugh @ipeychev can you resend?

1.) Code that is sucked in from another repo should not be checked in.

2.) All the other modules in frontend have *-web because they are accessible from the web. This one doesn't. Is that accidental or on purpose?

Thx guys!

**Comment by brianchandotcom** [comment]
See https://github.com/jbalsas/liferay-portal/pull/200

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/28506

**Comment by jbalsas** [comment]
Reworked as agreed after discussing it and resent to https://github.com/brianchandotcom/liferay-portal/pull/29662

**Pull request closed without merging**
