### PR TITLE
LPS-92099 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-92099

### CODE REVIEW

**Comment by john-co** [comment]
Hi @jbalsas,
Here are the test fixes that go with the commit. I did notice that the markup changes did not affect formbuilder tabs such as the ones found in DDL data definition and WC Structure. Please see attached image.
Selection_009

**Comment by john-co** [comment]
and also found workflow tasks was missing the update. 
Selection_011

Did we want to include the markup in DDL/Web Content and Workflow too?

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70121. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by john-co** [comment]
Hi @jbalsas, this was merged without feedback on markup changes for DDL/WebContent and Workflow. These are the areas affected that don't have navtab or some variation updated to nav-link:

Workflow
https://testray.liferay.com/reports/production/logs/test-1-16/1553637781468/test-portal-acceptance-pullrequest(master)/4005/functional-tomcat90-mysql57-jdk8/31/2/LocalFile.Staging_StagingOnlyApprovedPublishToLive/index.html.gz

DDL
https://testray.liferay.com/reports/production/logs/test-1-16/1553637781468/test-portal-acceptance-pullrequest(master)/4005/functional-tomcat90-mysql57-jdk8/28/0/LocalFile.CPDynamicdatalists_AddFormTemplate/index.html.gz

Web Content
https://testray.liferay.com/reports/production/logs/test-1-16/1553637781468/test-portal-acceptance-pullrequest(master)/4005/functional-tomcat90-mysql57-jdk8/23/0/LocalFile.CPRolesCPWebcontent_AddStructureSiteRoleDefinePermission/index.html.gz

I'll add a workaround for now since this was merged.

**Comment by john-co** [comment]
Fix sent https://github.com/brianchandotcom/liferay-portal/pull/70139

**Pull request closed without merging**
