### PR TITLE
LPS-105705 | Create collapsible utility | v4

### PR DESCRIPTION
**Pull request by markocikos**
Hey @jbalsas 

This is a followup on https://github.com/wincent/liferay-portal/pull/112, https://github.com/jbalsas/liferay-portal/pull/2060 and https://github.com/jbalsas/liferay-portal/pull/2065

Notes:
- We cannot do a loop on `liferay-collapse` nodes, like you suggested [here](https://github.com/jbalsas/liferay-portal/pull/2065#issuecomment-567505086). It is because `liferay-collapse` nodes are triggers, not containers. Panel that is collapsed by a trigger can be anywhere in dom, they are linked through trigger's `href` attribute. With the previous solution, we could manually set `containerId` in each application. With the global init, our options are limited. We could search for closest common ancestor, but that becomes a bit complicated as there can be nesting of collapsible elements. Much simpler solution, as is original Bootstrap solution, is to have a global listener.
- I am not sure if there is a better way to keep only a single listener, than keeping track of it in global `Liferay.CollapseProvider`. Another reason for this approach is that we are using `node.collapse('hide')` and `node.collapse('show')` in few places, for example [here](https://github.com/liferay/liferay-portal/blob/1aab1cd79c35bef0781f5f2095c6928243d0be16/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/liferay.js#L96) and [here](https://github.com/liferay/liferay-portal/blob/1aab1cd79c35bef0781f5f2095c6928243d0be16/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/form.js#L321). Those lines, with the current solution, could be replaced with `Liferay.CollapseProvider.hide(target)`.

Please review the code.

Thank you!

/cc @wincent

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @markocikos! I think we can just use `.js` here instead of `.es.js`. Since we already compile them both and there's no mix here, no need to make the distinction.

Could you start renaming those while I keep doing the review?

Thanks!

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by markocikos** [comment]
@jbalsas I pushed commit that changes file names. Did that stop CI? The summary comment got deleted.

**Comment by jbalsas** [comment]
No, CI should still be running... I've tested manually and it looks great, will probably push to Brian and retest over there!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82335. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
