### PR TITLE
LPS-70652 Theme Contributor resources are loaded on every page, data-senna-track should be set to permanent

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

Wanted to get your input on this in case I was mistaken, but if theme contributor resources are indeed loaded on every page, these `data-senna-track` attributes should be set to `permanent`.

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by jbalsas** [comment]
Makes sense, @Robert-Frampton!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50383. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Actually, I might've spoken too soon... maybe we changed this because it might cause issues when switching themes. Going to test now!

**Comment by jbalsas** [comment]
Nah, I think we're good

**Pull request closed without merging**
