### PR TITLE
LRQA-27491 Frontend JS PR tester prototype

### PR DESCRIPTION
**Pull request by kenjiheigel**
@jbalsas, this is a prototype of the frontend JS tests. I've set this pull to only run the frontend JS test.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Just to describe what I did a little bit... 

After talking with @ithildir, it would be easiest to add a task for testJS in each module's build.gradle that requires testing. This is done here: 
https://github.com/jbalsas/liferay-portal/pull/585/commits/842886c4150ff2a13b97efc6d8e80b358dfafde3

For this, I opted not to use the metal-karma-config, so we could have more explicit control over the configuration. Once I add more tests, I think I should be able to at least put a default karma.conf.js somewhere and load those. I don't think we even need to have all those npm packages either, so we could probably cut those down a bit. We'll still need to get around having to update each package.json with all those dependencies though.. so we might end up having to use metal-karma-config anyways to make it easier. 

I'm going to rename the job from "portal-gulp-jdk8" to "portal-frontend-js-jdk8" or "portal-frontend-js-unit-jdk8". I used gulp to be consistent with what was already implemented. 

I'll be applying this to the rest of the Image Editor commits you made next week so we'll see how multiple test results run. 

Results will be something like this: 
frontendjs_jenkins

**Comment by kenjiheigel** [comment]
cc-ing: @jonmak08, @brunobasto, @jpince, @brianchiu

**Comment by kenjiheigel** [comment]
Closing as this pull was an example of what future frontend test results might look like.

**Comment by jbalsas** [comment]
@kenjiheigel, and a good looking one at that! 😉

**Pull request closed without merging**
