### PR TITLE
LPS-106127 If the field has a itemSelectorURL use it

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
updated!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/2072. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Rerunning at https://github.com/jbalsas/liferay-portal/pull/2072 to see if `stable` passes

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82504. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
