### PR TITLE
LPS-75714 - Make Bootstrap compatibility layer configurable to speed up the markup migration

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:open

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/marcoscv-work/liferay-portal/pull/72. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53057. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53061. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/5e13981e1639~1...5e13981e1639) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53086. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/906579ece1b6~1...906579ece1b6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/marcoscv-work/liferay-portal/pull/74. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/0163624dcc30~1...0163624dcc30) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
