### PR TITLE
LPS-70056 Updates shrinkwrap.json to use the latest version of Senna

### PR DESCRIPTION
**Pull request by fernandosouza**
Hey, Chema. This pull is related to [this issue](https://issues.liferay.com/browse/LPS-70056)

The problem is fixed in the latest version of Senna but `Liferay Portal` wasn't downloading it because only the `package.json` file was pointing to the `2.1.3` version, but it was missing in the `npm-shrinkwrap.json`.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
Hi @jbalsas, any thoughts or issues with this PR?

**Comment by jbalsas** [comment]
Hey Spencer, sorry about the delay. I'll send this in today!

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
I've talked to @fernandosouza. We need to do this change with the `gradlew npmShrinkwrap` task instead of manually. He'll be sending a PR for this soon.

**Comment by fernandosouza** [comment]
New PR sent https://github.com/jbalsas/liferay-portal/pull/678

**Pull request closed without merging**
