### PR TITLE
LPS-78807

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-78807.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @fortunatomaldonado, @jonmak08, I'm not really familiar with this part of the code, so it's hard for me to evaluate this properly... I'm forwarding it to @shuyangzhou to see if someone in core infra has knowledge of this, otherwise, I can try to take a closer look.

Sorry about the delay :(

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/shuyangzhou/liferay-portal/pull/5933. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/1cb98617d4f7~2...1cb98617d4f7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @fortunatomaldonado, @jonmak08, I talked to @brunobasto and we'll likely push this forward. The only concern is if this is to be backported, it could break existing js code using the changed names and id selectors.

**Comment by fortunatomaldonado** [comment]
Hello @jbalsas, thank you for the information. Could you go into more detail on how the backport could break existing js code? 
Thank you for your help!

**Comment by jbalsas** [comment]
Sure, @fortunatomaldonado, 

```
<select class="form-control" id="<portlet:namespace /><%= randomNamespace %><%= HtmlUtil.getAUICompatibleId(name) %>"

<script>
    // This used to work, but since `<portlet:namespace />` is now prefixing the select tag id, the selector is no longer valid
    var selectId = '<%= randomNamespace %><%= HtmlUtil.getAUICompatibleId(name) %>';

    document.querySelector('#' + selectId);
    document.getElementById(selectId);
</script>
```

**Comment by fortunatomaldonado** [comment]
Thank you @jbalsas, I see how this is an issue. Would it be possible to add the `<portlet:namespace />` to the selector?
The <portlet:namespace /> is appended when a name attribute is set for the aui:field-wrapper. This attribute is needed to create the label for accessibility purposes. I could be wrong, but I do not believe we can omit the <portlet:namespace />.

**Comment by jbalsas** [comment]
Yeah, but that's exactly the nature of a breaking change. You'd be forcing customers to update their code, and this will happen in a fix-pack update, which is totally unexpected.

I don't think there'd be much usage like this, but just in case, it should be properly evaluated.

/cc @antonio-ortega

**Comment by fortunatomaldonado** [comment]
Oh okay, I understand. 
Thank you for going through this with me @jbalsas.

**Comment by jbalsas** [comment]
No problem, glad to help!

I've contacted @drewbrokke and @pei-jung to see if they can do a final review. Otherwise, I'll push it later.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/drewbrokke/liferay-portal/pull/477. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
