### PR TITLE
LPS-112871 - Replace usages of aui:col with clay:col

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@marcoscv-work FYI, first part of this made it to master: https://github.com/brianchandotcom/liferay-portal/pull/88326

**Pull request closed without merging**
