### PR TITLE
LPS-114017 - Apply the use of clay content taglib in connected-app-web

### PR DESCRIPTION
**Pull request by marcoscv-work**
As part of our effort to Improve HTML Layout Generation Strategies in DXP, here a PR about changing autofit-* and sheet-* for clay:sheet* and clay:content*

This "PR" updates markup with new taglibs. What we expect is to see the same visual design, so no visual changes are required on `connected-app-web` module.
The way to validate the changes is to see the same visual result. if is there any previously agreed difference it would be correctly pointed in comments

LPS-114017 - Apply the use of clay content taglib in connected-app-web

### CODE REVIEW

**Comment by jbalsas** [comment]
Screen Shot 2020-06-09 at 15 56 16

**Comment by marcoscv-work** [comment]
Carlos surprise call !

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/89864. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
