### PR TITLE
LPS-92480 Fix clay dropdown-menu positioning for rtl languages

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @p2kmgcl, this is what I'm seeing right now with this:

rtl_dropdown

Is this expected? Is it missing what you mentioned yesterday about yui? what was it?

**Comment by jbalsas** [comment]
Reading the LPS, you say it's `aui_deprecated`... I'll look into it

**Comment by p2kmgcl** [comment]
@jbalsas if you set dropdown position to "absolute" or "fixed", it works. That is what `aui_deprecated.css` adds

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/izaera/liferay-portal/pull/104. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/efeca23a7d55~1...efeca23a7d55) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
