### PR TITLE
LPS-114143 Update modal usages in document library

### PR DESCRIPTION
**Pull request by wincent**
Forwarding from @austinchiang's [wincent#304](https://github.com/wincent/liferay-portal/pull/304), which is itself a tweak on top of @markocikos's [wincent#303](https://github.com/wincent/liferay-portal/pull/303). Here's Marko's original message:

---

This is a followup on https://github.com/wincent/liferay-portal/pull/295

Changes:
- We are using `Set` in checking of previously selected items.
- We are using `useRef` for storing event handlers array.
- On event handler cleanups, we are clearing the array holding them as well.
- In 'access from desktop' modal, we are now focusing input after modal opens. For this, I needed to extend API with `onOpen`. As a bonus, we are cleaning up hidden dom structure that is rendered and transferred to modal. I spent way too much time today trying to figure out why `focus()` is not working, and it was because we had two elements with the same id in DOM.

The [unique failure](https://github.com/wincent/liferay-portal/pull/295#issuecomment-634023638) happened because that test expects id with a specific suffix on an iframe. AUI modal sets this [here](https://github.com/liferay/liferay-portal/blob/9a6f0dbd631d5248109a9eea7c4d769d51eb449f/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util_window.js#L187). So far we have not encountered a case in the code where this id would be relevant. I only see it [used](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util_window.js) in internal mechanisms of modal registration and events handling, which is irrelevant for new modals. We could add setting of this id, but I recommend we rather modify or remove this CI test.

For me, `Add Folder` button works normally. Please retest it on the latest code.

@liferay-echo: There is a modal in `UIItemsBuilder`, `addPermissionsToolbarItem`, that we are modifying in this PR. Where is it in UI?

@liferay-echo: We are changing the appearance of 'select folder' modals in this PR, to be full screen. See [screenshots](https://github.com/wincent/liferay-portal/pull/295#issuecomment-634049908). This follows [Lexicon guidelines for iframe modals](https://liferay.design/lexicon/core-components/modals/#iframe-in-the-body). Please review the new appearance, maybe it needs to be tweaked or reverted.

### CODE REVIEW

**Comment by wincent** [comment]
On @austinchiang's PR, [ci:test:relevant is green](https://github.com/wincent/liferay-portal/pull/304#issuecomment-635101158) but [ci:test:documents is not](https://github.com/wincent/liferay-portal/pull/304#issuecomment-635113609). I have not analyzed the failures beyond noting that they are labeled as "unique".

I did some manual QA in [the wincent#295](https://github.com/wincent/liferay-portal/pull/295) (see screenshots), but didn't have time to do any on the follow-up ([wincent#303](https://github.com/wincent/liferay-portal/pull/303)). I'll kick off `ci:test:bundle` on this one in case anybody wants to give it a shot, because I am unlikely to be able to get to this one soon.

**Comment by wincent** [comment]
ci:test:bundle

**Comment by wincent** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:documents

**Comment by markocikos** [comment]
@austinchiang I took a look at the [unique failures](https://github.com/wincent/liferay-portal/pull/304#issuecomment-635113609).

The first and the third are the same case of a test checking for ID on iframe. We should make the same change as in https://github.com/jbalsas/liferay-portal/pull/2178/commits/4e3ffc1ecfc90bf4593050121d7160b511d2f13c.

The [second one](https://testray.liferay.com/reports/production/logs/test-1-19/1590634642216/test-portal-acceptance-pullrequest(master)/6438/functional-tomcat90-mysql57-jdk8/5/0/LocalFile.DocumentsadministrationUsecase_ViewPaginationToolbarCheckboxAndMoveMultiplePaginationDocuments/summary.html.gz) is unusual. It complains that the `select-all-files` should be checked. When I use the 'add multiple documents' feature, it is checked:

screen1

But, when I add them the second time, it is unchecked. This matches screenshot in the CI test:

screen2

Could it be that we are not properly cleaning between tests? The test is expecting file to be uploaded for the first time, but it was uploaded in the previous one? Maybe in one of the other two failed tests.

**Comment by jbalsas** [comment]
@austinchiang, will you be able to adjust the missing selectors in here?

**Comment by jbalsas** [comment]
Hey @markocikos, one thing I've seen from this that we should address in a followup PR is that `id` isn't being propagated to the `iframe`, which feels weird. Also, `<iframe title` is being set to `src`. This is likely not playing nicely with screenreaders...

Since I haven't reviewed in detail in the past, maybe I'm missing some context here...

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/markocikos/liferay-portal/pull/188. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/04c9735342a0~2...04c9735342a0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
