### PR TITLE
LPS-79222

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Conflicts again, @petershin 😢 

I saw some weird errors in the log here, so I wasn't very confident... could you rebase and I'll rerun locally tomorrow?

**Comment by petershin** [comment]
@jbalsas Yup, will rebase with the latest and rerun tests

**Comment by izaera** [comment]
@petershin remember to remove this commit -> 0e6de7b0ba64906fb357340add45b65b4399144a as I have already fixed that in another PR

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Agree.  I'll look more carefully at the `inputs` and `outputs` for the `transpileJS` task for the `layout-admin-web` app.  If you know which ones are wrong, please let me know.

**Comment by petershin** [comment]
I'm looking into the errors.  Rebased with the latest here: https://github.com/petershin/liferay-portal/pull/125

**Pull request closed without merging**
