### PR TITLE
LPS-93946 Reverting to the aui taglib

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72062. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72086. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/e2408b6b323d~1...e2408b6b323d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
