### PR TITLE
LPS-89705 Runs build-taglibs (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/pavel-savinov/liferay-portal/pull/310. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jcampoy** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jcampoy** [comment]
Just started reviewing :)

**Pull request closed without merging**
