### PR TITLE
LPS-114044 - Apply the use of clay content taglib in portal-search-tuning-rankings-web

### PR DESCRIPTION
**Pull request by marcoscv-work**
As part of our effort to Improve HTML Layout Generation Strategies in DXP, here a PR about changing autofit-* and sheet-* for clay:sheet* and clay:content*

This "PR" updates markup with new taglibs. What we expect is to see the same visual design, so no visual changes are required.
The way to validate the changes is to see the same visual result. if is there any previously agreed difference it would be correctly pointed in comments

There is a `col` error case in LPS-114043, it uses `col-lg-12`, that on that case is the same as `<clay:col>`
854a6af5079332afb1c02b8b6368d59873293ec0

LPS-114043
Apply the use of clay content taglib in oauth2-provider

LPS-114044
Apply the use of clay content taglib in portal-search-tuning-rankings-web

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Bundled together at https://github.com/jbalsas/liferay-portal/pull/2189

**Pull request closed without merging**
