### PR TITLE
LPS-100140 Removes client-side validation temporarily. Server-side is already handling it

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by john-co** [comment]
[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=871300873&testrayRunIdA=871136355&statusB=2)

* functional tests are not related to PR
* the ci stable failure looks like a similar [fragment.entry issue in upstream](https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-batch(master)/39761/#showFailuresLink)

**Comment by john-co** [comment]
possible rebase issue?

**Comment by john-co** [comment]
ci:test:stable:norebase

**Comment by jbalsas** [comment]
Rebased and resent to https://github.com/ealonso/liferay-portal/pull/2622

**Pull request closed without merging**
