### PR TITLE
LPS-66054

### PR DESCRIPTION
**Pull request by juangon**
Hope is ok for you ;-)

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @juangon, thanks for sending this over! I'm doing an EVP the whole week, so I have very limited time to look into this. Just a couple of things from a brief inspection:

- About [the second commit](https://github.com/jbalsas/liferay-portal/pull/545/commits/db348bba366caf1b683b58e34e050124506ff0eb), @migue meant to look into it (and test it) before committing it, iirc...

- About the fix per se, I think this might not be the right approach. While I'm sure this makes the `ckeditor_creole` editor usable in `Blogs`, I don't think our Blogs engine can handle creole, so any blog entry created with it will render raw creole, which is not very desirable. Same should happen with `ckeditor_bbcode` (or the `alloy_*` equivalent ones...). Looking at this, I think we need an API to specify the editor output formats and the allowed input formats so we can properly match editors with consumers. That way, if you were to select an incompatible editor for your app, it would just default to the closer valid one... What do you think? Comments, @sergiogonzalez?

**Comment by juangon** [comment]
Hi @jbalsas sorry to bothering you on your EVP week :-(.

Hmm IMHO this doesn't have to do with Blogs or any other component. This will cause a nullpointerexception anytime if taglib developer doesn't set an empty map. In fact, I found this thanks to a Liferay Faces component that was rendering CKEditor Creole editor that was working fine in Liferay 6.2 (take a look at http://www.liferayfaces.org/web/guest/showcase/-/component/portal/inputrichtext/creole).

So, maybe what you said is fine from a developer perspective, but mine is much more simpler, a nullpointer exception made from a developer that doesn't have to know they have to provide a non-null object.

Thanks!

**Comment by juangon** [comment]
About the second commit @migue wanted to take a look, I didn't reinvent the wheel and I based the solution as what Miguel did here: https://github.com/juangon/liferay-portal/blob/db348bba366caf1b683b58e34e050124506ff0eb/modules/apps/foundation/frontend-editor/frontend-editor-ckeditor-web/src/main/java/com/liferay/frontend/editor/ckeditor/web/servlet/taglib/CKEditorOnEditorCreateDynamicInclude.java#L49

Thanks!

**Comment by jbalsas** [comment]
Hey @juangon, no problem at all, the wheels don't stop turning because we're out of the office, and that's good too! 😉 

I was kinda confused by the reproduction steps, since it does not reproduce in Wiki which is the App meant to use creole. Actually, looking at it closer, `attachmentPrefixUrl` is something that probably only Wiki injects, so this should be extracted to its own `ConfigContributor`, affecting only Wiki and not CKEditor as a whole. Null checks aside, you know I always like to fix the underlying issue 😉 

About the second one, we didn't push it before because @migue wanted to manually reproduce and verify it was causing an issue as well, but I'm fine with sending it over if he's okay with it.

**Comment by juangon** [comment]
Ok thanks very much @jbalsas.

I didn't make many checks in Liferay side, but I could reproduce the other error from a JSF portlet that was using this taglib. Maybe it can be reproduced in a bundle under some circumstances. In any case, this pull fixed that issue from JSF portlet so I thought it was the right fix.

Thanks!

**Comment by jbalsas** [comment]
@ambrinchaudhary, could you discuss this with @sergiogonzalez? If the attachment configuration part is only meant for wiki, we should extract that part.

@juangon, which portlet is using this in JSF? How is it handling the creole format?

**Comment by juangon** [comment]
@jbalsas it isn't a portlet, it is a JSF component (you can think it's like a taglib that can be used in a portlet).

Don't know what do you mean by "creole format". We are just instantiating the taglib class and set the tag attributes. This is working fine in previous Liferay versions.

**Comment by jbalsas** [comment]
Oh, ok, you said it was _a JSF portlet that was using this taglib_ on comment ago 😂 

If you use the `*_creole` variants as the editor, the resulting editors will work with Creole as input and will output Creole, not HTML. If you need to use it, you better have an engine when you need to render the contents in a page. This is what the Wiki App does.

The same way, the `_*bbcode` variants will work with BBCode format instead of HTML, so again, you need something in your app to turn it into html when you want to render it. This is what the MessageBoards App does.

**Pull request closed without merging**
