### PR TITLE
LPS-72976

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-72976.

I alphabetized the order of the plugins since this was going in portal and most things in portal are alphabetized.

Notes from @SpencerWoo:
We add ae_imagealignment to CKEditor via extraPlugins.

Changed order to match AlloyEditor
https://github.com/liferay/alloy-editor/blob/7687b612058c175c0113d049e64cfbb3790cfd0d/src/ui/react/src/adapter/alloy-editor.js#L319-L321

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by SpencerWoo** [comment]
Hi @jbalsas, any updates on this backport?

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49744. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
