### PR TITLE
LPS-101420 | Deprecate old modernized utilities and cleanup dependencies

### PR DESCRIPTION
**Pull request by markocikos**
Hi @jbalsas ,

Please review the code.

Thank you!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@jbalsas The failure unique to this pull is unrelated to changes in it.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78410. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
