### PR TITLE
LPS-78656 - Add portlet header separation

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by marcoscv-work** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56081. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/40d5e43f200c~1...40d5e43f200c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56082. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/8d1f14b136b3~1...8d1f14b136b3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
