### PR TITLE
LPS-108646 Remove global AUI AJAX configuration

### PR DESCRIPTION
**Pull request by markocikos**
Hey @jbalsas ,

I am sure this looks a bit scary :)

It has a limited scope though. There is only one usage in portal, with an integrated AUI component (`A.TreeView`). In it, in this PR, we are replacing global with local configuration, which seems a better practice in any case. The `uriFormatter` function that is defined in global config is not used anywhere.

I am not sure if there is a backwards-compatibility concern, since this seems like it was an internal mechanism. If it needs to stay, the alternative would be to move it to `frontend-js-aui-web`.

Please review the code.

Thank you!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by markocikos** [comment]
I force-pushed after rebase, no changes. Doing this to rerun CI test, as there were a lot of seemingly unrelated unique errors.

**Comment by markocikos** [comment]
ci:test

**Comment by jbalsas** [comment]
@wincent, I wouldn't mind if you could take a look at this too 😅

**Comment by wincent** [comment]
Will close this and proceed in https://github.com/wincent/liferay-portal/pull/140

**Comment by wincent** [comment]
ci:close

**Pull request closed without merging**
