### PR TITLE
LPS-75071

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @sergiogonzalez, @marianoalvarosaiz, I'm not sure this is the right fix.... I know we might have discussed it, but it feels all wrong :D 

Can you remind me again what was the exact problem?

Thanks!

**Comment by jbalsas** [comment]
Maybe we can use something like https://stereochro.me/ideas/detecting-broken-images-js to try to guess if images did load or not rather than blindly assuming they all did.

**Comment by marianoalvarosaiz** [comment]
All images load, the problem is that the background image (loading) appears as visible when the foreground image is transparent. We're only applying the class, but there's no logic removing the background image once the load gets done.

**Comment by jbalsas** [comment]
The problem with the fix is that it is simply removing the classes. It likely works in localhost because the images will load instantly and by the time the script gets executed the loading indicators are already hidden.

In a real connection, however, chances are we will be removing the classes before the images have finished loading.

**Comment by marianoalvarosaiz** [comment]
Yes, sounds right. Do you have another way in mind to fix it, so that the background image disappears after the proper one is loaded?
Thanks.

**Pull request closed without merging**
