### PR TITLE
LPS-104350 Defers react component initialization toon after SPA is ready to prevent Senna from moving away mounted components

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by john-co** [comment]
Test results look ok.
Pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal/pull/80773

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
