### PR TITLE
LPS-78047 Empty id attributes created in the DOM by taglib aui:icon

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi, @jbalsas. This fix is for a customer. I've taken the approach of not adding attributes whose value is the empty string. This is not strictly necessary for class but it is for id (see the LPS description). The other approach would be to generate a value for id if empty, but I'm not sure if that's preferable. Tell me if you have any questions. Thanks!

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55487. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @ricardocousolr, I was going to send this forward, but then I realized a couple of things:
- In `ui/IconTag`, we actually [generate a random id](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/IconTag.java#L243), so I think, for consistency, we should do so here as well.
- I think the pattern for definitions is to be as close to where they're used as possible, so you should move the `String cssClass` definition just above the `if (Validator.isNotNull(cssClass))` line.

Could you apply those changes and resend, please?

Thanks!

**Comment by ricardocousolr** [comment]
Thanks, @jbalsas. New pull request sent. https://github.com/jbalsas/liferay-portal/pull/1017

**Pull request closed without merging**
