### PR TITLE
[Lex][Mig][Dep] SocialActivities [!Leg]

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Chema,

I created the freemarker taglib contributer module and also removed all the `Import Package` and `Require Capability` changes from the bnds.

The `social-taglib-freemarker-contributor` bundle isn't starting for me.  I get this message when trying to start manually ```g! start 394
org.osgi.framework.BundleException: Invalid operation on a fragment.```, but I hope that is because of the necessary changes in the SDK that you mentioned. 

Please let me know if there are any other issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
arg, conflicts already. I'll rebase and force push

**Comment by mjbradford89** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey guys, I'm just updating the PRs title to reflect what's in there and why are they blocked

`[Lex][Mig][Dep] SocialActivities [!Leg]` means that this PR affects the taglib SocialActivities and

contains:
- Lexicon changes
- Migration changes
- Deprecation changes

is blocked by:
- Plugins legacy support

Thanks!

@mjbradford89, afaik, fragments do not start, they stay in the resolved state :wink:

**Comment by jonmak08** [comment]
Closing pull request.

**Pull request closed without merging**
