### PR TITLE
LPS-60665, LPS-61115

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-60665 and https://issues.liferay.com/browse/LPS-61115.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retet

**Comment by mjbradford89** [comment]
Hey @jbalsas, I saw this one is another instance where I forgot to migrate the corresponding JS component with this taglib.  I can make that change and resend if needed, just let me know.  Thanks!

**Comment by jbalsas** [comment]
Hey @jonmak08, @mjbradford89 sorry for the delay... a couple of comments for this one: 

- Aren't the `aui:*` taglibs and `liferay-aui.tld` autogenerated from `liferay-aui.xml`? Feels like we might be missing something. If we decide to convert it to a regular one, we should probably merge the base and the tag classes into one as the rest. @brunobasto, what do you think?
- Yes, please, do migrate the corresponding JS :)
- There are also lang keys that are unique to the translation manager talgib. Could you take care of extracting them as well?

Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/leoadb/liferay-portal/pull/160

**Pull request closed without merging**
