### PR TITLE
LPS-89271

### PR DESCRIPTION
**Pull request by samuelkong**
cc @arthurchan35

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
@jbalsas ,
It seems like new version of closure compiler does not like some of the generated js file, can you help with it?
junit.framework.AssertionFailedError: 
(null:-1): File cannot be a combination of goog.provide, goog.module, and/or ES6 module: /o/js/resolved-module/frontend-js-metal-web$metal-soy-bundle@2.16.7/lib/bundle.js [JSC_MODULE_CONFLICT]
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)

**Comment by jbalsas** [comment]
Hey @arthurchan35, this will be a complicated one to fix. I'm not sure we can easily change that source file without breaking a lot of stuff. That file is meant to be exactly what the compiler is complaining about and is the way we bridge the two worlds together :(

We should try to either ignore that error (which I assume will result in an unminified portion) or try to see if it can be disabled. Could you try to just add `JSC_MODULE_CONFLICT` to the list of [ignoredErrors](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-minifier/src/main/java/com/frontend/js/minifier/GoogleJavaScriptMinifier.java#L110-L115) and verify that the build completes and the resulting portal works as expected?

**Comment by arthurchan35** [comment]
HI @jbalsas 
Thanks for the input, I will have it tested on Monday!

**Comment by arthurchan35** [comment]
ci:close

**Pull request closed without merging**
