### PR TITLE
LPS-76780 Implement Portlet 3.0 Client API

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @julien, you need to update the `package-lock.json` file as well if you've changed dependencies ;)

**Comment by julien** [comment]
@jbalsas yes you're right. I'm surprised I didn't see the file marked as changed. 
I'll commit that

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/julien/liferay-portal/pull/23. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/6cc6f5669bf5~2...6cc6f5669bf5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
