### PR TITLE
[Mig][Dep] Flags [!Vel]

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-60967.

We cannot remove this taglib because it is used in ```VelocityTaglib.java```.  We need to see what we want to do with these taglibs.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @mjbradford89, I looked into this one, and it doesn't make sense to have it in `frontend-taglib`. I know it says so in the original plan, but the taglib itself depends on the `Flags` Portlet, so it makes much more sense to have it there and transfer it to @sergiogonzalez team.

Could you please:
- Move the taglib to `modules/apps/flags/flags-taglib`
- Create the `flags-taglib-freemarker-contributor` module
- Extract the lang keys that are unique to this taglib (I think there are a couple of them)
- Add the proper gradle compile dependencies in the modules that use the taglib

Thanks so much!

**Comment by mjbradford89** [comment]
Hey @jbalsas,  Thanks for your input on this.  I'm almost done with these changes and wanted to know if I should send this back to you or send it to @sergiogonzalez, since it is now part of `modules/apps/flags`.

**Comment by jbalsas** [comment]
Hey @mjbradford89, thank you for all your work on this!

Send it to me for a final review once you're done with it and I'll send it to Sergio.

Thanks!

**Comment by mjbradford89** [comment]
New pull here: https://github.com/jbalsas/liferay-portal/pull/354 :)

**Pull request closed without merging**
