### PR TITLE
LPS-75363

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-75363.

I sent this to you for review because you made the original change https://github.com/jonathanmccann/liferay-portal/commit/531f64099b20764dbfbae793ee3cb18219160543 along with @sergiogonzalez at https://github.com/jonathanmccann/liferay-portal/commit/2303300b1cb5862c23185808302fbcc22f66c629.

Can you please review to make sure this change is acceptable?

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
@jonathanmccann says:

> The issue here is that the input created when the subject or body is null or invalid XML does not have a sense of localization. Due to this, the input's name looks like:

> ```_com_liferay_portal_settings_web_portlet_PortalSettingsPortlet_settings--adminEmailPasswordSentBody--```

> When it should be:

> ```_com_liferay_portal_settings_web_portlet_PortalSettingsPortlet_settings--adminEmailPasswordSentBody_en_US--```

> Since the locale is missing, saving and fetching the record does not function properly.

**Comment by jbalsas** [comment]
Hey @jonathanmccann, @jonmak08, this doesn't feel right at all. Based on the information in the issue, logic points to a misuse in the taglib usage. 

The `email-notification` taglib supports templates for both localized and not-localized templates cases. If the taglib doesn't receive a localized-like input, then it won't produce a localized-like output. This is to be expected and it is the desired behaviour.

If for some reason we are sending in plain content and we are expecting it to be localized, we either need to adapt the input to get in in a localized manner or change the behaviour to handle the not-localized output accordingly.

Could you please take a second look based on this?

Thanks!

**Comment by jonathanmccann** [comment]
@jbalsas,

Thank you for taking a look at this fix and your response.

The issue isn't that we're sending in plain content and expecting it to be localized. What is happening is that in ```email_notifications.jsp``` we're calling this taglib:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-settings/portal-settings-web/src/main/resources/META-INF/resources/email_notifications.jsp#L112-L118

In the case of the steps on this LPS, since the template is invalid, we're sending across ```null``` for the ```emailBody``` since there is no preference stored in the database yet and the default value is taken from that property (ie ```null```):

https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-settings/portal-settings-web/src/main/resources/META-INF/resources/email_notifications.jsp#L113

In ```email_notification_settings/page.jsp```, we do a test on the ```emailBody``` to try and determine whether or not to render a localized editor:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/email_notification_settings/page.jsp#L58

Since we passed in ```null``` for the ```emailBody```, the taglib chooses to render the non-localized aware editor, which is incorrect.

Now, if you believe that instead of returning ```null``` when we try to fetch the ```emailBody``` we should return a valid, empty XML, that would be possible. However, the null check in ```email_notification_settings/page.jsp``` still doesn't make sense to me in this scenario. We should do a better job of checking whether or not the user of the taglib wants their input to be localized or not instead of simply testing for ```null```.

Please let me know your thoughts or if I misunderstood you.

**Comment by jbalsas** [comment]
Hey @jonathanmccann, yeah, I understand what you mean, but we usually overdesign and overcomplicate our APIs. 

In this case is quite simple. The `email_notification_settings` API takes a non-null XML to generate localized content or will default to non-localized. This was done to preserve the original behaviour and allows previous usages to work as expected. Removing the branching breaks the API and the tag.

On top of that, this eventually attacks an action, and the taglib doesn't know what it expects, so as we normally do, we default to the original behaviour if we don't know what to do. We could definitely do better by having a specific `localizedContent` flag. Why we didn't do it, I honestly don't remember 🤷‍♂️ 

In any case, I stand by `portal-settings-web` (and probably any other usage out there) being at fault here. Since we don't have a flag, you need to make sure `xml` is passed if you expect content in a localized way.

Let me know if there's anything else you think we could do.

**Comment by holatuwol** [comment]
@jbalsas, @jonathanmccann:

The following blog post which suggests that it is *not* the responsibility of the user of the taglib to ensure that it's XML:

https://web.liferay.com/web/jose.balsas/blog/-/blogs/new-feature-for-liferay-7-localize-email-notifications

It also notes that `liferay-ui:email-notification-settings` (which was then later changed to `liferay-frontend:email-notification-settings` prior to release) is new with DXP, which we can confirm by looking at liferay-ui.tld from 6.2.x:

https://github.com/liferay/liferay-portal/blob/6.2.x/util-taglib/src/META-INF/liferay-ui.tld

This says that there was never a time when the tag library expected non-localized content. The following are internal examples that emulate that blog post that do not provide additional logic to ensure that it's XML, and among them is `portal-settings-web`:

* modules/apps/foundation/login/login-web/src/main/resources/META-INF/resources/configuration.jsp
* modules/apps/foundation/portal-settings/portal-settings-web/src/main/resources/META-INF/resources/email_notifications.jsp
* modules/apps/invitation/invitation-web/src/main/java/com/liferay/invitation/web/internal/util/InvitationUtil.java
* modules/apps/web-experience/asset/asset-publisher-web/src/main/resources/META-INF/resources/email_subscription_settings.jspf

So, if we decide not to fix it in email notifications, the argument we will have to make is that either (a) the example is incorrect, or (b) `LocalizationUtil.getLocalizationXmlFromPreferences` must not return null.

We can change the way that the method works if we believe strongly that it's incorrect, but we have to take into account whether anyone using this API was *expecting* null as the return value for whenever the preference is missing, because that's how it's behaved for a very long time. Internally, we will call LocalizationUtil.getLocalizationXmlFromPreferences, but then pass a blank string to `liferay-ui:input-localized` rather than an empty XML.

* modules/apps/web-form/web-form-web/src/main/resources/META-INF/resources/configuration.jsp
* modules/apps/web-form/web-form-web/src/main/resources/META-INF/resources/edit_field.jsp

As far as I can see, because there is no legacy aspect to support, it should be very safe for us to make this change.

**Comment by jbalsas** [comment]
If this is meant to be backported, we can't change the tag API. If you just want to make this change for `7.1`, then we can definitely do the change and annotate the breaking change in case someone is expecting the old behaviour that was already shipped.

Thoughts, @sergiogonzalez?

**Comment by sergiogonzalez** [comment]
Hey guys,

Considering that this is a bug fix and that we would like to backport this to 7.0.x (correct me if I'm wrong) I think that it's better not to change any behaviour neither in `LocalizationUtil.getLocalizationXmlFromPreferences` nor `liferay-frontend:email-notification-settings` because, although it might not be an API breaking change, we are changing the behaviour and that has proved problematic other times that we did this kind of changes.

For this fix (and the backport) I would suggest documenting the current behaviour of the taglib in the line of what Chema commented above:  The `email_notification_settings` API takes a non-null XML to generate localized content or will default to non-localized. Then, the client of the taglib is responsible to ensure that the right parameters are passed to the taglib. This can mean that we need to change all the use cases of the taglib, but I'd rather do that and not change an API or the behaviour of an existing API.

I don't fully remember, but I think that the taglib attributes `emailBody` and `emailSubject` should be used for non localized email templates and the attributes of `emailBodyLocalizedValuesMap` and `emailSubjectLocalizedValuesMap` for localized ones.

**Pull request closed without merging**
