### PR TITLE
LPS-89557 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Hi @jbalsas, this pull includes fixes for our DM tests. Thanks!

cc @adolfopa

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @patriciajeanperez, this will fail many more tests from different teams. Please, go over them and sync with the different QAs before sending it back to me for final approval.

Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
running tests: https://github.com/patriciajeanperez/liferay-portal/pull/155

**Pull request closed without merging**
