### PR TITLE
LPS-86108 Remove metal-cli on dynamic-data-mapping-service

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test

**Comment by diegonvs** [comment]
ci:stop

**Comment by diegonvs** [comment]
ci:test

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66044. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
