### PR TITLE
LPS-107253

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co! Could you keep an eye on these tests and push to Brian if everything looks good?

Thanks!

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
the sf error looks related, rerunning ci tests
@zhangyan0701, could you check on the ci tests if we get results for those?

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Just start reviewing.

Somehow the test report cannot be generated. Will check this Jenkins report:
https://test-1-20.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8045/jenkins-report.html

**Comment by zhangyan0701** [comment]
Functional test failures are unrelated. 

Will take a look at the backend tests.

**Comment by zhangyan0701** [comment]
Two errors that may related:
1. SF failure:
`     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Variable '_destroyOnNavigate' is missing in method 'cleanUp': ./modules/apps/frontend-taglib/frontend-taglib/src/main/java/com/liferay/frontend/taglib/servlet/taglib/ComponentTag.java (SourceCheck:JavaCleanUpMethodVariablesCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)`

2. modules-semantic-versioning-jdk8 failure:
`     [exec] > Task :apps:frontend-taglib:frontend-taglib:baseline FAILED
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.frontend.taglib.servlet.taglib         MINOR      2.0.0      2.0.0      2.1.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.frontend.taglib.servlet.taglib.ComponentTag
     [exec] 		+   method     isDestroyOnNavigate()
     [exec] 			+   return     boolean
     [exec] 		+   method     setDestroyOnNavigate(boolean)
     [exec] 			+   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 5.1.0
     [exec] [Baseline Report] Mode: diff (persisted)`

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83635. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/af7111759022~2...af7111759022) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
