### PR TITLE
LPS-76140

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @crodriguezy, please run `gradlew baseline` to see what new version we need and resend. 

Thanks!

**Comment by crodriguezy** [comment]
ci:reopen

**Comment by crodriguezy** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53591. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/125d6fb2568e~1...125d6fb2568e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
