### PR TITLE
[Lex][Mig][Dep] ToggleTag [!Vel][!Leg]

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for https://issues.liferay.com/browse/LPS-60696 and http://issues.liferay.com/browse/LPS-60537 and https://issues.liferay.com/browse/LPS-60756.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey guys, this doesn't compile... the taglib is still used inside core in the `VelocityTaglibImpl`, so it might be the case we can't extract this one :cry: 

I'll investigate and let you guys know later

**Comment by jbalsas** [comment]
Hey guys, I'm just updating the PRs title to reflect what's in there and why are they blocked

`[Lex][Mig][Dep] ToggleTag [!Vel][!Leg]` means that this PR affects the taglib Toggle and

contains:
- Lexicon changes
- Migration changes
- Deprecation changes

is blocked by:
- Velocity support
- Plugins legacy support

Thanks!

**Comment by jonmak08** [comment]
Closing pull request

**Pull request closed without merging**
