### PR TITLE
LPS-105689 Stay on current URL upon checkout

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @stsquared99, I've made some changes, added some additions from @eduardoallegrini and sent this to @ealonso so we can work out the proper way to include menus in the control menu. 

We'll create a proper mechanism to simplify things.

I'll follow up with you as soon as we have something!

**Comment by stsquared99** [comment]
Great, thanks so much @jbalsas !

**Pull request closed without merging**
