### PR TITLE
LPS-67914

### PR DESCRIPTION
**Pull request by kenjiheigel**
@jbalsas, let's try this. I regenerated the shrinkwrap file again. It only uses the node-sass 3.10 version now

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @kenjiheigel, that's nice, for some reason the second `node-sass` dependency I got was 3.9.3. Still, we can't depend on this broken `node-sass` behaviour in the CI. It will fail anytime we update and a new `node-sass` version has been released, and then we'll be forced to update everything that depends on it.

Could you take a look to see if we can do it properly?

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@jbalsas, the first time this pull failed.. there was some network outage that was unrelated. The 2nd time it failed was cause of the ModulesStructureTest.testScanIgnoreFiles failure.. Once that test fails, I'll resend it to BChan.

But yeah, in regards to why regenerating kept giving you node-sass 3.9.3, I think it might have been because of the existing npm-shrinkwrap.json. If that's there, it affects what gets updated in the shrinkwrap. For some reason. This pull, I first deleted the npm-shrinkwrap then ran `npm shrinkwrap`

**Comment by kenjiheigel** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/43495

**Pull request closed without merging**
