### PR TITLE
LPS-89481 | Add utility that gets a form element, with intention to replace jQuery fm plugin

### PR DESCRIPTION
**Pull request by markocikos**
Hi Chema,

Please review the code.

Thank you!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @markocikos, can you show how this will be used in the context of what we're trying to replace so I can understand how the new API will be consumed?

Thanks!

**Comment by markocikos** [comment]
Hey @jbalsas,

I tested it on the ```deleteUsers``` function in user-admin-web, view.jsp.

Old code:
```
	function <portlet:namespace />deleteUsers(cmd) {
		if (...) {
			var form = AUI.$(document.<portlet:namespace />fm);

			form.attr('method', 'post');
			form.fm('<%= Constants.CMD %>').val(cmd);
			form.fm('redirect').val(form.fm('usersRedirect').val());
			form.fm('deleteUserIds').val(Liferay.Util.listCheckedExcept(form, '<portlet:namespace />allRowIds', '<portlet:namespace />rowIdsUser'));

			submitForm(form, '<portlet:actionURL name="/users_admin/edit_user" />');
		}
	}

```

New code:
```
	function <portlet:namespace />deleteUsers(cmd) {
		if (...) {
			var form = document.<portlet:namespace />fm;

			form.setAttribute('method', 'post');

			var Util = Liferay.Util;

			Util.getFormElement(form, '<%= Constants.CMD %>').value = cmd;
			Util.getFormElement(form, 'redirect').value = Util.getFormElement(form, 'usersRedirect').value;
			Util.getFormElement(form, 'deleteUserIds').value = Util.listCheckedExcept(form, '<portlet:namespace />allRowIds', '<portlet:namespace />rowIdsUser');

			submitForm(form, '<portlet:actionURL name="/users_admin/edit_user" />');
		}
	}
```

**Comment by jbalsas** [comment]
Thanks @markocikos!

If this is the regular usage... maybe we could do something like:

```
Liferay.Util.setFormValues = function() { ... };

function <portlet:namespace />deleteUsers(cmd) {
	if (...) {
		var form = document.<portlet:namespace />fm;

		form.setAttribute('method', 'post');

		Liferay.Util.setFormValues(
  		    form,
		    {
		        '<%= Constants.CMD %>': cmd,
		        'redirect': Liferay.Util.getFormElement(form, 'usersRedirect').value,
		        'deleteUserIds': Liferay.Util.listCheckedExcept(form, '<portlet:namespace />allRowIds', '<portlet:namespace />rowIdsUser')
		    }
		);

		submitForm(form, '<portlet:actionURL name="/users_admin/edit_user" />');
	}
}
```

**Comment by markocikos** [comment]
@jbalsas Yeah, that looks good!

Where to add these methods? They are closely related, so it would make sense to me to place them in the same file. Currently the pattern in ```frontend-js-web/.../liferay/util``` is to name the file the same as the method in it. Maybe we can have a ```form.es.js``` file, containing ```getFormElement```, ```setFormValues``` and even existing ```objectToFormData```. 

What do you think?

**Comment by jbalsas** [comment]
Hey @markocikos, one of the goals of having multiple files was so that it'd be easier to unit-test and to know what to import from where. we could have a `liferay/util/form` folder and then move all form related methods in there keeping the file separation for now... what do you think?

**Comment by markocikos** [comment]
@jbalsas Sounds good! Will you push the PR, or wait for me to send both methods?

**Comment by markocikos** [comment]
@jbalsas I force-pushed the changes, including the sample application

**Comment by jbalsas** [comment]
Hey @markocikos, this is starting to look very nice!!

I've seen that in combination with this, we almost always do:

```
var form = document.querySelector(...);

form.attr('method', 'post');
Liferay.Util.setValues(...);

submitForm(form, '...');
```

It'd be great if we could maybe do something like:

```
Liferay.Util.post(
    '#formId',
    'actionURL',
    { ... }
);
```

So, we could have the following:

```
// Old code
var form = AUI.$(document.<portlet:namespace />fm);

form.attr('method', 'post');
form.fm('deleteOrganizationIds').val(organizationIds);
form.fm('deleteUserIds').val(Liferay.Util.listCheckedExcept(form, '<portlet:namespace />allRowIds', '<portlet:namespace />rowIdsUser'));

if (organizationsRedirect) {
	form.fm('redirect').val(organizationsRedirect);
}

submitForm(form, '<portlet:actionURL name="/users_admin/delete_organizations_and_users" />');

// New Code
Liferay.Util.post(
    '#fm',
    '<portlet:actionURL name="/users_admin/delete_organizations_and_users" />'
    {
        'deleteOrganizationIds': organizationIds
        'deleteUserIds': Liferay.Util.listCheckedExcept(form, '<portlet:namespace />allRowIds', '<portlet:namespace />rowIdsUser'),
        'redirect': organizationsRedirect ? organizationsRedirect : ''
    }
);
```

What do you think?

**Comment by markocikos** [comment]
@jbalsas I am not sure. ```.post()``` may be misleading as this is only applicable to form submission. ```postForm()``` maybe? It sounds a bit odd. I was thinking maybe we could extend ```submitForm()```, but it doesn't have a config object argument so invocations would look ugly. Also, we would be extending AUI code unless we do massive refactor. ```Liferay.Util.submitForm()``` already exists in frontend-js-spa-web and has a lot of very spa-related logic. Would this maybe be too many similar utils?

**Comment by markocikos** [comment]
@jbalsas Please see [jQuery.post()](https://api.jquery.com/jquery.post) and [axios](https://www.npmjs.com/package/axios), they use ```.post()``` as s a convenience wrapper for ajax of the post variety. I think it is very intuitive, may not be a bad idea to have ```Liferay.Util.post()``` and ```this.post()``` in PortletBase with the same behavior.

As for this PR, I suggest keeping it as it is, unless we want to rename current spa-related ```Lifeay.Util.submitForm()```, replacing it with your last suggested code.

What do you think?

**Comment by jbalsas** [comment]
Hey @markocikos, thanks for the research! With that in mind, I'll say we should update this PR with something else... Brian has expressed in the past that he'd rather see a final pattern rather than small iterations if we have the clarity. 

Currently `Liferay.Util.submitForm` exists and is simply being overridden by the SPA one, so it's not as simple as renaming those... How do you feel about this?

```
Liferay.Util.postForm =(form, url, data) {
    // form -> (string) form selector
                      (DOMNode) form node
    // url ->     (string) action url
    // data ->  (object) addtitional payload data to set in the form

    return fetch(...);
}
```

We should make this change and try to apply it in more places to make sure we're not missing anything!

**Comment by markocikos** [comment]
@jbalsas ok, sounds good!

**Comment by markocikos** [comment]
@jbalsas There is a problem with the last solution. While it is good, it does not replace the existing code. The forms are currently being submitted with ```window.submitForm()```, which doesn't perform an ajax but validation and auth setup, ending with ```form.submit()``` action. See frontend-js-aui-web/.../util.js.

We can code:
```
Liferay.Util.? = (form, url, data) {
    // form -> (string) form selector
                      (DOMNode) form node
    // url ->     (string) action url
    // data ->  (object) addtitional payload data to set in the form

    submitForm(...);
}
```
Would is still be ok to call this ```postForm```? Is it even acceptable to have an AUI dependency in this module? Should we migrate all the code from util.js?

**Comment by jbalsas** [comment]
Hey @markocikos, this will depend on the case. We should continue calling `submitForm` as we're currently doing. Everything is set-up so depending on whether SPA is enabled or not the AJAX submission is used or the default form submission is used.

In both cases, this would be a `POST` request, regardless of whether we use ajax or not, so I think the `postForm` is still valid.

**Comment by markocikos** [comment]
@jbalsas I see. But if we continue calling ```submitForm()``` as we're currently doing, this structure would not be used anywhere in the existing code:
```
Liferay.Util.postForm =(form, url, data) {
    ...
    return fetch(...);
}
```
Also, it would be quite complex to implement, as we would need to migrate all the validation, auth setup etc. that is now a part of ```submitForm()```.

**Comment by markocikos** [comment]
@jbalsas I force-pushed the changes.

**Comment by jbalsas** [comment]
Looks good to me @markocikos!! 

Could you please apply this as a sample to 3-4 other places to verify? With that we might be able to ask Brian to get someone to do the whole replacement for us...

**Comment by markocikos** [comment]
@jbalsas The three us working on jQuery removal are eager to start making replacements, as ```.fm()``` appears in almost all remaining user modules :)

**Comment by markocikos** [comment]
@jbalsas What I mean is, I can make the replacement in all modules, but it will take me couple of days. I wouldn't like all of us to blocked while waiting for somebody else to finish these replacements. If you don't mind, please forward the PR, so we are unblocked and can proceed with per-module PRs.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67436. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/4fa01560f861~1...4fa01560f861) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67438. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/0c96f5bcb201~1...0c96f5bcb201) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
