### PR TITLE
LPS-75071 Remove background image, when original image loaded, to avoid it appearing over image with transparent background.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
added extra check, just in case there's is no image at all.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53840. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
