### PR TITLE
LPS-73579 Wiki Tree Menu is collapsing on page refresh

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
Hello @jbalsas 

I was wondering if you could find time to take a look at the pull request.
As I see, the failed tests are not releated to the solution.

Thank you and best regards,
István

**Comment by jbalsas** [comment]
Hey @IstvanD, I wanted to take a look yesterday but I ran out of time. My first thought was, can't we do this when rendering the markup? so we avoid the js flickering after the initial render?

**Comment by IstvanD** [comment]
Hey @jbalsas 

I haven't thought of it, as I used logic that was implemented in _modules/apps/web-experience/asset/asset-taglib/src/main/resources/META-INF/resources/asset_categories_navigation/page.jsp_

That being said, I haven't experienced flickering when I tested the solution.

**Comment by jbalsas** [comment]
Hey @IstvanD, looks, good, the only difference I see is they use `.tree-node .tag-selected` to get the selected node and here you're using the `strong` tag. 

Could we use the same selector? That's more reliable and semantic than using `strong`.

What do you think?

**Comment by IstvanD** [comment]
Hey @jbalsas 

I'm using the `strong` tag because in the Tree Menu portlet, that is the only indicator that a node has been selected.

_modules/apps/collaboration/wiki/wiki-navigation-web/src/main/resources/META-INF/resources/tree_menu/view.jsp_

```
if (label.equals(curTitle)) {
	sb.append("<strong>");
	sb.append(label);
	sb.append("</strong>");
}
else {
```

**Comment by jbalsas** [comment]
I see. Can you add a class there, then? Maybe `item-selected` or `page-selected` based on whatever we're actually showing and use that instead of the tag? That should make the API contract more obvious.

If you can do that little change and push on this branch I'll send it forward.

Thanks!

**Comment by IstvanD** [comment]
Hey @jbalsas 

I sent you the pull request
https://github.com/jbalsas/liferay-portal/pull/1043

**Pull request closed without merging**
