### PR TITLE
LPS-79585 Change alignment constants to prevent overflow for tablet simulation

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
@jbalsas Could you please take a look? The main problem here is that we user a modal(opened with Liferay.Util.openWindow) for the simulation panel and in new Clay CSS "modal-dialog" has fixed max-width which doesn't allow us to resize the simulation as before.
If this solution is OK for you - please merge and if not it would be great to see some proposal on how to fix it better without creating a sim. panel from scratch ;) Thanks!

cc @ealonso

**Comment by jbalsas** [comment]
@pavel-savinov, yo creo que esto no está bien... el diálogo se sale de la zona visible con este cambio:

screen shot 2018-04-17 at 12 03 22

**Comment by pavel-savinov** [comment]
@jbalsas Con este cambio funciona bien, se muestra justamente lo que debería. Y sin cambio - está super-feo. Creo que es por algún cambio en CSS de modal. Puedes echar un ojo y proponer alguna otra solución?

**Comment by jbalsas** [comment]
Resent -> https://github.com/pavel-savinov/liferay-portal/pull/162

**Pull request closed without merging**
