### PR TITLE
[TECHNICAL SUPPORT] LPS-78861 Message boards: link containing an Ö character is lost after opening the message for editing

### PR DESCRIPTION
**Pull request by NemethNorbert**
[LPS-78861](https://issues.liferay.com/browse/LPS-78861)
[LPP-29313](https://issues.liferay.com/browse/LPP-29313)

Please review the PR.

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
Hey @jbalsas ,

Could you give un update on the PR?

Thanks

**Comment by jbalsas** [comment]
Hey @adolfopa, @sergiogonzalez, can you take a look at this? I assume there was a reason why the regex was filtering additional characters. If you're fine with it, I can just send it forward.

**Comment by sergiogonzalez** [comment]
Hey @jbalsas I can't think of any reason why we decided to restrict those characters, but I'm not a bbcode expert.
Nevertheless I thought that we had a BBCode parser in java as well. Shouldn't it also be updated?

@adolfopa any idea about this?

**Comment by jbalsas** [comment]
I think this is probably there because [URL RFC](http://www.faqs.org/rfcs/rfc1738.html) doesn't really allow unicode characters.

> Thus, only alphanumerics, the special characters "$-_.+!*'(),", and
   reserved characters used for their reserved purposes may be used
   unencoded within a URL.

We should encode the url first if we want to be compliant (unless the RFC has changed since)

**Comment by NemethNorbert** [comment]
Hey @jbalsas ,

I checked the fix again on 6.2 sp20, as I had to create an SDH for a customer and I found an error thrown from backend. I`ll have to investigate a bit more with this issue and probably update the BBcode parser on the Java side as well, like @sergiogonzalez pointed out.
Please close this PR, I`ll send an updated one when I`ll have a more robust solution.

Thanks,

**Comment by jbalsas** [comment]
Thanks for looking into it, @NemethNorbert!

**Pull request closed without merging**
