### PR TITLE
LPS-114042 Fix compilation problem: declare variable before so it can be used later in both <clay:content-col> sections

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
from @marcoscv-work: 
>As part of our effort to Improve HTML Layout Generation Strategies in DXP, here a PR about changing autofit-* and sheet-* for clay:sheet* and clay:content*
This "PR" updates markup with new taglibs. What we expect is to see the same visual design, so no visual changes are required.
The way to validate the changes is to see the same visual result. if is there any previously agreed difference it would be correctly pointed in comments
The markup output, in this case, is a little bit different but the behavior should be the same (float behavior in autofit).
LPS-114042
Use new Layout Tags in JSPs in message-boards

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
I've reviewed message board's UI and everything lookf fine.

**Comment by jbalsas** [comment]
Bundled together at https://github.com/jbalsas/liferay-portal/pull/2189

**Pull request closed without merging**
