### PR TITLE
LPS-73514 auto fields custom message is not replicated when adding fields

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Chema,

I got an LPP on my last some days on support, this LPS is related for that.
I just copied the code for "rules".

Could you review it or direct me to the owner of "auto_fields.js"?

Thank you in advance
Péter

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @peterborkuti, I'm not convinced this is fixing the issue... or at least I'm not sure what it is supposed to fix.

This is what I'm seeing after the fix:

screen shot 2017-07-13 at 09 56 28

Can you explain in some more detail?

**Comment by jbalsas** [comment]
I guess it is just that the message is the same but it is not handling the issue that it is duplicated?

**Comment by peterborkuti** [comment]
Yes, your right. And it does not fix that the validation is the opposite, IMHO.

But yesterday I did not notice the duplicated messages.

I need more time to debug that cases and those bugs are not in the customer's branch.

If you want me to work on those also (I'd like to), I need more time and I need to prioritize the other two staging issues (modularization of "liferay-export-import" and name-fixing).

**Comment by jbalsas** [comment]
It's okay, I'll fix the remaining issues and send it forward.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50276. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/43a41502~1...43a41502) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
