### PR TITLE
LPS-79316

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-79316.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brianikim, @jonmak08, I don't think this is the right fix, and I wonder why it actually works at all. This certainly points to a deeper problem somewhere in [LanguageImpl](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L1533-L1537) when translating the language keys. 

Checking the output of `alloy-editor-extras.js`, other keys like `'sorry\x2c-this-platform-is-not-supported'` are also untranslated, so we should figure out why is this happening. Could you please take a look?

**Comment by jbalsas** [comment]
Adding more information to this, we've seen that the existence of `minifierType` in the URL is the cause of the different behaviours, because it sends the contents of the file through a different filter chain where the module language keys can't be resolved.

```
// Works
http://localhost:8080/o/frontend-editor-alloyeditor-web/alloyeditor/alloy-editor-extras.js?browserId=other&languageId=en_US&b=7100&t=1523272000646

// Doesn't work
http://localhost:8080/o/frontend-editor-alloyeditor-web/alloyeditor/alloy-editor-extras.js?browserId=other&languageId=en_US&b=7100&t=1523272000646&minifierType=js
```

In the second case, the file will fail to go through [LanguageFilter](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-language/portal-language-servlet-filter/src/main/java/com/liferay/portal/language/servlet/filter/internal/LanguageFilter.java) which is the only one that has knowledge of the bundle resourceLoader.

@csierra... any chance you could give us a hand here? 🙏

**Comment by csierra** [comment]
so the problem seems to be that `AggregateFilter` in portal-impl kicks in when `minifierType` is present. 
This filter is getting the content of the file using the bundle url entry directly (`bundleentry://blabla`) so no further request processing is done after that, so the LanguageFilter associated to the module's servlet context is not reached. 
Then the LanguageFilter at the portal level only knows about portal resourcebundles, so it only would translate keys present in the portal.

**Comment by jbalsas** [comment]
Hey @shuyangzhou, could you guys help us out figuring this out? Shouldn't we be forwarding http-like so we can honour the proper filter chain?

**Pull request closed without merging**
