### PR TITLE
LPS-76952

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-76952.  I don't love the idea that we are mixing jQuery/clay components with AUI, but I do not know of another way around this since we are trying to fire a jQuery event from the JS file.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @jbalsas @jonmak08 
Do we have any screenshots so we can better see what we are talking about? 😄 
Thanks!

**Comment by jbalsas** [comment]
**Current behaviour:**
screen shot 2018-01-18 at 17 24 51

**After proposed fix:**
localhost_8080_web_guest_home_-_document_library_nbdy4dlwivl2_view_file_37802__com_liferay_document_library_web_portlet_dlportlet_instance_nbdy4dlwivl2_redirect http 3a 2f 2flocalhost 3a8080 2fweb 2fguest 2fhome 3fp_p_id 3dcom_liferay_docum

**Comment by pat270** [comment]
https://github.com/pat270/lexicon/pull/95#issuecomment-356394091

**Comment by jbalsas** [comment]
@sergiogonzalez, didn't we go over a similar case with @ambrinchaudhary a while ago?

**Comment by sergiogonzalez** [comment]
@jbalsas not that I recall...

**Comment by ambrinchaudhary** [comment]
@sergiogonzalez @jbalsas yes, there is a similar issue here: https://issues.liferay.com/browse/LPS-70562

**Comment by jbalsas** [comment]
we'll take a look to see what we need to do to fix this one.

**Comment by AngeloJ** [comment]
@jbalsas, when you get a chance, can you provide us with an update.

**Comment by jbalsas** [comment]
We'll be looking into this tomorrow or some time next week. @pat270 will try to figure out what css we need to apply to keep the sidebar from growing outside the container.

**Pull request closed without merging**
