### PR TITLE
LPS-78777 - Move hiding of .sortable-layout-drag-indicator background-color to admin theme

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by jbalsas** [comment]
Hey @jonmak08. We certainly don't need the drag indicator in the admin theme, but the admin theme itself shouldn't be concerned about this at all.

If the form-builder css wasn't being loaded, this wouldn't even be an issue. Rather than touching the admin theme, I think we should:
1. Scope the css in form-builder better so it only applies inside their portlet, and not globally.
2. Prevent the form-builder and form-renderer css from being loaded when the portlets aren't actually in the page. Not sure why this is happening at all.

Who do you think could take care of this?

Thanks!

**Comment by jbalsas** [comment]
I would assume form-builder is trying to hide the drag indicator inside their portlet. For that reason, I'd expect it to be inside their own `.portlet-content` or similar, so it should definitely be scoped to that only.

@pedroqueiroz, @leoadb, @clovisdasilvaneto, could you shed some light into this? Could we revert the original change and figure out a safer way to apply it?

**Comment by pedroqueiroz** [comment]
Hey guys,

I asked the team and the styles for `dynamic-data-mapping-form-builder` and `dynamic-data-mapping-form-renderer` are being loaded in every page due to our dynamic include in `top_head.jsp`.

We use that because Forms won't know where a Form Builder or a Rendered Form can be used across the portal.

@jbalsas @jonmak08  , do you know how can we solve this?

@clovisdasilvaneto , do you think we can revert the original change?

Thanks!

**Comment by jonmak08** [comment]
Hey @pedroqueiroz,

I spoke to @clovisdasilvaneto about reverting this change in the original pull request at https://github.com/clovisdasilvaneto/liferay-portal/pull/40, which is why we came up with the current solution based on our discussion.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Thanks @clovisdasilvaneto!  I will close this pull request now.

**Comment by jbalsas** [comment]
Thanks guys!

**Pull request closed without merging**
