### PR TITLE
LPS-76458 - Navbar background

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by marcoscv-work** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/916. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/2c8859c4ee0a~2...2c8859c4ee0a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
