### PR TITLE
LPS-61891 - Product menu margin corrections

### PR DESCRIPTION
**Pull request by marcoscv-work**
image

cc /@juliocamarero

### CODE REVIEW

**Comment by juliocamarero** [comment]
:+1:

**Comment by juliocamarero** [comment]
cc @carloslancha

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34189. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/210f413~1...210f413) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
