### PR TITLE
LPS-74402 Adds SPA navigation performance test

### PR DESCRIPTION
**Pull request by brunobasto**
To run:
`ant -f build-test.xml run-selenium-test -Dtest.class=SPA#AssertPerformance`

** You'll need Firefox 45

### CODE REVIEW

**Comment by brunobasto** [comment]
@xbrianlee, can you help figure out these failures?

Do you know why I got
```
javax.portlet.PortletException: com.liferay.portal.kernel.security.auth.PrincipalException$MustBeCompanyAdmin: User 36772 must be the company administrator to perform the action
```
when trying to get into the `App Manager` portlet if the user was logged in as `test@liferay.com`?

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
exec]     Regular navigation took, on average, 621ms to complete.
     [exec]     SPA navigation took, on average, 520ms to complete.
     [exec]     SPA navigation was faster than regular navigation.

On my local machine difference was greater. Also, will simulate more realistic connections to emulate production environments.

**Comment by jbalsas** [comment]
Awesome!!! 🎉 🎉 🎉 🎉 

We need to gather some more data and tabulate it properly to make sure it is well understood! :)

**Comment by xbrianlee** [comment]
@brunobasto That exception looks like a fluke. It shouldn't show up when using `test@liferay.com`. I checked our recent App Manager test runs and the same exception didn't show up.

Btw will this test eventually get merged? This is very valuable information 😄

**Comment by jbalsas** [comment]
Hey @xbrianlee, I think this make more sense as performance regression tests. They are definitely very valuable, that's why we're investing in them but I'm just not sure if we should merge this in to be run in every PR. Maybe we can find some other place to put them?

@brunobasto, I'm closing it for now to keep track of my missing work, but reopen it if needed 😉

**Comment by brunobasto** [comment]
@jbalsas, sure!

@xbrianlee, we can add this one (or a similar one) as a nightly build test or some kind of test that run less often. Do we have anything like that?

**Comment by xbrianlee** [comment]
@brunobasto Let's add this test to the upstream jobs - `<property name="portal.upstream" value="true" />`. We analyze these jobs weekly for regressions.

**Pull request closed without merging**
