### PR TITLE
LPS-78475

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @Ithildir, this would be a breaking change. Could you add an entry to the `BREAKING_CHANGES.md` file with it?

I also assume this is not meant to be backported, right?

**Comment by Ithildir** [comment]
Hi @jbalsas,
I only noticed the problem while working on Commerce with `master` and fixed it! I'm not sure if it should be backported 🤔

**Comment by Ithildir** [comment]
Hi @jbalsas,
I just pushed the breaking change, hope it's okay 😊

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55892. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/6d5d6cf4463f~1...6d5d6cf4463f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Looks, good, @Ithildir, thanks for sending it over!

Can you double check this last commit I added? https://github.com/brianchandotcom/liferay-portal/pull/55892/commits/6d5d6cf4463f32229d5fd8daa19be36294c50760

Thanks! ☺️

**Comment by Ithildir** [comment]
You're right @jbalsas, thanks for catching it!!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55896. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/df646b74af49~1...df646b74af49) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
