### PR TITLE
LPS-67718

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-67718.  I sent this to you since I saw you did some work on the tree before.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey @jbalsas,
Could you please help to review this pull request as high priority as we have a ee customer is waiting for this fix

Thanks,
Dale

**Comment by jonmak08** [comment]
Sent to @brianchandotcom for review at https://github.com/brianchandotcom/liferay-portal/pull/43121.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/juliocamarero/liferay-portal/pull/4263

**Pull request closed without merging**
