### PR TITLE
LPS-99925 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-99925

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, I'm not sure I understand the goal of this PR... if we want to enable code-coverage for js-unit tests, we should do so globally from [liferay-npm-tools](https://github.com/liferay/liferay-npm-tools). 

This would only show locally for a developer running the tests, though, so it is of little use. How are we planning to integrate this with CI so we can gather metrics?

**Comment by john-co** [comment]
Hi @jbalsas, I was assuming developers were running the tests locally and thought it would be helpful to see the coverage report immediately after running the test.

I can follow up on integrating this on CI so it can be reported on jenkins. Is this something the team would like to prioritize? There's some stuff on jenkins side that's needed, I can request CII team for help in implementing.

I was scoping down the code coverage to our frontend infra owned tests, but I can investigate a way to enable code coverage from liferay-npm-tools if we want this to be included by all js-tests that use liferay-npm-scripts.

**Comment by jbalsas** [comment]
Hey @john-co, I've created https://github.com/liferay/liferay-npm-tools/issues/205 to track this down and implement it over there.

I don't think this is a priority for us, just a general desire for the future.

**Comment by wincent** [comment]
Whoops, I also created one 😂: https://github.com/liferay/liferay-npm-tools/issues/206

**Pull request closed without merging**
