### PR TITLE
LPS-114045 Replace layout classes with new clay taglibs in portal-search-admin-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple code replacement, we don't expect to see any difference between the old code `<div class="sheet sheet-lg">` and the new one `<clay:sheet>`.

https://github.com/liferay/clay/blob/6244ab8aa35059cc681ead2c1530e6fe320eed2d/packages/clay-layout/src/Sheet.tsx#L81
https://github.com/liferay/clay/blob/6244ab8aa35059cc681ead2c1530e6fe320eed2d/packages/clay-layout/src/Content.tsx#L34

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:stable

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Bundled together at https://github.com/jbalsas/liferay-portal/pull/2189

**Pull request closed without merging**
