### PR TITLE
LPS-107226 Update Clay v2 packages to 2.20.0 and Clay v3

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
@jbalsas updated

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/2099. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f8f22484e14a~1...f8f22484e14a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
