### PR TITLE
LPS-114143 Update modal usages in document library

### PR DESCRIPTION
**Pull request by markocikos**
Hey @jbalsas 

Task history:
- wincent#295
- wincent#303
- wincent#304
- #2178
- markocikos#188
- #2195
- https://github.com/jbalsas/liferay-portal/pull/2196

Changes from https://github.com/jbalsas/liferay-portal/pull/2196
- Minor SF 

@wincent @austinchiang

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:documents

**Comment by wincent** [comment]
> Task history:
> 
> * [wincent#295](https://github.com/wincent/liferay-portal/pull/295)
> * [wincent#303](https://github.com/wincent/liferay-portal/pull/303)
> * [wincent#304](https://github.com/wincent/liferay-portal/pull/304)
> * #2178
> * [markocikos#188](https://github.com/markocikos/liferay-portal/pull/188)
> * #2195
> * #2196

task-history

**Comment by markocikos** [comment]
The [failing test](https://testray.liferay.com/reports/production/logs/test-1-6/1591090380127/test-portal-acceptance-pullrequest(master)/6357/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.CPDocumentsandmedia_MoveToRecycleBinDocument/summary.html.gz) looks unrelated to this PR.

**Comment by wincent** [comment]
> The [failing test](https://testray.liferay.com/reports/production/logs/test-1-6/1591090380127/test-portal-acceptance-pullrequest(master)/6357/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.CPDocumentsandmedia_MoveToRecycleBinDocument/summary.html.gz) looks unrelated to this PR.

Given that @jbalsas approved [over here](https://github.com/jbalsas/liferay-portal/pull/2196#issuecomment-637399891), I think you can forward this.

**Comment by markocikos** [comment]
We may want to forward this to @liferay-echo, as there are appearance changes on 'select folder' modals.

**Comment by wincent** [comment]
If you'd like to wait for them you can, but this one has been stuck for so long that personally I would get it shipped with the obvious offer to follow-up if there are any regressions or problems with the appearance.

**Comment by markocikos** [comment]
Up to @jbalsas I guess. I wouldn't mind pushing it :)

**Comment by jbalsas** [comment]
Push it!

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
