### PR TITLE
[TECHNICAL-SUPPORT] LPS-90239 AlloyEditor source button fails on Firefox and safari for Mac OS

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @jbalsas , @antonio-ortega
I updated the solution, could you review it please?

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @NemethNorbert, yes, we will take a look asap!

Could you please send this to @julien instead? He's the one taking point on all AlloyEditor development.

Thanks!

**Comment by NemethNorbert** [comment]
https://github.com/julien/liferay-portal/pull/96

**Pull request closed without merging**
