### PR TITLE
LPS-81044 Override color of workflow taglib in info bar

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by jpince** [comment]
@jbalsas thanks for the retest. All errors look unrelated.

cc/ @austinchiang fyi. reference: https://issues.liferay.com/browse/LPS-81044

**Comment by jpince** [comment]
@michaelhashimoto @kenjiheigel @yichenroy CDN issue showed up in plugins-compile https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/235587//consoleText

**Comment by pyoo47** [comment]
@jpince I"ve reached out to Sam again to get him to upload org.apache.ivy-2.4.0.LIFERAY-PATCHED-1-SNAPSHOT.jar to mirrors. This ought to at least remove this issue for CI.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59345. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
