### PR TITLE
LPS-60552

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-60552.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Same as in https://github.com/jbalsas/liferay-portal/pull/283#issuecomment-160949526

`liferay-ui:icon` does not have lexicon view. Is the produced markup equivalent?

**Comment by jonmak08** [comment]
Hey @jbalsas,

I just updated the taglib usage to use ```<aui:icon markupView="lexicon" />```.  The only thing missing for this ```<aui:icon />``` taglib is the hidden help message for screen readers.  Lexicon does not have the hidden message on their form labels, so that might be something to talk to Juan and Marcos about.

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
- Add lexicon folder to the taglib and move the lexicon changes to the lexicon folder

**Comment by jonmak08** [comment]
Hey @jbalsas,

I have added the ```markupView="lexicon"``` to the ```<aui:select />``` taglib as requested with the commit https://github.com/jonmak08/liferay-portal/commit/a0c5b5c7a9edf057842af9e93facc07fe378b894.

Please let me know if you have any questions. Thanks!

**Comment by mjbradford89** [comment]
Hey @jbalsas @jonmak08 
I sent a couple new pulls (https://github.com/jbalsas/liferay-portal/pull/317, https://github.com/jbalsas/liferay-plugins/pull/4) for this issue.  Thanks!

**Pull request closed without merging**
