### PR TITLE
LPS-63117

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-63117.

I think we should confirm this change with @juliocamarero and @sergiogonzalez just in case.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
:+1:  looks good to me!

**Comment by sergiogonzalez** [comment]
:+1: However there are some poshi tests failing in Documents and Media so we should send it to @sharonchoi before this can be merged. Thx guys!

**Comment by jbalsas** [comment]
Forwarding to Sharon...

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/sharonchoi/liferay-portal/pull/455. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
