### PR TITLE
LPS-78949

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-78949.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey guys, thanks for sending this over, and apologies for the delay! 😢 

I haven't had a chance to try this out just yet, but I had a question about it nonetheless. As far as I can tell, we're just updating one of the 3 possible views of the search container, don't we? Don't the other views suffer a similar accessibility issue? Even if they don't (because they don't use a specific `<table>` tag), we should at least keep them consistent by providing the summary in an `aria-*` way.

What do you think? Does this make sense?

Thanks!

/cc @antonio-ortega

**Comment by jonmak08** [comment]
@jonathanmccann @SpencerWoo,

Thoughts on what @jbalsas mentioned?

**Comment by SpencerWoo** [comment]
Hi @jonmak08, @jbalsas is correct -- there are other views that should have also have the summary tag.

**Comment by jbalsas** [comment]
@SpencerWoo, could you take care of this and resend? Also, is this meant to be backported? I'm not sure if we're even taking minor kernel changes...

Please, let me know if there's anything I can do to help.

Thanks!

**Comment by jonmak08** [comment]
Hey @SpencerWoo,

You can use the ```<caption />```` attribute for the ```<table />````.

**Pull request closed without merging**
