### PR TITLE
LPS-102379 When Italian is set as display language, the Export User functionality will not work

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @jbalsas,

could you plesae check my changes?

Thanks, Roland

https://issues.liferay.com/browse/LPS-102379

Prev PR: https://github.com/dsanz/liferay-portal/pull/73

cc: @dsanz, @antonio-ortega

### CODE REVIEW

**Comment by rolandpakai** [comment]
Hi @jbalsas 

coud you please check it and push it to master?

Thanks, Roland

**Comment by jbalsas** [comment]
Hey @rolandpakai, I want to take a look at this with @antonio-ortega. I hope to be able to send it tomorrow.

Thanks for your patience!

**Comment by rolandpakai** [comment]
Hi @jbalsas ,  @antonio-ortega

i am wondering you where able to check this? 

Thanks, Roland

**Comment by jbalsas** [comment]
Hey @rolandpakai, thanks for your patience here. We finally managed to look at this and I think for some reason we were looking at the wrong place all along.

Based on our initial conversations with @dsanz, the assessment that this applied to many cases threw me off and still didn't exactly made sense, which is why I wanted to be able to look at it more carefully.

Currently, we're already escaping `liferay-ui:message` based on context. See how [the value of unicode is retrieved from the request](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/MessageTag.java#L52-L53). A [JS context is set when using `aui:script](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/aui/ScriptTag.java#L208-L209). 

In the case of this issue, because we're using a `liferay-util:buffer`, we fail to do this by default.

As it is, I'd agree that the easies fix would be to simply add the `unicode` attribute in here and that should actually cover it.

@dsanz, could you re-check our initial assumptions to see if this makes sense or if we're still missing many cases?

@antonio-ortega will be sending a PR today with the final fix.

Thanks!

**Comment by rolandpakai** [comment]
Thank you @jbalsas 

I am looking for @antonio-ortega  PR.

Thanks, Roland

**Comment by dsanz** [comment]
Hi @jbalsas:

> Currently, we're already escaping liferay-ui:message based on context. See how the value of unicode is retrieved from the request. A JS context is set when using `aui:script.
> In the case of this issue, because we're using a liferay-util:buffer, we fail to do this by default.
> As it is, I'd agree that the easies fix would be to simply add the unicode attribute in here and that should actually cover it.

Your findings are the same as mine (https://github.com/dsanz/liferay-portal/pull/73#issuecomment-537841585). 

The fix Roland sent is fine to keep customer "happy". As you said, we need to check some cases to ensure we fix this completely. Fortunately, <aui:script> takes care so the number of cases greatly reduces. These are the ones I think we must check:
- occurrences of `<liferay-ui:message>` in a JS context, but outside `<aui:script>`. I used IntelliJ regex search to find them in regular `<script>`s and when buffering output, as follows:
  - `<script[^>]*>[\s\S]*?liferay-ui:message[\s\S]*?</script>` and found 14 matches (7.2.x), which gives an idea of the size we're interested in
  - `<liferay-util:buffer[^>]*>[\s\S]+?liferay-ui:message[\s\S]+?</liferay-util:buffer>` found 28 matches, some of them pretty similar to the one fixed by Roland as they generate Js snippet. Others are false positives as they generate just HTML
- occurrences of Liferay.Language.get may be checked too, although I'm not sure about these ones being problematic

I am not 100% sure this covers all cases where we generate JS code and make use of translations at the same time, but I can not think of more for now
cc/ @antonio-ortega
Best

**Comment by antonio-ortega** [comment]
brianchandotcom#79613

**Pull request closed without merging**
