### PR TITLE
LPS-103009 Update liferay-npm-scripts to v11.0.0

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Looks like a couple modals are not editable in:

Calendar add event:
image

Asset publisher configuration not edittable:
image


I'll verify manually.

Flaky test:
DMAutoTagging#Smoke - test results show flaky behavior since yesterday afternoon

I'll check backend in a bit

**Comment by john-co** [comment]
Verified form fields are grayed out and not editable.

Asset Publisher js errors:
Selection_003
Selection_004

Calendar has similar errors:

image
image

**Comment by john-co** [comment]
js-unit-jdk8 errors looks related:
```
     [exec] FAIL test/js/components/list-view/ListView.es.js
     [exec]   ??? Console
     [exec] 
     [exec]     console.error ../../../node_modules/react/cjs/react.development.js:172
     [exec]       Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
     [exec]       
     [exec]       Check the render method of `TableWithPagination`.
     [exec]           in TableWithPagination (created by Wrapper)
     [exec]           in Wrapper (created by Wrapper)
     [exec]           in Wrapper (created by _default)
     [exec]           in _default
     [exec]     console.error ../../../node_modules/jsdom/lib/jsdom/virtual-console.js:29
     [exec]       Error: Uncaught [Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
     [exec]       
     [exec]       Check the render method of `TableWithPagination`.]
     [exec]           at reportException (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
     [exec]           at invokeEventListeners (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
     [exec]           at HTMLUnknownElementImpl._dispatch (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
     [exec]           at HTMLUnknownElementImpl.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
     [exec]           at HTMLUnknownElementImpl.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
     [exec]           at HTMLUnknownElement.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
     [exec]           at Object.invokeGuardedCallbackDev (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:397:16)
     [exec]           at invokeGuardedCallback (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:454:31)
     [exec]           at beginWork$$1 (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
     [exec]           at performUnitOfWork (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:22211:12) { Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
     [exec]       
     [exec]       Check the render method of `TableWithPagination`.
     [exec]           at /opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:24036:34
     [exec]           at createFiberFromTypeAndProps (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:24039:13)
     [exec]           at createFiberFromElement (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:24060:15)
     [exec]           at reconcileSingleElement (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:14530:23)
     [exec]           at reconcileChildFibers (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:14587:35)
     [exec]           at reconcileChildren (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:16691:28)
     [exec]           at updateHostComponent (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:17170:3)
     [exec]           at beginWork$1 (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:18510:14)
     [exec]           at HTMLUnknownElement.callCallback (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:347:14)
     [exec]           at invokeEventListeners (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
     [exec]           at HTMLUnknownElementImpl._dispatch (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
     [exec]           at HTMLUnknownElementImpl.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
     [exec]           at HTMLUnknownElementImpl.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
     [exec]           at HTMLUnknownElement.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
     [exec]           at Object.invokeGuardedCallbackDev (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:397:16)
     [exec]           at invokeGuardedCallback (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:454:31)
     [exec]           at beginWork$$1 (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:23217:7)
     [exec]           at performUnitOfWork (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:22211:12)
     [exec]           at workLoopSync (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:22185:22)
     [exec]           at renderRoot (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:21878:11)
     [exec]           at runRootCallback (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:21554:20)
     [exec]           at /opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:11353:24
     [exec]           at unstable_runWithPriority (/opt/dev/projects/github/liferay-portal/modules/node_modules/scheduler/cjs/scheduler.development.js:643:12)
     [exec]           at runWithPriority$2 (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:11305:10)
     [exec]           at flushSyncCallbackQueueImpl (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:11349:7)
     [exec]           at flushSyncCallbackQueue (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:11338:3)
     [exec]           at scheduleUpdateOnFiber (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:21431:9)
     [exec]           at dispatchAction (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:15816:5)
     [exec]           at dispatch (/opt/dev/projects/github/liferay-portal/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/components/list-view/ListView.es.js:51:4)
     [exec]           at fetchOnComplete (/opt/dev/projects/github/liferay-portal/modules/node_modules/@clayui/data-provider/lib/useResource.js:124:5) name: 'Invariant Violation' }
     [exec]     console.error ../../../node_modules/react-dom/cjs/react-dom.development.js:19814
     [exec]       The above error occurred in the <div> component:
     [exec]           in div (created by TableWithPagination)
     [exec]           in div (created by TableWithPagination)
     [exec]           in TableWithPagination (created by Wrapper)
     [exec]           in Wrapper (created by Wrapper)
     [exec]           in Wrapper (created by _default)
     [exec]           in _default
     [exec]       
     [exec]       Consider adding an error boundary to your tree to customize error handling behavior.
     [exec]       Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
     [exec]     console.warn ../../../node_modules/@clayui/data-provider/lib/useResource.js:105
     [exec]       DataProvider: Trying 1 of 5 will happen in 233.30681067848082ms
     [exec] 
     [exec]   ??? ListView ??? renders with 21 items and 2 pages
     [exec] 
     [exec]     expect(received).toBe(expected) // Object.is equality
     [exec] 
     [exec]     Expected: 20
     [exec]     Received: 0
     [exec] 
     [exec]       94 | 		});
     [exec]       95 | 
     [exec]     > 96 | 		expect(queryAllByTestId('item').length).toBe(20);
     [exec]          | 		                                        ^
     [exec]       97 | 		expect(container.querySelectorAll('li.page-item').length).toBe(4);
     [exec]       98 | 		expect(
     [exec]       99 | 			container.querySelector('li.page-item.active').firstElementChild
     [exec] 
     [exec]       at Object.toBe (test/js/components/list-view/ListView.es.js:96:43)
     [exec] 
     [exec] Test Suites: 1 failed, 1 passed, 2 total
     [exec] Tests:       1 failed, 4 passed, 5 total
     [exec] Snapshots:   0 total
     [exec] Time:        3.666s
     [exec] Ran all test suites.
```

**Comment by john-co** [comment]
All other test failures look unrelated.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:stop

**Comment by john-co** [comment]
The previous calendar, asset publisher and webcontent functional tests are passing on last test run.
The js-unit-jdk8 test failure with app-builder still looks unique.

Other test failures look unrelated.

**Comment by jbalsas** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/79488

**Pull request closed without merging**
