### PR TITLE
LPS-79691 Adding simple text support for tilde to Creole Parser

### PR DESCRIPTION
**Pull request by balazssk**
Hi @jbalsas
Can you please have a look at this review?

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @balazssk, I don't think this is correct, and LPS-79691 is invalid as far as I can tell.

In creole, the tilde is the escape character. See http://www.wikicreole.org/wiki/Creole1.0. If you want to add a tilde, you need to actually add the `~~` combination.

**Comment by balazssk** [comment]
Hi @jbalsas 
Thank you for your comment, I was struggling exactly with this when I took up this ticket.
In our understanding, if you type a single tilde in the preview panel of the editor, it should stay like that after publication. This means that a double tilde would be saved to the database.
However, if you parse the html to creole (publishing or switching view from preview to source), you will see that there is only a single tilde there. Which in Creole is a simple escape+<nothing> and will not be displayed.
Our aim is to have double tilde after the parsing.

If I recall correctly, this issue can most easily be reproduced in your way after publishing twice. If you add a double tilde in the preview mode and publish, indeed a single tilde would appear after publication. However, if you republish again without any changes, the single tilde will disappear.

Hope this clears up the confusion a bit.

**Comment by jbalsas** [comment]
Hey @balazssk, makes sense, thanks for the explanation, I'll take a closer look, but the change makes me worry :/

**Comment by jbalsas** [comment]
Setting `_verbatim` to false seems like an invitation to a big behaviour change... @antonio-ortega, what do you think?

**Comment by jbalsas** [comment]
Hey @balazssk, I'm still very wary of the effects this change can have on existing behaviour... could you try to limit the scope of the change or shed some light on why is it necessary and it won't affect anything else? 

This part of the code is not widely maintained, so it's hard for me to assess it.. pinging @sergio-gonzalez too, as he will be the most affected by this.

**Comment by sergiogonzalez** [comment]
Hey guys,
It's very hard for me to know the consequences of this change as well because I'm not familiar with this logic. 
However, considering that the issue is not critical, the impact it's very limited and that we have several questions and doubts about the possibility of regressions that this might create, I would suggest not merging this and consider it a limitation.
In this case I think it's better to be more cautious and live with this limitation than doing this change and then creating several regressions that might be worse than the bug we are trying to fix.
Thanks

**Comment by balazssk** [comment]
Hi @sergiogonzalez , @jbalsas ,

My reasoning for changing the _verbatim default value is that it is already set to false in _handleElementEnd. So, in my understanding, it is only affecting:
- the very first line in the document until the first closing html element,
- header elements
- and link elements.

In my opinion the uncontrolled first line shouldn't be happening.

**Comment by balazssk** [comment]
@jbalsas 
Yes, feel free to close this PR, but I'd really like to solve this issue, don't want to waste the time already in it.
Also thanks for the heads up about Creole support, I'll keep that in mind.

**Comment by jbalsas** [comment]
No problem @balazssk! Feel free to send this again our way, but if you're looking for things to fix, @antonio-ortega and myself can give you some hints at where to look 😉

**Pull request closed without merging**
