### PR TITLE
LPS-82243 Update portal's senna version

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:check:sf

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
ci:close @diegonvs you were looking for the command "ci:test:sf". You can always type "ci:help" to list available commands.

Pushed to BChan. https://github.com/brianchandotcom/liferay-portal/pull/60176

**Comment by diegonvs** [comment]
Thanks for the infos @jpince :)

**Pull request closed without merging**
