### PR TITLE
LPS-105706 Remove jQuery from portal

### PR DESCRIPTION
**Pull request by markocikos**
Hey @jbalsas ,

This are most of the commits from https://github.com/carloslancha/liferay-portal/pull/244, rebased and conflicts fixed. No errors in `ant all`.

Missing are the commits from LPS-106846 (modal in `portal-workflow-metrics-web`) and LPS-95726 (disabling jQuery by default). First one needs significant refactoring, so we can be sent is as a separate PR, second can be added after first.

Please review the code.

Thank you!

/cc @carloslancha

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Awsome!! 👏

**Comment by jbalsas** [comment]
Look what the SF caught, @wincent! -> https://github.com/jbalsas/liferay-portal/pull/2112/commits/a542bccbe0ebf5065419e7011515ef985b00ab40

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83980. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
