### PR TITLE
LPS-70562 Trigger a jquery event so the sidebarPanel could calculate his height.

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
@jbalsas Could you please have a quick look to these 3 last commits? 
I've been talking to @pat270 to see which one is the event to fire so the sidenav can calculate his height appropiately. And it has to be a jquery event.
If you find it ok I can send it directly to Brian Chan. 
Many thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @ambrinchaudhary, @pat270, I'm not sure this is the right fix... not that it doesn't fix the issue, but rather than it creates a really weird sensation. The height of the portlet is continually changing causing a very uncomfortable sensation. I think we probably want to have the outer containers with `overflow: hidden` and work with UX on what exactly should be happening here.

What do you think?

**Comment by pat270** [comment]
`overflow: auto;` somewhere would work.

**Comment by jbalsas** [comment]
Yeah, that's what I tested... that in combination with some `min-height` for the specific portlets should do the trick. We'll check with UX to see what they think.

Thanks @pat270!

**Pull request closed without merging**
