### PR TITLE
LPS-92572

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-92572

Includes the changes requested in https://github.com/jbalsas/liferay-portal/pull/1940

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79065. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @holatuwol, I've sent this to Brian without the url flag feature in the last commit. 

We don't really want to add url flags at this point for things that can be configurable by other means. Granted, only admins would be able to access and modify those settings, but I think that's to be expected.

I see this could be use to run some quick tests, but I don't think that on its own grants maintaining and documenting that feature flag. Please, let me know if you had other usages in mind that we should consider.

Thanks!

/cc @antonio-ortega, @david-truong

**Comment by holatuwol** [comment]
@jbalsas : When troubleshooting UI issues, I usually test with SPA and without SPA to rule out SPA as a potential cause. I mainly wanted to avoid restarting the server twice every time I need to test a UI issue.

**Comment by holatuwol** [comment]
@jbalsas : Also, while we don't have any of our own testing results, while reviewing an older ticket, one of our customers provided us with these timings with SPA enabled and with SPA disabled:

| Test | SPA | Chrome | IE11 |
| --- | --- | --- | --- |
| Test 1 | enabled | 0.565 sec | 5.8 sec |
| Test 1 | disabled | 2.26 sec | 3.1 sec |
| Test 2 | enabled | 0.510 sec | 6.8 sec |
| Test 2 | disabled | 1.8 sec | 3.3 sec |

**Comment by jbalsas** [comment]
> When troubleshooting UI issues, I usually test with SPA and without SPA to rule out SPA as a potential cause. I mainly wanted to avoid restarting the server twice every time I need to test a UI issue.

Makes sense. I would suggest to simply stop the `frontend.js.spa.web` module from the Gogo Shell, either via command line if enabled or through the admin UI. That would have the same effect without the need of restarting the server.

> Also, while we don't have any of our own testing results, while reviewing an older ticket, one of our customers provided us with these timings with SPA enabled and with SPA disabled:

Those are some numbers... 🤔. It's of course hard to evaluate and performance metrics are hard to get right. In any case, the trend seems obvious there. Being like that, it might make sense to just treat this as a bug in IE11 and turn it off by default on maintenance branches as well. As I said, I'll leave that entirely up to you to assess and manage customers' expectations and aftermath. 👍

**Comment by holatuwol** [comment]
> I would suggest to simply stop the frontend.js.spa.web module from the Gogo Shell, either via command line if enabled or through the admin UI. That would have the same effect without the need of restarting the server.

I think there's scripts provided by that module that forms uses, so you can't actually stop the module without other things breaking. However, I realized I could create a config file to blacklist the dynamic include component, so I'll do that from now on.

**Comment by jbalsas** [comment]
> I think there's scripts provided by that module that forms uses, so you can't actually stop the module without other things breaking. 

If that’s the case, that should be reported and fixed. The spa feature was designed as a drop-in and other features should not have necessary dependencies on it.

**Comment by jbalsas** [comment]
@brunobasto, does this form dependency ring a bell?

**Comment by brunobasto** [comment]
Not really. We shouldn’t be depending on the spa module itself. If we are, it’s probably a mistake and we need to fix it.

**Pull request closed without merging**
