### PR TITLE
LPS-61272 Migrate ui:ratings to modules/apps/ratings

### PR DESCRIPTION
**Pull request by thektan**
Hi @jbalsas!

Attached is an update for http://issues.liferay.com/browse/LPS-61272. Imported the ratings taglib to the message-boards-web module.

On my computer, only the message-boards-web module needed the import, but let me know if you're getting a different outcome since on @jonmak08's machine the blogs-web module was throwing package errors as well.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey guys, the issue with the `Import-Package` will probably be fixed by https://github.com/brianchandotcom/liferay-portal/pull/33547. Could you please try again after it gets merged?

**Comment by thektan** [comment]
Sure thing! I'll keep an eye on it. Thanks!

**Comment by thektan** [comment]
Hi @jbalsas!

There doesn't seem to be any issues without the import package statement now, so I removed the commit that added it. I also added the gradle dependencies for the modules using the taglib.

Let me know if there are any issues or things you'd like me to change. Thanks!

**Comment by jbalsas** [comment]
Hey @thektan, I haven't done a thorough review, but I see a couple of issues:

- We shouldn't add the kind of project dependencies we add on that last commit. Taglibs are wired as OSGi capabilities in runtime. Adding a `compile project(":apps:ratings:ratings-taglib")` couples everything together. We should drop that commit. What was the reason to add it in the first place?

- The `liferay-ui:discussion` taglib still uses the old prefix. @jonmak08 what was the reason of that change? If there's a problem we should identify it and try to fix it.

- As I pointed out [here](https://github.com/jbalsas/liferay-portal/pull/298#issuecomment-166021242), we need to extract the `js` code as well. This taglib makes use of `liferay-ratings`. We need to move it into the taglib following the existing examples or the linked commit.

- We need to make taglibs available to the `Freemarker` engine. For every `my-app-taglib` module we need a corresponding `my-app-taglib-freemarker-contributor` one. Could you please create it for this one as well? You can check how to do it in [site-navigation-taglib-freemarker-contributor](https://github.com/liferay/liferay-portal/tree/master/modules/apps/site-navigation/site-navigation-taglib-freemarker-contributor) or in [frontend-taglib-freemarker-contributor](https://github.com/liferay/liferay-portal/tree/master/modules/frontend/frontend-taglib-freemarker-contributor).

Could you please work on these changes and resend?

Thanks a lot!

**Comment by thektan** [comment]
Hi @jbalsas!

I thought I saw a commit that was adding the compile project to the gradle files, but I can't seem to find it anymore. Anyhow, I'll definitely remove that commit!

I think @jonmak08 reverted the change in the ui:discussion since it's currently being migrated ([LPS-61259](https://issues.liferay.com/browse/LPS-61259)). So those commits will probably be changed after the migration of the ui:discussion taglib is merged into master.

Thanks for the feedback! I'll fix the issues and get it back to you as soon as I can!

**Comment by jbalsas** [comment]
Hey @thektan,

I'll wait for Jon to answer, but we should keep that change in, no matter what the status of other PRs are. That's why it's usually a best approach to `git mv` files instead of copy-pasting and creating new ones. Changes can be kept when merging if there are no other conflicts. (It's also better for traceability)

The way we're doing it now, at least, we'll get a rebase error indicating that something went wrong. This should alert us to look into what changed into the file since we created our branch so we can properly reflect it on the new file.

If we don't keep it, we'll probably unknowingly end up missing some changes.

**Comment by jbalsas** [comment]
Hey @thektan, @jonmak08, @mjbradford89, I asked about the `gradle` dependencies. This is the state:

- *Ideally* they shouldn't be there and we should depend on published `jars` instead.
- We currently only publish modules on demand
- Some taglib modules are going to be changing a lot as the migration process advances

With this in mind, we've decided to:

- Add all the `gradle project` dependencies for now and
    - If the module is not expected to have more updates, ask Brian to publish it and change the dependency to the published jar **in a followup PR**
    - If the module is expected to see more updates in the near future, keep it as is to do a batch update later on.

Could you take this into account when migrating taglibs? 

Thanks a lot!

**Comment by jonmak08** [comment]
Hey @jbalsas and @thektan,

The reason I kept https://github.com/thektan/liferay-portal/commit/315ed528994c73734e10878ab758c8dfe69cb621 in this pull request was because the files were still in liferay-portal core and when we migrated them out to the OSGi module, the portal compile would fail because it could not include the newly created taglib.

Please let me know if you have any questions.  Thanks!

**Comment by jbalsas** [comment]
Oh, I see... I thought it was just because of the `velocity` dependency.

In that case, we should work on extracting the `liferay-ui:discussion` first. Is someone already working on that one?

**Comment by jonmak08** [comment]
Yes, there is a pull in my queue sent by @mjbradford89 at https://github.com/jonmak08/liferay-portal/pull/1401.

This was sent at the end of last week after this was sent to you.  I will work on reviewing https://github.com/jonmak08/liferay-portal/pull/1401.

**Comment by mjbradford89** [comment]
Hey guys, I worked on the liferay-ui:discussion taglib and sent a pull to Jon last week, but I will have to close it so I can create the `comment-freemarker-contributor` module, along with the other bnd dependency changes.

**Comment by mjbradford89** [comment]
Hey @jonmak08, you will probably want to hold off on reviewing it until I can get those other freemarker and bnd changes in.  I'll jump on that one as soon as I'm done doing the same for the social-activities taglib.  Thanks!

**Comment by jonmak08** [comment]
Hey @mjbradford89,

Thanks for the update.  I will wait until you give me ok to begin the review of the discussion taglibs.

Thanks guys!

**Pull request closed without merging**
