### PR TITLE
LPS-85136 - Remove aria selected

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
@john-co, could you check the failures here? Do they seem relevant?

**Comment by john-co** [comment]
@jbalsas, the failures here are not relevant to the PR.

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/63215. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
