### PR TITLE
LPS-89557 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LPS-89557

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hi @jbalsas, I ran all our acceptance tests here patriciajeanperez#155 and all the failures are unrelated. Thanks! 

cc @adolfopa

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @patriciajeanperez 

Can you send this to someone from User Management team anyway (QA if possible)? Even if all the tests pass, there could be visual changes that they need to double check.

Thanks!

**Comment by patriciajeanperez** [comment]
Pushed to @alee8888
https://github.com/alee8888/liferay-portal/pull/623

**Comment by adolfopa** [comment]
Thanks @patriciajeanperez !

**Pull request closed without merging**
