### PR TITLE
LPS-104672 Update Clay2 packages to 2.19.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @john-co, can you take a look at this? `test:relevant` seems to be failing... do you think it's related?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Failing on setup-profile-dxp task, I don't think this is related to the PR.
```
setup-profile-dxp:
     [echo] Executing Gradle task: checkoutDXPScript
     [exec] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
     [exec] Using proxy squid.lax.liferay.com:3128.
     [exec] 
     [exec] > Task :checkoutDXPScript
     [exec] git clone --branch=master-private --depth=1 --no-checkout --single-branch git@github-dev.liferay.com:liferay/liferay-portal-ee.git git-clone-profile-dxp
     [exec] Cloning into 'git-clone-profile-dxp'...
     [exec] Warning: Permanently added 'github-dev.liferay.com,10.0.0.37' (RSA) to the list of known hosts.
     [exec] error: refs/heads/cache-liferay-e59f79ff3dc77d46e6f74844aeacd7876d16bec4-marianoalvarosaiz-df7d71da4cbb2dd0f8c2b7dfc08d03bb057ac88a-1561547580767 does not point to a valid object!
     [exec] remote: error: refs/heads/cache-liferay-e59f79ff3dc77d46e6f74844aeacd7876d16bec4-marianoalvarosaiz-df7d71da4cbb2dd0f8c2b7dfc08d03bb057ac88a-1561547580767 does not point to a valid object!        
     [exec] 
     [exec] BUILD SUCCESSFUL in 11s
     [exec] 1 actionable task: 1 executed
     [exec] Gradle build finished at 2019-11-25 20:41:14.072.
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/modules/build/reports/profile/profile-2019-11-25-12-41-03.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
[beanshell] 3821 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 9 seconds 688 ms.
[beanshell]     https://api.github.com/repos/jbalsas/liferay-portal/pulls/2053
[beanshell] Executing commands: cat /tmp/429533040.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.
```

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81419. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
