### PR TITLE
LPS-98299 JPG and JPEG extensions are not normalized

### PR DESCRIPTION
**Pull request by IstvanD**
Dear @jbalsas 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75804. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @IstvanD, I've forwarded this to Brian. In the future, please, send portal PRs to @julien instead.

Thanks!

**Comment by IstvanD** [comment]
Thank you @jbalsas for forwarding.
I'm sorry for the missassignment. The document https://grow.liferay.com/share/Frontend+Infrastructure+-+Code+Review+Process seems to be obsolete then.

Best regards,
István

**Comment by jbalsas** [comment]
Hey @IstvanD, no worries. I was in fact talking to @antonio-ortega about this. In theory, all support issues should go through our SME, so please, be so kind as to direct your PRs to him instead. 

Thanks!

**Comment by IstvanD** [comment]
I see.
In the future, I'll should send the UI related PR to @antonio-ortega then, if I understand correctly.

Best regards,
István

**Comment by jbalsas** [comment]
Exactly! Thanks for understanding! :)

**Pull request closed without merging**
