### PR TITLE
LPS-89096 use aria label in a nav tag instead of role="navigation"

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @marcoscv-work

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/67344. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
