### PR TITLE
LPS-102561 Change metal+soy component for React component

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @julien, for this, of course, I have the same doubts I expressed in https://github.com/jbalsas/liferay-portal/pull/1963

/cc @wincent, @boton

**Comment by julien** [comment]
@jbalsas yes I imagined that, let's see what we decide to do with these, thanks.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/julien/liferay-portal/pull/158. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/2bc847c90cc4~1...2bc847c90cc4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
