### PR TITLE
LPS-116752 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-116752

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
I think the Button.clickAdd macro should be using the Button#ADD path instead of Button#ANY. We'll investigate in a separate ticket to refactor the paths.

**Comment by john-co** [comment]
I just realized that we had just tried to fix this path very recently...lol https://github.com/liferay-frontend/liferay-portal/pull/2#issuecomment-653110076

I think it's normal workflow to update path locators using selenium as testing framework, but we'll see what adjustments we can do.

**Comment by jbalsas** [comment]
> I just realized that we had just tried to fix this path very recently...lol liferay-frontend#2 (comment)
>
> I think it's normal workflow to update path locators using selenium as testing framework, but we'll see what adjustments we can do.

It's the gift that keeps on giving :)

**Comment by jbalsas** [comment]
This should be upstream

**Pull request closed without merging**
