### PR TITLE
LPS-73140 Puts propagated request param under "requestParams" injected data

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @hhuijser, this PR is choking on `formatSource` in the `portal-template-soy` module. Could you help us figure out why? 

Thanks!

/cc @brunobasto

**Comment by hhuijser** [comment]
@jbalsas been out of the office, will look at that after the weekend

**Comment by brunobasto** [comment]
Thx, @hhuijser

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
@jbalsas @brunobasto 

I checked out your branch and ran sourceFormat without problems:

> C:\github\liferay-portal\modules\apps\foundation\portal-portlet-bridge>..\..\..\..\gradlew formatSource
> Configuration on demand is an incubating feature.
> :apps:foundation:portal-portlet-bridge:portal-portlet-bridge-soy:formatSource
> POM relocation to an other version number is not fully supported in Gradle : xml-apis:xml-apis:2.0.2 relocated to xml-apis:xml-apis:1.0.b2.
> Please update your dependency to directly use the correct version 'xml-apis:xml-apis:1.0.b2'.
> Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
> Dependency 'com.liferay:com.liferay.source.formatter:1.0.418', published Tue Jul 11 01:36:15 CST 2017, is older than the latest one available ('com.liferay:com.liferay.source.formatter:1.0.424', published Sat Jul 15 00:07:41 CST 2017), but not yet expired
> 
> BUILD SUCCESSFUL
> 
> Total time: 27.608 secs
> 
> C:\github\liferay-portal\modules\apps\foundation\portal-portlet-bridge>

**Comment by brunobasto** [comment]
Hey @hhuijser, thanks for testing it. That's weird. Both me and @xbrianlee have experienced source formatter hanging. Let's see if the CI passes this time.

Thx again

**Comment by hhuijser** [comment]
Okay, looks like it is hanging on CI as well... will dig to see what's happening

**Comment by hhuijser** [comment]
@jbalsas @brunobasto, turns out it hangs on /foundation/portal-template/, not /portal-portlet-bridge-soy/

Anyway, the file that it hangs on is SoyTemplateConstants.java

Author and copyright is missing and somehow SF gets into infinite loop. I can get a fix in for this, but probably not this week as I am pretty busy. Can you manually fix that file for now?

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50360. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/6067cc4~2...6067cc4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Thanks a lot, @hhuijser!!

**Comment by brunobasto** [comment]
Thanks @hhuijser

**Comment by hhuijser** [comment]
@jbalsas @brunobasto just FYI, this one will fix the infinite loop for next time: https://github.com/brianchandotcom/liferay-portal/pull/50369

**Comment by brunobasto** [comment]
Awesome! Thank you!

**Pull request closed without merging**
