### PR TITLE
LPS-104445

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-104445

Variant of https://github.com/jbalsas/liferay-portal/pull/2042 that updates portlet CSS instead of theme CSS.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
@marcoscv-work, can you review this? Do we want to add `width:100%` only in the case of IE11?

**Comment by marcoscv-work** [comment]
> @marcoscv-work, can you review this? Do we want to add `width:100%` only in the case of `.ie`?

@jbalsas yes, the original issue is in IE, and it should be applied only in IE in order to prevent future flexbox width rendering issues in modern browsers. In the other hand, it will be easy to be removed when we drop the IE support, only searching for `.ie` clase names and remove them

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2628. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/b58fb60606f1~1...b58fb60606f1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
