### PR TITLE
LPS-104262 Removes no longer necessary hack

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by john-co** [comment]
Hi @jbalsas, It looks like the same tests are failing with the same issues as https://github.com/wincent/liferay-portal/pull/92#issuecomment-550417410 

* regression: clicking on plus button that leads to a modal 1 time doesn't do anything.
* Test fix: tooltip path Message#TOOLTIP `//div[contains(@class,'tooltip-content')` no longer present. Possibly update to `//div[contains(@class,'tooltip-inner')]` or `//div[contains(@class,'tooltip') and contains(@class,'show')]`

**Comment by jbalsas** [comment]
ugh, yeah, I forgot to push my changes and retest... will do so later :(

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co, I verified the issue and in theory fixed it, but ironically I see more broken tests than yesterday... can you please take a look? 😢

**Comment by jbalsas** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
going to resend in the meantime, just in case

**Pull request closed without merging**
