### PR TITLE
LPS-61515 Create site-navigation js component and migrate navigation taglib js components

### PR DESCRIPTION
**Pull request by thektan**
Hi @jbalsas!

The navigation taglib was migrated already ([LPS-60328](https://issues.liferay.com/browse/LPS-60328)) and I noticed that there were js components for it as well. I'm not sure if there's anything else to add besides defining the JS-Config in the bnd file.

I also just wanted to say I appreciate the feedback you've been providing. It's really helpful in understanding not only what needs to be fixed, but the concepts behind them as well! 

Thanks!

### CODE REVIEW

**Comment by thektan** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @thektan, thanks for submitting this!

Unfortunately, I think there's been a misunderstanding here. If you look closely, the `liferay-navigation-*` modules are not related to the `site-navigation-taglib`. You can see this by searching for the string `liferay-navigation` throughout portal. 

In this case, this module is used in:
- `site-navigation-menu-web` in different templates
- `bottom_js.jspf`

We could definitely do some reorganization around there, but that will be out of the scope of the taglib work we're currently doing.

Please, let me know if you have ay doubts regarding this.

Thanks again!

PS: I'm happy to provide any feedback you guys might need. Don't ever hesitate to ask for it :wink:

**Comment by thektan** [comment]
I see! Thanks for clearing that up!

**Pull request closed without merging**
