### PR TITLE
LPS-102115 - Disable toggle card in compatibility layer

### PR DESCRIPTION
**Pull request by eduardoallegrini**

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
The [modules-unit test failure](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271550/AXIS_VARIABLE=0,label_exp=!master/consoleFull) could be related:
```     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Could not resolve all files for configuration ':apps:document-library:document-library-web:testCompileClasspath'.
     [exec] > Could not download assertj-core.jar (org.assertj:assertj-core:3.10.0)
     [exec]    > Could not get resource 'http://repository-cdn.liferay.com/nexus/content/groups/public/org/assertj/assertj-core/3.10.0/assertj-core-3.10.0.jar'.
     [exec]       > Premature end of Content-Length delimited message body (expected: 3964428; received: 236465
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':apps:document-library:document-library-web:testCompileClasspath'.
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1054)
```

Test failure from CPSharepoint#MoveDocumentToHome doesn't look related to the PR but seems to be a similar issue from [LPS-104350](https://issues.liferay.com/browse/LPS-104350?focusedCommentId=2007766&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2007766) where the personal menu avatar disappears inconsistently

**Poshi Report:** 
[CPSharepoint_MoveDocumentToHome - Poshi Report](https://testray.liferay.com/reports/production/logs/test-1-5/1573572293933/test-portal-acceptance-pullrequest(master)/5806/functional-tomcat90-mysql57-jdk8/54/0/LocalFile.CPSharepoint_MoveDocumentToHome/index.html.gz)

It looks like the personal menu avatar disappears after publishing the third DM file.

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

the modules-unit test failure appears on upstream tests:
https://test-1-11.liferay.com/job/test-portal-acceptance-upstream-batch(master)/46479/AXIS_VARIABLE=0,label_exp=!master/consoleFull

**Comment by jbalsas** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/80892

**Pull request closed without merging**
