### PR TITLE
LPS-69747 Fix user agent test strings to resemble real browser values and make tests pass

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
All tests LGTM.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54245. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
