### PR TITLE
LPS-75424 - MB attachments fix

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by marcoscv-work** [comment]
ci:open

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @marcoscv, what does `min-height: 100%` means? 😂

**Comment by marcoscv-work** [comment]
This prevents the value of the height property from becoming smaller than min-height, previous height: 100% was having the previous element height in old browser versions like Firefox 45

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52667. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
