### PR TITLE
LRDOCS-4157 JSDOC review

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jbalsas I wanted to send this first batch to you for review before sending to Brian, just to make sure everything looks good to you. Also a couple things:

1. The `@inheritDoc` tag does not work last I checked. It doesn't inherit the docs from the parent class as you think it would when the JSDocs are generated.
2. Right now, there is a space between the JSDoc and the function. Based on what I've seen, there shouldn't be one for proper formatting. Is this the format we want to follow? or is that still being decided?

### CODE REVIEW

**Comment by jbalsas** [comment]
Looks good, @mwilliams2014! Feel free to send it forward! 👍

**Comment by jbalsas** [comment]
Or I can do it if you prefer :)

**Comment by mwilliams2014** [comment]
@jbalsas what are your thoughts on the questions I commented above?

**Comment by jbalsas** [comment]
Sorry, I could swear they weren't there when I started reviewing 😂 

1. That's fine for now if we don't know a way to do it. We can keep it there for now until we find a solution
2. The extra line comes from the automatic formatter, nothing we can do about it at the moment. @natecavanaugh, could you take a look at this, please?

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56564. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
