### PR TITLE
LPS-67082 Simplify the way to reply with quote

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc @sergiogonzalez

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3347. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/4252f57~2...4252f57) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
