### PR TITLE
LPS-75372 - Properties fixes

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by jpince** [comment]
@marcoscv-work @jbalsas I built on master-private head + commits from this pull. portal started up fine, but I noticed this exception in my log: `standard-theme.war does not support this version of Liferay` 
https://gist.github.com/jpince/0848d0f7d916737724ddb75779f201f1
not sure if this is something that needs to be fixed right away, just thought I'd let you guys know

**Comment by jbalsas** [comment]
Hey @jpince, this theme is only meant to be used on 7.1.+, so I guess `master-private` is still signaling `7.0.+`?

**Comment by jpince** [comment]
@jbalsas I thought @achaparro already updated all version information in https://github.com/brianchandotcom/liferay-portal/pull/51879, but I don't understand the technical details of what he did to know for sure.

**Comment by achaparro** [comment]
@jbalsas @marcoscv The release version of the portal should be 7.1.0 and the theme properties are aligned with it (in this case it's checking liferay-plugin-package.properties), could you test it locally (using master-private) so that we can distinguish if it's a problem with the theme or with CI?

Cheers.

@jpince

**Comment by jbalsas** [comment]
Hey @achaparro, the theme works fine on `master`. If I understand correctly, @jpince tried to use it on his own branch on `master-private`, which is where it fails, not on the CI.

**Comment by jpince** [comment]
Yes, I built the branch locally on master-private and it failed.

-- 
Jason Pince
Lead Test Engineer


Liferay Inc. | 1400 Montefino Avenue, Diamond Bar, CA 91765 USA |
877-543-3729 <(877)%20543-3729>
_____________________________________________________________________

*Confidentiality Notice:* This e-mail message, including any attachments,
is for the sole use of the intended recipient(s) and may contain
confidential and privileged information. Any unauthorized review, use,
copying, disclosure or distribution is prohibited. If you are not the
intended recipient, please contact the sender by reply e-mail and destroy
all copies of the original message.

**Comment by achaparro** [comment]
@jpince, could you check buildNumber value for the portal in the release table in your database?

**Comment by jpince** [comment]
It shows 7010 (I think I did the query correctly?)
```
mysql> select buildNumber from lportal.release_;
+-------------+
| buildNumber |
+-------------+
|        7010 |
|           0 |
|           0 |
|           0 |
|           1 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|           2 |
|           0 |
|           1 |
|           2 |
|           2 |
|           2 |
|           3 |
|           1 |
|           3 |
|           0 |
|          10 |
|           0 |
|           1 |
|           0 |
|           1 |
|           1 |
|           2 |
|           6 |
|          15 |
|           1 |
|           0 |
|           0 |
|           0 |
|           0 |
|           2 |
|           1 |
|           0 |
|           1 |
|           1 |
|           2 |
|           0 |
|           2 |
|           1 |
|           1 |
|           1 |
|           3 |
|          15 |
|           1 |
|           7 |
|           6 |
|           3 |
|           3 |
|           1 |
|           2 |
|           1 |
|           8 |
|           2 |
|           1 |
|           2 |
|           1 |
|           1 |
|           3 |
|           3 |
|           1 |
|           9 |
|           1 |
|           0 |
|           0 |
|           5 |
|           2 |
|           1 |
|           0 |
|           0 |
|           0 |
|           0 |
|           0 |
|         412 |
|         100 |
|           3 |
|           2 |
+-------------+
187 rows in set (0.01 sec)
```

**Comment by achaparro** [comment]
Hi @jpince,

That's the problem, the buildNumber should be 7100. How do you build that environment? Has it been updated with the 7100 commits?

Thanks.

**Comment by achaparro** [comment]
Hey @jpince,

I have just realized that the environment where you are deploying the theme is DXP (7010) so it's natural to get than error since, as @jbalsas said, that theme is only valid for 7100.

Cheers!

**Comment by jpince** [comment]
@achaparro why is master-private considered a DXP environment? Shouldn't it have the version info updated to 7100 (or 7110?)

here was my procedure:
start with a clean database
master-private git ID: [373e3c864a571577167c9dbf028ebe5ab092006a|https://github.com/liferay/liferay-portal-ee/commit/373e3c864a571577167c9dbf028ebe5ab092006a]
fetch Marco's branch `LPS-75372-standard-theme-B` and overwrite master branch
change git-commit-portal to [3e6cc7e|https://github.com/marcoscv-work/liferay-portal/commit/3e6cc7e94c7792cb3f13ed95dccddf73e38e1431] from Marco's branch
ant -f build-working-dir
ant all

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52950. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/04bda4196b74~2...04bda4196b74) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @jpince,

Future 7110 is based on current 7100 so it can't be generated until release time.

If you deploy master and master-private in the top of it your release version should be 7100. If you need it, you can investigate if the _ReleaseInfo.java_ is overwritten somehow (in that class the release build number is defined)

Cheers.

**Comment by jpince** [comment]
Thanks @achaparro. I'll look into this with Chas.

**Pull request closed without merging**
