### PR TITLE
LPS-63474 Partial revert

### PR DESCRIPTION
**Pull request by Preston-Crary**
Hi @jbalsas,

@shuyangzhou was looking into performance improvements and we think we discovered that the SPAFilter is not needed to fix [LPS-63474](https://issues.liferay.com/browse/LPS-63474).  @anthony-chu also confirmed this by retesting without the filter.

Since you're the one who added it can you confirm if it's okay to remove the SPAFilter?

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @Preston-Crary, @anthony-chu, @shuyangzhou,

This is still very much necessary. This is [used by `senna.js`](https://github.com/liferay/senna.js/blob/0d1e4a27c7bfbd814d625b9537a58af5e11344ed/src/screen/RequestScreen.js#L239-L246) as a fallback mechanism in IE to account for [responseUrl](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL) missing support.

A way to properly test this is:
- Using IE, navigate to portal (not being logged in)
- Log in
- Manually refresh the page

You'll see that if you disable the filter, the url in the address bar will be the one of the login portlet and not the final redirected url, so a refresh won't keep you in the home page.

What we could do is enable the filter for IE only. Would that help? If so, could you please send a new PR?

Thanks!

**Comment by anthony-chu** [comment]
@shuyangzhou I've confirmed the steps provided by @jbalsas and updated the description with these new steps on [LPS-63474](https://issues.liferay.com/browse/LPS-63474).

**Comment by shuyangzhou** [comment]
Thanks @anthony-chu !

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/3204

**Comment by jbalsas** [comment]
Thanks @Preston-Crary!

**Pull request closed without merging**
