### PR TITLE
[TECHNICAL-SUPPORT] LPS-103179

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @jonathanmccann, could you please add a test for this case? [BrowserSnifferImplTest](https://github.com/liferay/liferay-portal/blob/master/portal-impl/test/unit/com/liferay/portal/servlet/BrowserSnifferImplTest.java) is already there, so it should be relatively straightforward.

Please, send to @izaera for final review.

Thanks!

**Comment by jbalsas** [comment]
(closing here and reassigning LPS just to keep track)

**Comment by jonathanmccann** [comment]
https://github.com/izaera/liferay-portal/pull/114

**Pull request closed without merging**
