### PR TITLE
LPS-80998 toolbar extracted outside re-rendering jsps

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by zoltancsaszi** [comment]
https://issues.liferay.com/browse/LPS-80998?focusedCommentId=1813313&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1813313

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/danielkocsis/liferay-portal/pull/740. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
