### PR TITLE
LPS-68726 Only assert partial text for tags

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @vbence86

**Comment by jbalsas** [comment]
Hey @vicnate5, could you take a look at these failures? Do they look like real positives? Could you help us understand the problem and how to reproduce it?

@patriciajeanperez already fixed some tests in this same PR, so maybe we just need to make similar adjustments?

Thanks!!

**Comment by vicnate5** [comment]
@jbalsas Sorry for the delay, I sent the fix for the workflow tests in the subrepo https://github.com/liferay/com-liferay-portal-workflow/pull/151. After this is merged I can forward this to Brian, unless there is more review needed.

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/51567

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
