### PR TITLE
LPS-70057 Expand range of valid status codes

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @jbalsas, if we consider that status codes between 200 and 499 should redirect to a page instead of showing an error alert to the user, then I think this solution should be ok. What do you think?

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brunobasto, yeah, I'd say that should be enough, maybe even adding `500` too... @adolfopa, could you please check to see if this fixes your issues?

**Comment by adolfopa** [comment]
Works perfectly :-)

Thanks a lot @brunobasto @jbalsas

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46122. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/b01db00~1...b01db00) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
