### PR TITLE
LPS-87254 Remove lodash usage from frontend-js-aui-web

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co, can you keep an eye on these test results? This is a mid-risk PR.

Thanks!

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
3. Verified JSError upon clicking a document title on Document and media portlet.

jserrorpagedocument

**Comment by jbalsas** [comment]
Closing here, @julien, please analyze and resend? Thanks!

**Pull request closed without merging**
