### PR TITLE
LPS-68460

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-68460.  I sent this to you because you removed the hidden input at https://github.com/liferay/liferay-portal/commit/7336a7d00194ad4aefb0e6855c65b5d03ee4b5ce but it is needed for this use case.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @jonmak08, @BryanEngler 

I'll take a closer look at this next week with @juliocamarero, but my first reaction is to reject this. 

Based on all the times someone has tried to re-add the hidden inputs, there's always a better, more standard and html-compliant way to do that. Most of the times, it involves changing how you think and approach these kind of issues to stay as close to html as possible.

If you can think of a different approach that doesn't involve this, we'll greatly appreciate it 😉

**Comment by BryanEngler** [comment]
just wondering if you guys know when you might have time to take a look at this?

**Comment by jbalsas** [comment]
Hey @BryanEngler, sorry about the delay, but we've been busy with DXP and Spain Symposium the past weeks.

As I said, though, this is most likely not going to be the right fix. By reading the issue description, I imagine that you might not want those checkboxes in there at all to begin with (if they're not configuring anything, what's the sense in having them?). It's probable that this could be solved by some tweaking in what is submitted in the form and what gets processed in the action.

Again, it would help if you can revisit your fix with this in mind. Otherwise, we'll try to look into it as soon as possible.

Also, this is first an issue in Message Boards, so it should be tagged as such and not a generic UI Taglibs. CC'ing @sergiogonzalez and @adolfopa

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/adolfopa/liferay-portal/pull/367. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @BryanEngler, I've talked to @adolfopa and he'll take care of fixing this properly on the MessageBoards side.

Thanks!

**Pull request closed without merging**
