### PR TITLE
LPS-68581 Ignoring inline height to keep the ratio.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey @jbalsas 

Could you help review this pr?

It seems we are not allowed to change journal code in liferay portal repo right now

So I sent another pr to https://github.com/liferay/com-liferay-journal/pull/20

Thanks
John.

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey @jbalsas
Could you help to review this ticket as high priority as this issue has been open long time for a customer?

Thanks,
Dale

**Comment by jbalsas** [comment]
Hey @daledotshan, we're looking into this since we're not convinced this is the right fix and want to provide a better alternative.

Feel free to provide a hotfix to the customer, but we need to analyze this issue carefully since it affects a big amount of applications.

**Comment by daledotshan** [comment]
Hey Jbalsa,
I talked about this issue with Zsolt and he said he escalated this issue to you. You mentioned we can create a hotfix first if it is urgent for customer but I have confirmed with Zsolt so far we are not ready to build a hotfix for DXP so provide a hotfix seems impossible right now

What is your opinion on this issue? Are you working on this issue?

Thanks,
Dale

**Comment by jbalsas** [comment]
Hey @daledotshan

**Comment by jbalsas** [comment]
Hey @zxdgoal, as discussed, we won't accept this fix as is. Teams will work on documenting this behaviour and we're trying to put some mitigation strategies in place: https://github.com/liferay/alloy-editor/issues/601

**Pull request closed without merging**
