### PR TITLE
LPS-114061 - Apply the use of sheet clay taglib in user-associated-data-web

### PR DESCRIPTION
**Pull request by marcoscv-work**
As part of our effort to Improve HTML Layout Generation Strategies in DXP, here a PR about changing autofit-* and sheet-* for clay:sheet* and clay:content*

LPS-114060:
Use new Layout Tags in JSPs in sync-web
- settings.jsp
How to test it: go to Sync web > Settings and review the sheet container is the same

LPS-114061
Use new Layout Tags in JSPs in user-associated-data-web
* add_uad_export_processes.jsp
* anonymize_nonreviewable_uad_data.jsp
* review_uad_data.jsp
How to test it: go to `user associated` and review the sheet container is pretty similar

LPS-114059
Use new Layout Tags in JSPs in staging-taglib
* content/page.jsp
* deletions/page.jsp
* permissions/page.jsp
* select_pages/page.jsp
How to test it: activate and go to `staging` and review all the application screens, all sheet container should be displayed correctly.

/cc @eduardoallegrini

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
