### PR TITLE
LPS-98874 Getting the node directly from document

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @jbalsas ,

This issue happens because title editor in blogs is a div tag. Because of that when we look for the elements in [aui-form-validator](https://github.com/liferay/alloy-ui/blob/master/src/aui-form-validator/js/aui-form-validator.js#L731) is not found and return null.

Instead of looking the DOM Node using AUI methods we could try to get it directly from document.

Thanks.

Regards.

/cc

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@john-co It looks like this causes new regressions. Can you investigate?
https://testray.liferay.com/home/-/testray/runs?testrayBuildId=701989107

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @antonio-ortega, The regressions seem related to this pull since they were not observed in upstream.

It looks like after clicking Save in certain areas the page hangs or does nothing.
1. Adding a new Page
Selection_054

2. Saving a configuration > Display Settings on asset publisher
Selection_056

3. Toggling Change List: CP > Change Lists > Settings > Save > "Error occured"
Selection_057

4. Trying to Add a Page through Navigation Menu
Selection_055


I'll investigate further with the bundle when it's available.

**Comment by jbalsas** [comment]
Resent this as https://github.com/brianchandotcom/liferay-portal/pull/76321. Please check there for test status.

**Pull request closed without merging**
