### PR TITLE
LPS-86144 Adds actions to folder dropdown

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Closing, I think @carloslancha should have an updated version with the latest changes

**Comment by carloslancha** [comment]
Yes, I'm on it (it's being more difficult than expected 😅 )

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
