### PR TITLE
LPS-102086 Deactivating compat_alerts from classic and admin themes

### PR DESCRIPTION
**Pull request by eduardoallegrini**

### CODE REVIEW

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80669. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by john-co** [comment]
lfr-spa loading errors, should be fixed by https://github.com/jbalsas/liferay-portal/pull/2022

likely fluke:
CPRolesCPWebcontent#AddTemplateSiteRoleDefinePermission - same error occurred in another PR within past 24 hours.

Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=865574706&testrayRunIdA=866208910&statusB=2

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80766. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
