### PR TITLE
LPS-78451 SF

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
Testing again to check if those are false positives

**Comment by izaera** [comment]
So, false positives as I said 😎

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/73. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f7949e11e5b4~1...f7949e11e5b4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
