### PR TITLE
Updates clay to 2.1.12

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:retest

**Comment by julien** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60485. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60507. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/3ab42306d4bf~1...3ab42306d4bf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
