### PR TITLE
LPS-100126 Update `openToast`  command for using React

### PR DESCRIPTION
**Pull request by diegonvs**
Things that I discovered:

- We must have a single React instance (such as an overlay) for working on adding things like notifications and etc.
- Several DOM treatments (`dom.addClasses`, etc.) are required to reuse React components in the Portal commands. (See https://overreacted.io/the-bug-o-notation/)
- Doing these commands in Metal was easier, since the components were instantiable, unlike React.
- Considering this implementation, We can't stack toasts due to previous explained issues.

About the React instance for notifications, etc. Do you have any ideas folks? @matuzalemsteles @wincent @bryceosterhaus

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/wincent/liferay-portal/pull/71. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
