### PR TITLE
Uses the same backend response of Page Editor for creating panels and sidebarPanels on DLB Sidebar

### PR DESCRIPTION
**Pull request by diegonvs**
For maintain the same pattern as the Page Editor, I changed the backend for supporting the same shape of allowed response as Page Editor was receiving. I modify this for not using the separators API as I sent some days ago and for maintain consistency between sidebars.

Just one thing was changed from the original Page Editor sidebarPanels response, a `pluginsEntryPoint` was added for providing multi panel support from another modules.

### CODE REVIEW

**Comment by diegonvs** [comment]
f1b0459 is huge. If you prefer, I can split into small commits for a better commit history.

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/wincent/liferay-portal/pull/157. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f114402488f3~4...f114402488f3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
I think @wincent will squash it all and then work his way up from there

**Comment by wincent** [comment]
Specifically, I am going to reconcile this one with [the other overlapping pull that I have here](https://github.com/wincent/liferay-portal/pull/156). Will squash both, try to sort out any discrepancies, and split into React parts (LPS-108987), JSP parts (LPS-108987), and whatever might be left (maybe, LPS-108989). If I can get all that tested and working together, we can get all this over to Brian.

**Pull request closed without merging**
