### PR TITLE
LPS-68298: Add npm-shrinkwrap.json (autogenerated)

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
@jbalsas I added that, because when changing the configuration (from the Portal) and reloading the page there was an error concerning `require` and `define` to be `undefined`, but let me double check.

**Comment by julien** [comment]
Yes, you mean just calling `Liferay.Loader.require` and forgetting the local variable?

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ithildir/liferay-portal/pull/520. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/ca88b6f~2...ca88b6f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
