### PR TITLE
LPS-108270 Move AuiConfiguration to Third Party section of settings

### PR DESCRIPTION
**Pull request by izaera**
cc/ @markocikos @john-co

I have moved the configuration from Infrastructure to Third Party as @jbalsas requested in [this comment](https://github.com/jbalsas/liferay-portal/pull/2134#issuecomment-585986582).

Given that @john-co asserted that the tests are correct in [this comment](https://github.com/jbalsas/liferay-portal/pull/2139#issuecomment-586482402) I guess we can send this to Brian... 

@jbalsas anything else to add? @marcocikos plans to work on top of this once it is merged. And the rest of the team shouldn't notice anything as AUI is enabled by default (as before).

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relvant

**Comment by jbalsas** [comment]
@wincent, can you take this, test it out and push it forward if you don't see anything out of the ordinary?

Thanks!

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Will close this and proceed in https://github.com/wincent/liferay-portal/pull/140

**Comment by wincent** [comment]
ci:close

**Pull request closed without merging**
