### PR TITLE
[Lex] A.Input

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-60553.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @jonmak08 

The `liferay-ui:icon` doesn't currently have a lexicon view, so is this really applying lexicon?

**Comment by jonmak08** [comment]
- Add lexicon folder to the taglib and move the lexicon changes to the lexicon folder

**Comment by jonmak08** [comment]
Hey @jbalsas,

I have added the ```markupView="lexicon"``` to the ```<aui:input />``` taglib as requested with the commit  https://github.com/jonmak08/liferay-portal/commit/6bee0d42bf539793d48cff6b51a1bec080735dc6.

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
Closing pull request

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/wincent/liferay-portal/pull/248. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/8484abb6fbd0~2...8484abb6fbd0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
