### PR TITLE
[TECHNICAL-SUPPORT] LPS-78904

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @SpencerWoo

### CODE REVIEW

**Comment by SpencerWoo** [comment]
We tested further and found this change does not regress LPS-51733's behavior and successfully resolves LPS-78904's behavior.  AlloyEditor change because the issue also affects Journal and isn't specific to Blogs.

**Comment by SpencerWoo** [comment]
Hi @jbalsas 
Yes, in testing I can copy google searched images that have styles when inspected (or manually adding style elements) and when pasting these external images into AE the image does not have the style attribute.

Let me know if you get different results.

**Comment by jbalsas** [comment]
Hey @SpencerWoo, based on what you're telling me, the value of the `styles` flag does not affect whether or not a dom element with a `styles` attribute style set carries over that value into AlloyEditor?

If that is like that:
1. There is a clear bug in the filtering behaviour
2. How does that fix the image problem? Isn't it caused because that code is filtering the `style` attribute in the first place?

**Comment by SpencerWoo** [comment]
@jbalsas

Without testing again LPS-78904 is resolved and LPS-51733 is not regressed.

I understand the confusion because the former copies the style and the latter does not copy the style. 
 In hypothesis, the difference could be because we're filtering external copies.  Again, not blog-specific filtering but AE.

If there's further questions please do test the change.  It will help us avoid misunderstandings.

**Comment by jbalsas** [comment]
Hey @SpencerWoo, I **did** test the change. I don't understand why the old code worked the way it did and why the new one is behaving as it is.

In good conscience, I can honestly don't push this through, as it's very hard for me to foresee the consequences.

It's fine if you can't put dedicate additional time to thoroughly investigate this. I'll get to it when I can and try to figure out what change in CKEditor and how should this be set up properly now.

**Comment by SpencerWoo** [comment]
Hi @jbalsas, 
Thank you for the clarification, I was under the impression the questions were replacing actually testing the change.

I appreciate the thorough review and understand on holding off on pushing this forward until we investigate further.  Thanks!

**Comment by duracell80** [comment]
All,

I have some insight that might be helpful, or not. I'm the reporter of this issue, I've seen a few issues where in particular on the blogs are having UX issues because code is being scrubbed. Myself I've added class="btn btn-default" to a link to make it a call to action for blog readers and that has been stripped too when switching back from source view.

I understand and agree that external content should be stripped to maintain consistent blog publishing.

**Might there be an issue with implementation of  the scrubbing?** So everyone has the option to "paste as plain text" in the browser when they copy styled code into a blog and rebuild the styles using AE. Even if they don't ... shouldn't this scrubbing be optional? This seems to be enforced for a narrow use case but is affecting all use cases. 

Allow content editors to "paste from external" and make that a feature where the scrubber is applied in that case only. If they fail to use copy as plain text or fail to use that feature "paste from external" that's on them.

I can't see why this should interfere with UX and existing features? Could the scrubbing be optional or silo-ed into a specific text box entry / modal where users pre-scruib the content before it's pasted into Alloy Editor. Just spending my tuppence for the day.

**Comment by duracell80** [comment]
Additionally can we have better control over what is and isn't stripped? Put this list into a portal-properties file or on the web UI of the control panel under Blogs?

`var contentFilter = new CKEDITOR.filter(
	{
		$1: {
			attributes: ['alt', 'aria-*', 'height', 'href', 'src', 'width'],
			classes: false,
			elements: CKEDITOR.dtd,
			styles: false
		}
	}
);`

**Comment by jbalsas** [comment]
Hey @duracell80, nice to see you around. I think we've been over this before. The allowed content is configured per-application. 

At this point, the behaviour in Blogs is the intended as per our UX (at the time) definition and @sergiogonzalez is in charge of it. The idea behind it was to allow the admin or theme developer to have full control over the blog content to offer a consistent experience. Looking back, we probably should've hidden the "Source" option too, to avoid all this confusion... @sergiogonzalez, are we planning any changes for this?

As of how easy it is to configure, you can simply [create an EditorConfigContributor](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/modifying-an-editors-configuration) to change the content you want and any other editor configuration. See how [Blogs is using that same mechanism](https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/blogs/blogs-editor-configuration/src/main/java/com/liferay/blogs/editor/configuration/internal/BlogsContentEditorConfigContributor.java#L70-L79) to configure the `allowedContent` among many other things.

**Comment by duracell80** [comment]
We have. It seems the issue would keep coming back in different use cases. I would think that re-thinking how this scrubbing is occurring as enforced would resolve future issues not even considered yet. In any case when writing blogs ... you're not really pasting in textual content, you're hopefully creating it. Unless you are plagiarizing someone else's blog entry and if that's the case you'd be citing a piece of text hopefully in a blockquote element.

The only other use case I can see is that the portal times out while you are writing a blog and this may force you as a user to write the entry in Word first and then copy/paste from there ... and in any case "Paste as plain text" is a thing.

**Comment by jbalsas** [comment]
Hey @duracell80, I do agree yeah... I think a less confusing approach might be:
- Hide the source option. As you mention, as a blog writer, you're only writing, and all the styling options are available/allowed options can be accessed from the wysiwyg editor.
- Scrub on pasting using the same rules the editor has configured to prevent extraneous content to be stored.

**Comment by duracell80** [comment]
As ever I appreciate the hard work you guys do.

Scrub on pasting seems to be the exact root issue on this one with cut/paste of an image. 

While editing your blog you may have placed the image and resized it. You now want to move it to a different location in the content, now you have to resize it again (drag handles don't work in IE11 so you'd have to go into source and set a width). Disregarding the fact that drag and drop of an image now doesn't work ... when you cut/paste it (to move the image) pasting it back in removes the size information. It's the paste where the issue is occurring.

There's no distinction being made between trusted content and untrusted content on the action of paste. Hence the suggestion of a "paste from external" modal window so the scrubbing could happen only there and not in the main editor. I don't think the issue could be resolved until that distinction in pasting occurs.

I just think this will pinball around. If you allow style= it would surely regress LPS-51733 and cause large sized hot pink text to be added (which wouldn't be good).

**Comment by duracell80** [comment]
I think the ability to drag/drop an image to move it was lost when drag handles were introduced, however even then drag/dropping the image also caused the width information to be lost.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56942. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/a99f9dd47744~1...a99f9dd47744) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
