### PR TITLE
LPS-90507 Applies Default Event Handler to Management Toolbar Event Handlers

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @patriciajeanperez, could you please monitor this PR and push to Brian if everything looks good?

Both @adolfopa and @ealonso added some additional fixes.

Thanks!

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68158

**Comment by patriciajeanperez** [comment]
Thanks @jbalsas!

**Pull request closed without merging**
