### PR TITLE
LPS-87253 Remove lodash usage from frontend-js-web

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co, can you keep an eye on these test results? This is a high risk PR.

Thanks!

**Comment by john-co** [comment]
@jbalsas, these failures are not related to the code changes.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64986. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
