### PR TITLE
LPS-114055 Replace layout classes with new clay taglibs in site-navigation-admin-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple code replacement, there are 2 important structural changes where we removed some superfluous code
- https://github.com/jbalsas/liferay-portal/pull/2199/files#diff-c25ea9b81bd27b1a429d12dece3f5eb1L102
- https://github.com/jbalsas/liferay-portal/pull/2199/files#diff-29afcb9f88670acce85cf353fd807c32L118

And some cases where we removed the class `autofit-col-end` because we don't have a defined taglib's attribute for it and it resulted unneeded after a deeper examination https://codepen.io/eduardoallegrini/pen/PoZompa?editors=1000
- If we don't use `autofit-float` in the row the `autofit-col-end` in the col won't work https://github.com/liferay/clay/blob/d417c2748b2400c8a516d9d15e79b4e700ba663a/packages/clay-css/src/scss/mixins/_utilities.scss#L12

/cc @marcoscv-work

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/slnn/liferay-portal/pull/482. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Sent to Lily for performance testing while we wait for test results

**Pull request closed without merging**
