### PR TITLE
LPS-102089 Remove compat-button_groups from classic and admin themes

### PR DESCRIPTION
**Pull request by eduardoallegrini**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co, I see a `LocalFile.PortalSmoke#Smoke` test failing here.. can you tell if that one or any other might be related to this PR?

Thanks!

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

The websphere smoke test failure seems to affect other pulls in it's test history.

History:
https://testray.liferay.com/home/-/testray/case_results/868735436/history?delta=200&tab=result&testrayCaseId=863476377&environmentHash=-734174467&hideFilterPin=true&testrayRoutineId=849929038&orderByCol=createDate_sortable&orderByType=desc&resetCur=false&cur=2
`path=(//div | //li)[(contains(@class,'open') or contains(@class,'show')) and (contains(@class,'dropdown') or contains(.//*/@class,'dropdown'))]//*[self::a or self::span or self::button][normalize-space(text())='Public Page']"`

Comparison of other unique test failures:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=868307106&testrayRunIdA=868733336&statusB=2
ContentPageTemplatesWithFragmentConfiguration#AddCheckboxConfigurationFragmentToContentPageTemplate - is flaky
SiteMemberships#OrganizationsView - looks like a fluke on `ci test` run, it passed on `ci test relevant`

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80892. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
