### PR TITLE
LPS-66149

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-66149.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
We can continue our discussion from https://github.com/brianchandotcom/liferay-portal/pull/40759#issuecomment-225935834

**Comment by brunobasto** [comment]
Hey @juliocamarero,

Yeah, I agree with your points. And yeah, the API to translate language keys has gotten more complex as now you need to keep in mind to pass the right bundle resource context to it. This kind of change has to be thoroughly tested and I'm not sure our CI catches localization issues very well.

**Comment by jbalsas** [comment]
Hey guys, I was also under the impression that we won't be doing that anymore and taglibs would expect the translated strings to be passed onto them.

We can rethink the whole `resourceBundle` approach for our taglibs so there's at least some consistency with the old behaviours, but as you guys have already pointed out, it's not straightforward now to resolve the appropriate `ResourceBundle` in every case...

**Pull request closed without merging**
