### PR TITLE
LPS-68581 Ignoring inline height to keep the ratio.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey @jbalsas 

Please help review this pr.

Thanks
John

/cc @blzaugg @jonmak08 @daledotshan

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @jbalsas, @blzaugg @jonmak08 @daledotshan:

Do you have any update about this pull?

Thanks!!!

**Comment by blzaugg** [comment]
This is the most recent status (on an older pull): 
https://github.com/blzaugg/liferay-portal/pull/176#issuecomment-254425918

This may have slipped through the cracks, as to who's working on it. I assumed Chema's team was looking into how to mitigate the issue of max-width.

**Comment by jbalsas** [comment]
Hey @ealonso, @blzaugg, we won't accept this PR. This is the expected behaviour as is, and we're simply working on mitigation strategies on the editor side: https://github.com/liferay/alloy-editor/issues/601

**Comment by ealonso** [comment]
Hey @jbalsas,

Then we should resolve the issue as won't fix? Could you do that and explain the reason?

Thanks!!!

**Pull request closed without merging**
