### PR TITLE
LPS-85918 Portlet Hub does not prefix private render parameters with the portlet namespace

### PR DESCRIPTION
**Pull request by ngriffin7a**
/cc @julien

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
@jbalsas @julien This does not fix the two TCK failures that I mentioned the other day. It is a simply fix that makes the Portlet Hub work when `requires-namespaced-parameters=true` in liferay-portlet.xml

**Comment by julien** [comment]
Hi @ngriffin7a thanks for the heads up.
I was looking at the TCK failures and thought this might help.

**Comment by jbalsas** [comment]
@julien, I'm pushing this forward on @ngriffin7a request. Please, can you add a task for us in the next episode to add some tests to cover this? Thanks!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63677. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
