### PR TITLE
LPS-89151 - Change card horizontal separation in card grid

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:stop

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66971. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
