### PR TITLE
[Mig][Dep] Language

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-61417 and https://issues.liferay.com/browse/LPS-62000.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
This is likely failing due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged please re-run this particular pull request.

Sorry for the inconvenience.

**Comment by jbalsas** [comment]
ci:retest

**Comment by jonmak08** [comment]
rebased since there was merge conflicts with master.

**Comment by jonmak08** [comment]
ci:retest

**Pull request closed without merging**
