### PR TITLE
LPS-85198 The empty string should be considered as an empty list of posssible actions

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @jbalsas,

Can you please have a look at https://github.com/jbalsas/liferay-portal/pull/1457/commits/d794953b45c85849b99767a615a244e6d283d300?

When the list is empty we generate an empty string which evaluates to falsy in js. This makes js defaults to the wildcard and enable all the options.

If you're happy with it please forward to Brian.

Thanks!

**Comment by jbalsas** [comment]
Hey @4lejandrito, I actually agreed on this with @sergiogonzalez... let's talk about it tomorrow! 👍

**Comment by 4lejandrito** [comment]
I think the empty string `''` should mean _there are no available options_ and a value of `null` or `undefined` should mean _use the wildcard_. Otherwise how are we supposed to disable all the options? I could use a comma for instance but that looks dirty.

**Comment by jbalsas** [comment]
Makes sense @4lejandrito, I'll work it out on top of this. Thanks!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/165. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/58761102eb40~1...58761102eb40) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
