### PR TITLE
LPS-99698 fragment - Update this.fetch usage

### PR DESCRIPTION
**Pull request by kresimir-coko**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @kresimir-coko, wouldn't it be easier to just update the `PortletBase.es.js` fetch usage instead?

**Comment by jbalsas** [comment]
We should anyways, so why change its usages?

**Comment by kresimir-coko** [comment]
I didn't investigate this as I assumed it wasn't related to something that needed updating since it was an offhanded comment made by Marko before he left for PTO saying that we should also update `this.fetch` usages as well as `fetch` and `io.request`, since AFAIK `this.fetch` wasn't in the original scope of the Epic

**Comment by jbalsas** [comment]
Got it.

Don't we have something in the epic to update `PortletBase.es.js` global fetch usage? `this.fetch` would be fine as long as they extend from `PortletBase` which is inheriting this. Might not be the best pattern, but it brings some ergonomics to the table, so let's fix it there for all such cases.

**Comment by kresimir-coko** [comment]
Portlet Base isn't mentioned in the epic https://issues.liferay.com/browse/LPS-98283

I'll leave `this.fetch` tasks for now and focus on the others

**Comment by jbalsas** [comment]
> Portlet Base isn't mentioned in the epic https://issues.liferay.com/browse/LPS-98283

Then it was missed during the Epic research/definition phase.

I'll take care of it as part of https://issues.liferay.com/browse/LPS-99339. Just make sure we don't change `PortletBase.prototype.fetch` usages unnecessarily.

**Comment by kresimir-coko** [comment]
Sure, I'll leave those unchanged!

**Pull request closed without merging**
