### PR TITLE
LPS-99130 Removes fontAwesome from Admin

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @jbalsas, looks good to me. Failures are not related to this pull. Exploratory regressions found in https://github.com/john-co/liferay-portal/pull/154 and https://github.com/john-co/liferay-portal/pull/155 have been resolved. :heavy_check_mark:

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @john-co, I was expecting an almost clean test run here since we addressed more issues from last time.

Could you please analyze the results and see if this is still safe or if it's causing any of the issues seen in the test run?

Thanks!

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Hi @jbalsas, It looks like these failures are unrelated based on comparison with upstream results. :heavy_check_mark:

**Comment by jbalsas** [comment]
See LPS-99129

**Pull request closed without merging**
