### PR TITLE
LPS-108270 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-108270

### CODE REVIEW

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

**Comparison Details:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1008972419&testrayRunIdA=1008963513&statusB=2

source-format-jdk8 test fails on same issue in upstream: [full log](https://test-1-9.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/41500/consoleFull)

cc/ @markocikos @izaera

**Comment by izaera** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
Resent with a minor modification as https://github.com/jbalsas/liferay-portal/pull/2140

**Pull request closed without merging**
