### PR TITLE
LPS-79837 Uses shared namespace for validatorTagsMap

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
@jbalsas is this urgent, or can this wait until my Monday? The tests probably won't finish until after I leave today. Also, do you want me to forward the commits to Brian if it looks good?

**Comment by jbalsas** [comment]
It can wait, @jpince, if it finishes and looks good, please push it forward. If you're out by then, I'll take a look monday 👍

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @jpince, based on the current results I think this one is good to go... those 2 missing tests seem unrelated.

Sending to brian!

**Comment by jpince** [comment]
@jbalsas thanks for looking at this & forwarding

**Pull request closed without merging**
