### PR TITLE
LPS-77516 Updates test locators

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @jpince, could you guys help me out figuring out the rest the failing tests?

**Comment by jpince** [comment]
@anthony-chu @austinchiang can you please analyze the test failures?

https://testray.liferay.com/home/-/testray/runs?testrayBuildId=176164555

**Comment by jbalsas** [comment]
Hey @jpince, @anthony-chu, @austinchiang, any update on this? Anything I can do to help see this through?

Thanks!

**Comment by austinchiang** [comment]
Hey @jbalsas, most of these test failures are unrelated and should have been turned. I will double check.

**Comment by austinchiang** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @austinchiang, these two are indeed related to this, but I'm not sure why.

https://testray.liferay.com/reports/production/logs/test-1-23/1517361136551/test-portal-acceptance-pullrequest(master)/684/functional-tomcat80-mysql56-jdk8/1/0/CPRolesPGBlogs_AddBlogsEntryRegRole/index.html.gz

https://testray.liferay.com/reports/production/logs/test-1-23/1517361136551/test-portal-acceptance-pullrequest(master)/684/functional-tomcat80-mysql56-jdk8/2/0/MySites_LeaveSite/index.html.gz

I think both are checking for `ListGroupItem#ITEM_NAME`. Maybe they should use `ListGroupItem#ITEM_LINK` instead?

Could you fix those and send to bchan, please?

Thanks!

**Comment by austinchiang** [comment]
I will take a look. Thanks.

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54968

**Comment by jbalsas** [comment]
Awesome, thanks for figuring that out, I didn't realize those had changed! 👍

**Comment by jpince** [comment]
@jbalsas I'm very thankful for your willingness to understand and make changes to the POSHI code. It is very helpful and appreciated!

**Pull request closed without merging**
