### PR TITLE
LPS-107659 Change default theme from Classic to Chamaeleon

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
There are some issues with semantic versioning. Also I think there's one commit missing. Will resend.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84176. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84235. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/11fcd112ed28~1...11fcd112ed28) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84236. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/78dbde10a708~1...78dbde10a708) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
