### PR TITLE
LPS-60864, LPS-61154

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-60864 and https://issues.liferay.com/browse/LPS-61154.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/313. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/f272a7b~1...f272a7b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33297. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/56f5489~1...56f5489) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @jonmak08, @mjbradford89, I sent this to Brian. Just a couple of comments:

- This was a brand new taglib for 7.0. No need to add deprecation notices or breaking changes :wink: 
- The `Import-Package` declarations are only needed in weird cases where bnd can't resolve the dependencies (due to reflectivity or similar mechanisms). Try first without them and only add them if necessary.
- The `Require-Capability` is automatically calculated by `JSPAnalyzer`, so it's not necessary to do the wiring manually. I removed them in the last commit and it had been already removed from all modules in master prior to me sending this to brian.

Thanks a lot, guys!

**Comment by mjbradford89** [comment]
Hey @jbalsas 
I didn't even realize that it was a brand new taglib, whoops :smile:.  I'll make sure to follow those patterns for the rest of the taglib migrations.  Thanks for the help!

**Comment by jbalsas** [comment]
Hahaha... no problem @mjbradford89! I only knew it was a new taglib because I created it myself a while ago :joy:

**Pull request closed without merging**
