### PR TITLE
LPS-72413 font-awesome should be loaded in a seperate file due to IE9 CSS selector limit

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

In case you have a quick moment to look at this.

This will address the CSS selector limit issue in IE9 by loading font-awesome in a separate CSS file. It's even backwards compatible since all the logic is in the base themes and not tied to anything in Portal, _and_ the rtl conversion still works.

The only issue is that by including it with `@import url()`, none of the query params on the `aui.css` file are passed to it. The result is that Portal aggressively caches it, so once you deploy your theme the first time, there isn't really a way to modify this file.

However, in most cases, no one is going to modify anything in this file. It's pretty static.

Do you think it's a big enough concern to not go through with this fix?

The only idea I have is adding something to the CSS filter in portal that sniffs out these kind of imports, and adds all the same params to the `@import` url, but that sounds like a pain ;)

**Comment by Robert-Frampton** [comment]
Dave Truong and I figured out a workaround for the cache issue. So we should be good.

**Comment by jbalsas** [comment]
Awesome!! 👍

**Comment by jbalsas** [comment]
BTW, @Robert-Frampton, can we close the following IE9 issues now?
- [LPS-72416](https://issues.liferay.com/browse/LPS-72416)
- [LPS-72415](https://issues.liferay.com/browse/LPS-72415)
- [LPS-72412](https://issues.liferay.com/browse/LPS-72412)
- [LPS-72361](https://issues.liferay.com/browse/LPS-72361)

**Comment by Robert-Frampton** [comment]
Hey @jbalsas,

We should be able to, I was waiting until the fix for LPS-72413 was cleared by QA before closing any related issues.

**Comment by jbalsas** [comment]
Awesome, thanks so much!! 🎉🎉🎉

**Pull request closed without merging**
