### PR TITLE
LPS-83241 Remove table column styles, use Clay 2 table helper classes instead

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> ci:test:relevant

Hey @john-co, this was already doing a full `ci:test` run... doesn't that include the `ci:test:relevant` suite?

**Comment by john-co** [comment]
> > ci:test:relevant
> 
> Hey @john-co, this was already doing a full `ci:test` run... doesn't that include the `ci:test:relevant` suite?

@jbalsas, `ci:test` only goes through acceptance tests, `ci:test:relevant` includes the tests on modules that have been affected by the code changes. `relevant` will cover a more extensive suite in this case since the code most likely touches a lot of components.

**Comment by jbalsas** [comment]
Interesting... and counter-intuitive at the same time 😂

Thankd for the clarification!

**Comment by john-co** [comment]
@jpince, can you review unique failures #1 and #2 under ci : test?
test-portal-acceptance-pullrequest-batch(master)/deprecated-module-smoke-jdk8
test-portal-acceptance-pullrequest-batch(master)/functional-smoke-jboss71-mysql57-jdk8/0

**Comment by john-co** [comment]
ci:test:relevant
retesting for LocalFile.WorkflowPageRevision#ViewApprovedPageAfterStagingDeactivated

**Comment by jbalsas** [comment]
Hey, @sergiogonzalez, @austinchiang, @ealonso, @brianchiu, @matethurzo, @kmaria, @drewbrokke, @topolik, @jeyvison, @rafaprax, @alexcandidos, @jpince!

We've worked to update table usage across the portal for a better behaviour under different situations (japanese locale, screen size...). The changes involved are generally small, but we wanted to make them globally to make sure experience stays consistent across Portal. 

We're testing here to make sure nothing breaks before sending it forward. Please, if possible, take a minute to verify that the apps that belong to you are working as expected and let us know if they don't.

If no-one finds any issues, we'd like to send this to Brian by end of day tomorrow.

Thanks!

**Comment by matethurzo** [comment]
looks good thanks @jbalsas

**Comment by rafaprax** [comment]
\\cc @pedroqueiroz

**Comment by jpince** [comment]
@john-co failures in deprecated-module-smoke-jdk8 and smoke-jboss71 are unrelated.

**Comment by john-co** [comment]
@jpince thanks!
@jbalsas the failures in `ci: test` and `relevant` are unrelated. This pull passes automation testing.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchiu** [comment]
@jbalsas 
Looks fine for WEM. There are no WEM-specific functional test failures on the pull, and I also built with those commits and I don't see anything wrong upon a quick check.

cc @jkappler

**Comment by jbalsas** [comment]
Thanks a lot, @matethurzo, @jpince, @john-co, @pedroqueiroz, @brianchiu! Forwarding to brian! 💃

**Pull request closed without merging**
