### PR TITLE
FrontEnd help!

### PR DESCRIPTION
**Pull request by martamedio**
Hey @jbalsas 👋 

We really need your help to include a library to generate a QRCode 😅 
I have not been able to import anything to generate it due to lack of knowledge, you're changing a lot of things at FrontEnd Infrastructure and I'm a bit lost.
 
I would appreciate if, when implementing it, you would add the step-by-step in the commits (for example: _1. add package.json with the dependency, 2. load NPMPackageNames, 3. import it at JSP..._) to helps us learn how to do it in the future with other frontend imports in our modules, so as to avoid bothering you again.

The module where we need your help is `multi-factor-authentication-timebased-otp-web`, we need to print a QRCode at `<div id="<portlet:namespace/>qrcode"></div>` in `setup_timebased_otp.jsp` using the variable `text` as URL for the QRCode. 
At Slack Greg had suggested to me that [this is the best option at the moment](https://github.com/soldair/node-qrcode) to work with QRCodes.

Please let me know if you have any problems with the actual code.
Thank you very much for your help ❤️ , at our next meeting you'll be invited to some drinks 😏 🍸

cc/ @csierra

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @martamedio, I hopefully can get this up and running for you before the end of the day (have some training starting in an hour, so it'll take me a while, though 😢 )

Not sure why I'm getting rebase issues here, though... 🤔

**Comment by martamedio** [comment]
I just realized about the problems of rebasing, probably caused by some translations. You can completely ignore those files, I'll deal with it!

**Comment by jbalsas** [comment]
Hey @martamedio, I honestly have 0 idea how to actually test this.

Could you please add here the necessary steps to reach the app you want and some screenshots of the current state and expected result?

Thanks!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/martamedio/liferay-portal/pull/149. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/e2ffcbfa4536~4...e2ffcbfa4536) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Regardless of this, I've applied the library in `login-web` so you should be able to replicate in your module.

See https://github.com/martamedio/liferay-portal/pull/149 and let me know if something's not clear!

**Pull request closed without merging**
