### PR TITLE
LPS-68979

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @jbalsas,
Can you please try this pull on top of https://github.com/brianchandotcom/liferay-portal/pull/44384?

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44397. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44428. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/c6be04e~1...c6be04e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
