### PR TITLE
LPS-92609 Fix remaining errors in dynamic-data-mapping-form-web tests

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:close

**Comment by jbalsas** [comment]
ci:stop

**Comment by john-co** [comment]
pushed to BChan https://github.com/brianchandotcom/liferay-portal/pull/70189

**Pull request closed without merging**
