### PR TITLE
LPS-100139 + LPS-100144

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
º #

**Comment by julien** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
ci:close

**Comment by carloslancha** [comment]
Resent https://github.com/jbalsas/liferay-portal/pull/1970

**Pull request closed without merging**
