### PR TITLE
LPS-74373 Rebuild TopHeadResources cache as soon as started so that portal.properties is loaded properly from the beginning

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
Curiosamente esto da el mismo error de ayer (un OOM al compilar), asi que descubrimos el error "real" por chiripa.. 😬

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by izaera** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/izaera/liferay-portal/pull/16. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/eab03d1~1...eab03d1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/izaera/liferay-portal/pull/17. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/843b1eb~1...843b1eb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
