### PR TITLE
LPS-45260 Prevent forbidden portlets’ JS and CSS files in page footer

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by izaera** [comment]
@jbalsas This can be a real failure. I need to check.

**Comment by izaera** [comment]
@jbalsas It doesn't seem to be our fault. In fact, it works in local 👍 .

**Comment by izaera** [comment]
I'm going to push force this PR rebased with today's master. Please reget it if you want to test it in local. Thx.

**Comment by izaera** [comment]
Retesting again with rebase

**Comment by izaera** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/5541. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
