### PR TITLE
LPS-114062 - Apply the use of content and sheet clay taglibs in user admin

### PR DESCRIPTION
**Pull request by marcoscv-work**
Hey @jbalsas 

As part of our effort to Improve HTML Layout Generation Strategies in DXP, here a PR about changing `autofit-*` and `sheet-*` for `clay:sheet*` and `clay:content*` in JSPs in account-admin-web.

We have funded out a case currently don't have tag to use to template them:

`<div class="sheet-lg" id="breadcrumb">`

/cc @eduardoallegrini

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@marcoscv-work

Screen Shot 2020-05-25 at 13 22 24

Hope you know what to do...

**Comment by jbalsas** [comment]
Thanks @marcoscv-work, in addition to the explanation, things we're usally looking for in PR descriptions are:
- Steps to test this PR (how to get where the changes are applied)
- Visual indications of what's expected
- Expectations for the review and any additional consideration

**Comment by jbalsas** [comment]
Hey @marcoscv-work, I'm going to forward this, but please, read my comment and remember to add that information for the next PR!

>Thanks @marcoscv-work, in addition to the explanation, things we're usally looking for in PR descriptions are:
>
>Steps to test this PR (how to get where the changes are applied)
>Visual indications of what's expected
>Expectations for the review and any additional consideration

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
