### PR TITLE
LPS-89481 | Add form utilities, with intention to replace jQuery fm plugin

### PR DESCRIPTION
**Pull request by markocikos**
Hi Chema,

I'm opening PR with no changes in the code, apart from fresh rebase, to manually test CI.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test

**Comment by markocikos** [comment]
ci:test

**Comment by markocikos** [comment]
ci:test

**Comment by markocikos** [comment]
ci:test

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@jbalsas I think the PR is safe to review and forward. The CI is failing, but nothing unique to this PR. I tested it manually and was not able to reproduce.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67791. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
