### PR TITLE
LPS-86808 Update lockfile

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Hi @diegonvs, I have tested your PR and I still see that messages are not localized after an `ant all`. It only works when the module "flags-taglib" is deployed separately, as described in the LPS. 
Could you please check this again?

**Comment by jbalsas** [comment]
Keep in mind that this seems to be a build issue, and somehow platform or machine specific. I can never reproduce, while @ambrinchaudhary can always see the problem... CI doesn't seem to be having this issue either afaict...

**Comment by jbalsas** [comment]
@petershin, could you think of a reason why something like this is happening?

**Comment by petershin** [comment]
@jbalsas - I haven't seen this issue before.  I'll do some tests on my end and if I find something will add a comment here

**Comment by jbalsas** [comment]
Thanks @petershin, closing here for now

**Comment by adolfopa** [comment]
@diegonvs  @jbalsas See https://github.com/brianchandotcom/liferay-portal/pull/66564. I've sent this under a different ticket.

**Pull request closed without merging**
