### PR TITLE
LPS-86059 Reset component promises on beforeScreenFlip event

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test-relevant

**Comment by jbalsas** [comment]
hey @john-co, could you take a look at these test results when you have the chance?

Thanks!

**Comment by john-co** [comment]
> hey @john-co, could you take a look at these test results when you have the chance?
> 
> Thanks!

will do.

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
see https://github.com/jbalsas/liferay-portal/pull/1481 for rebased branch testing.

**Comment by jbalsas** [comment]
rebased at https://github.com/jbalsas/liferay-portal/pull/1481

**Pull request closed without merging**
