### PR TITLE
LPS-94712 | The new 'fetch' utility

### PR DESCRIPTION
**Pull request by markocikos**
Hey @jbalsas ,

This PR is missing application of the utility and tests. Before I proceed with those, please see if the pattern of the new utility makes sense.

I opted to write a very thin wrapper on Fetch API, just ensuring `credentails: 'include'`. There are different approaches we can take here, if we want to stay closer to AJAX API of AUI or jQuery: for example adding a callback function param, or having `type` param that determines how we handle response. But, i think it is better we keep it as close to vanilla as possible.

What do you think?

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @markocikos, I'm not sure this will be very ergonomic to use... we should analyze how this is going to be used. Could you analyze current usage to identify what would make for a good API?

My feeling is that most usage would be of the form:

```
fetch(
    url,
    {
        body: data,
        credentials: 'include',
        method: 'GET' | 'POST'
    }
);
```

If so, we could optimize the API for that... @wincent, care to weigh in?

**Comment by wincent** [comment]
I agree that I'd like to see some current usage to get a feel for how we typically use `fetch` in liferay-portal but a couple of thoughts on the PR as it currently stands:

1. I think it would be enough to expose this as `Liferay.Util.fetch()` as opposed to `makeFetch()`; it's already obvious from the fact that its on `Liferay.Util` that this is "our version of `fetch()`", so I don't think we'd need to create more distance by making the name different — this is still pretty much just `fetch()`.
2. As written, I have no way of overriding `credentials` — do we really want to force that? or would we rather supply a reasonably value of `credentials` by default that is used only if the caller doesn't supply one? In other words, why not something like?

```javascript
const DEFAULTS = {
	credentials: 'include',   
};

export default function fetchWithDefaults(resource, init = {}) {
 	return fetch(resource, {
		...DEFAULTS,
		...init,
	});
} 
```

I think there is some merit to keeping the API close to the original `fetch()`, so that developers don't have to learn a whole new API (even if that does mean forgoing the opportunity to make something more ergonomic). ie. I like the idea of keeping this as `fetch()`-but-tailored-for-Liferay. There is always room for putting a higher-level on top of that to abstract away the really common use cases that we might identify.

**Comment by wincent** [comment]
> Util needs to be internally called something other than `fetch`, or we get an endless loop in the implementation.

Right. That's why I called it `fetchWithDefaults` internally.

> we would have an inconsistency in global.es.js

Would we? You can still do:

```javascript
import fetch from './util/fetch.es';

Liferay.Util.fetch = fetch;
```

The "inconsistency" would actually be inside "fetch.es.js", because the default export is a function with a name that doesn't match the file name, but personally I think that's ok: what the function is called internally is an implementation detail, even if it does "leak" out into stack traces (in which case, it will actually be helpful, because if the (native) `fetch()` threw an error you'd see that `fetch()` was called by a method called `fetchWithDefaults()`, which gives you a clearer picture of what is actually happening).

**Comment by markocikos** [comment]
@jbalsas Are you ok with the plan? 
1. We write a thin wrapper utility that includes custom default configuration, `Liferay.Util.fetch()`. In the implementation, it has different default export than function name.
1. In separate ticket(s), we write ergonomic convenience method(s).

Regarding what the convenience methods should be, I really like API of [axios library](https://www.npmjs.com/package/axios). It think it perfectly matches common use cases:
1. get: maybe set params -> get -> do something with response / handle error
1. post: set data -> post -> handle success / error

It is pretty similar to fetch API, but:
1. Defines readable 'get' and 'post' methods
1. Hides awkward middle part of fetch, where we parse returned data to json or text. Instead, we set 'responseType' in initial config.

**Comment by jbalsas** [comment]
Sounds good to me!

**Pull request closed without merging**
