### PR TITLE
LPS-92331 frontend-css-web - Increase form button margin

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey Chema, unsure who to send this small PR, so can you either tell me who to send it to or review it yourself.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @kresimir-coko, please forward this to @eduardoallegrini. In general, send CSS-related PRs either to him or @marcoscv-work.

Thanks!

**Comment by kresimir-coko** [comment]
Done, thanks!

**Comment by jbalsas** [comment]
Hey @kresimir-coko, https://issues.liferay.com/browse/LPS-92331 is still assigned to me and to this PR. Could you please reflect any changes that might've happened there?

In general, if issues are not updated properly, they get stuck somewhere along the workflow because our tools will fail to update them. Please, make sure you update the tickets when you move them from one reviewer to another to make sure they don't remain forever open!

**Comment by kresimir-coko** [comment]
Oh for sure, oversight on my part.

**Pull request closed without merging**
