### PR TITLE
LPS-77517 - Update table list markup

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/995. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
