### PR TITLE
[TECHNICAL-SUPPORT] lps-84351

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @ricky-pan @joshuacords

Notes from Josh and Ricky:

> Issue: @ [LPS-84351](https://issues.liferay.com/browse/LPS-84351)
> Previous PR to 7.0.x: [685](https://github.com/MichaelPrigge/liferay-portal-ee/pull/685)
> 
> This doesn't currently change the behavior in master but removes a potential infinite loop. It should be committed to master to allow for a backport to 7.1.x and 7.0.x where the loop has the potential to be entered.
> 
> Notes from @ricky-pan:
> 
> > This commit fixes an infinite loop within `_onDataReady`, which is fired again before the flag can be reset. The infinite loop is never accessed in master and 7.1.x, but produces a bug in 7.0.x, referenced in [LPS-84351](https://issues.liferay.com/browse/LPS-84351). The fix for the bug will be backported from this change in master. While it does not affect functionality in master or 7.1.x, fixing this function will prevent issues from this function from arising in the future. 
> 
> More details [here](https://github.com/joshuacords/liferay-portal/pull/25#issuecomment-425486047) and [here](https://github.com/MichaelPrigge/liferay-portal-ee/pull/685#issuecomment-425137364).

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Hey @SamZiemer, thanks for sending this over!

I'm currently travelling and a bit behind schedule on this review. I'll make sure to take a look at this asap, or defer to someone in the next days.

Thanks!

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/julien/liferay-portal/pull/59. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
