### PR TITLE
LPS-61735

### PR DESCRIPTION
**Pull request by mikakoivisto**
Hi Chema, seem Nate is on vacation and MHan told me you are dealing with Freemarker stuff so sending this to you instead.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey Mika, @juliocamarero just refactored this. See https://github.com/brianchandotcom/liferay-portal/pull/34027

Would you mind waiting for that?

Thanks!

**Comment by mikakoivisto** [comment]
It doesn’t seem that Julio’s pull touches the same file. This is just proper null value handling in Freemaker and should also be applied everywhere. I just fixed it in the place that blows up the UI for me and also others working with legacy portlets. So I’d appreciate getting it expediently to merged to master. It’s already being broken who knows how long. I ran into it first thing coming back from vacation on Monday.

**Comment by jbalsas** [comment]
Hey Mika, I'd say this is the exact same file Julio touched here https://github.com/brianchandotcom/liferay-portal/pull/34027/files#diff-ee441dbd1c295db444801472032f970fL9, so these changes will surely get overridden.

For proper null handling, would be `#assign valid_portlet_description = portlet_description?has_content && portlet_description?contains("javax.portlet.description")>` equivalent?

Using the default operator to nullify a variable seems a bit weird to me. Is that the usual approach?

**Comment by jbalsas** [comment]
I asked if you mind waiting because it will probably give rebase conflicts with @juliocamarero's pull. Since it failed because of poshi errors, we can forward this to Brian and ask Julio to rebase on top.

**Comment by jbalsas** [comment]
Hey Mika, Julio finally sent another version of his whole PR that removes all those issues (https://github.com/brianchandotcom/liferay-portal/pull/34048/files#diff-ee441dbd1c295db444801472032f970fL1).

If Brian doesn't merge it tonight, we'll push this change upstream first thing in the morning and resend the other one.

Hope that'll work for you.

**Comment by mikakoivisto** [comment]
Thanks. The default operator is a must because in Freemarker following line blows up if portlet_display.getDescription() returns null because you then essentially trying to assign undefined. 

<#assign portlet_description = portlet_display.getDescription()>

**Pull request closed without merging**
