### PR TITLE
LPS-102110 Old AUI component still brings in legacy classes which are the ones we're trying to replace and remove

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co, I think I've addressed yesterday issues... care to review the test results once they're in?

Thanks!

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
pushed to https://github.com/brianchandotcom/liferay-portal/pull/79310

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated.

**Comment by jbalsas** [comment]
rebased and resent to https://github.com/brianchandotcom/liferay-portal/pull/79334

**Pull request closed without merging**
