### PR TITLE
LPS-86108 Update lockfile

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @diegonvs, this is a `-service` module. It doesn't make any sense to have js compilation configuration. It doesn't contain one single line of JS code 😂 

Could you please simply remove the `package.json` and `package-lock.json` files from here and send to the DDM lead to review and forward to Brian?

Thanks!

**Comment by diegonvs** [comment]
But this module compile a soy file, check https://github.com/diegonvs/liferay-portal/blob/6e0e86a7ad88496c78422b08c7634c282521b265/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/resources/META-INF/resources/notification/form_entry_add_body.soy

**Comment by jbalsas** [comment]
Hey @diegonvs, that is true, but the template is [only being rendered in java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/notification/DDMFormEmailNotificationSender.java#L141-L143), so I don't think anyone will be using the `.js` version.

**Comment by diegonvs** [comment]
That's true. I'll remove `js` things 👍

**Pull request closed without merging**
