### PR TITLE
LPS-75190 Mark modified interfaces as Provider to avoid major changes in package versions

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
Ran retest because of push force

**Comment by jbalsas** [comment]
ci:reopen

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Resent as https://github.com/jbalsas/liferay-portal/pull/862

**Pull request closed without merging**
