### PR TITLE
LPS-77051

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-77051.

I added some changes to fix some of the issues described in http://issues.liferay.com/browse/LPS-77051 even though you said you did not want to fix the ticket.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
@john-co, I tried to address some of the issues listed in https://issues.liferay.com/browse/LPS-77051.  Can you check this out to see if this is good and mergeable to give a slightly better UX for the problems?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Thanks @jonmak08, I tested the UX and as you said, it doesn't address all the issues but can be merged for slight improvement. Would want to still keep it as Won't Fix if this is the only movement for 7.2.

**Comment by jonmak08** [comment]
Thanks for testing @john-co!

@jbalsas, thoughts on whether to bring these slight changes and improvements in or not?

**Comment by jbalsas** [comment]
Thanks for sending it over @jonmak08! I thought these had already been merged and closed the ticket to avoid putting any additional effort into this.

Based on release dates, I'll side with @john-co on this and will simply defer this work for a future component to minimize risks for now.

Thanks!

**Pull request closed without merging**
