### PR TITLE
LPS-76586 - Product menu fixes

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by marcoscv-work** [comment]
ci:test

**Comment by marcoscv-work** [comment]
image

**Comment by jpince** [comment]
@marcoscv I talked about this with @jbalsas, @koor4356 is going to look into it. Might not finish today, but definitely this week. Thanks guys!

**Comment by koor4356** [comment]
@marcoscv-work @jbalsas and @jpince, I've sent this pr with the test fixes to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/53963

**Comment by koor4356** [comment]
ci:close

**Comment by jbalsas** [comment]
Awesome, thanks so much @koor4356!!

**Pull request closed without merging**
