### PR TITLE
LPS-70758 Remove unnecessary calls to themeDisplay.isImpersonated (vm)

### PR DESCRIPTION
**Pull request by Robert-Frampton**
Hey @jbalsas 

Originally I thought the variables set in `FTL_liferay.ftl` were available in ADTs/Web Content templates, but that doesn't appear to be true, which means we can take this approach. Doing it this way is backwards compatible in regards to the base themes as well. Let me know if you have any questions.

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, this looks good to me!

The only thing is that we're still missing the `control_menu`, even if that wasn't reported specifically in the issue:

missing_control_menu

I guess we should give [`is_signed_in `](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-template/portal-template-freemarker/src/main/resources/FTL_liferay.ftl#L18) the same treatment? What do you think? Can you apply the same there and send it forward? (if the 👶 is still waiting)

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

I just looked into it, and `is_signed_in` is returning `true`. It's just when impersonating a new user, they won't have permissions to see the elements inside the control menu. I gave admin permissions to my test user, and those items now show up when impersonating that user.

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, makes sense, thanks for double-checking!

Forwarding to Brian!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49047. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
