### PR TITLE
LPS-114087 Replace layout classes with new clay components in site-navigation

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple code replacement applied to the js files. The new Clay layout components are rendering correctly
Screenshot 2020-06-09 at 11 36 39
(`edu` class is used as test)

In the previous pr (https://github.com/eduardoallegrini/liferay-portal/pull/85#discussion_r435308547) I wasn't sure about the changes in the product-navigation-product-menu-web so I tried again and I decided to remove those changes
Screenshot 2020-06-09 at 12 23 17
Screenshot 2020-06-09 at 12 24 42

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:stable

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM! 

Let's wait to see what CI says before forwarding :)

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/89862. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
