### PR TITLE
LPS-104262 Uses mouseup instead of click to avoid messing with other click handlers

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. However, this will need a test fix for tooltip locator. I'll make the test fix and push to BChan.

Explanation of uptick in unique failures:
The unique failures are unrelated. Something recently seems to have slowed down or cause portal to hang on CI. Core team is looking into it.

**Comment by john-co** [comment]
Testing https://github.com/john-co/liferay-portal/pull/196

**Comment by jbalsas** [comment]
Thanks!

**Comment by john-co** [comment]
Pushed to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/80698

**Pull request closed without merging**
