### PR TITLE
LPS-87269 Fix NPE when portal starts

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67947. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/23c6498bb215~1...23c6498bb215) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67948. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/2d5751c8df3d~1...2d5751c8df3d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67998. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/74c458173260~2...74c458173260) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67999. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/be66c8c8602c~2...be66c8c8602c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
