### PR TITLE
LPS-78892 Lexicon patterns adjustments

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @jpince, @alee8888, UX decided they'd like portlet-titles capitalized after all. See https://github.com/jbalsas/liferay-portal/pull/1155/files#diff-9445ef64098a4c302020203bd204234bR10 for the change.

I expect this PR to fail catastrophically... can you guys take care of the tests and push forward?

Thanks!

**Comment by alee8888** [comment]
Reviewing test fix changes here:
https://github.com/alee8888/liferay-portal/pull/548

**Comment by alee8888** [comment]
@jbalsas @marcoscv-work 
Sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/57156

**Pull request closed without merging**
