### PR TITLE
LPS-106466 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/adolfopa/liferay-portal/pull/1197

**Pull request closed without merging**
