### PR TITLE
LPS-78847

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-78847.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @jonmak08, @gregory-bretall, can you explain why removing the `Liferay.Store` call fixes the problem? What was the issue here? Won't that have side effects?

**Comment by jbalsas** [comment]
Why did we add that `store(..., null)` code in the first place is what puzzles me and makes me concerned about removing it.

**Comment by jonmak08** [comment]
Hey @jbalsas and @gregory-bretall,

```Liferay.Store('<portlet:namespace/><%= id %>', null);``` was added with https://github.com/jonmak08/liferay-portal/commit/d67a0856fef5a31a8a333b07f44d4fda4cf47a36#diff-df6137897ed7ccaf40baa205c80642d0.  It was supposed to resolve https://issues.liferay.com/browse/LPS-72007.

@gregory-bretall, can you check whether it's removal from the code will cause https://issues.liferay.com/browse/LPS-72007 again?

**Comment by gregory-bretall** [comment]
Sorry, I should've mentioned it in my original PR, but I already had tested to make sure my change didn't cause a regression of LPS-72007 and confirmed that it did not before sending in the initial fix.

**Comment by jbalsas** [comment]
I think the `users-admin` portlet has changed significantly and might not be affected, but other usages might. Can you try to identify other places where this might still have an impact?

**Comment by gregory-bretall** [comment]
Hi @jbalsas when testing this issue, I was unable to find a spot to replicate the specific circumstances in master but pushed the change through on master anyways because the code is unchanged between it and 7.0.x where I was able to consistently reproduce the issue.

**Comment by jbalsas** [comment]
Should we just revert the whole thing, then?

**Comment by gregory-bretall** [comment]
We can't revert the whole change or else we will cause a regression of LPS-72007. The change I made was the only change that seemed to both resolve the issue and maintain the fixed behavior from LPS-72007

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56434. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
