### PR TITLE
LPS-103828 Update Clay2 packages to 2.18.4 and Clay3 packages to 3.1.x

### PR DESCRIPTION
**Pull request by matuzalemsteles**
hey @jbalsas I updated the Clay3 packages, i didn't change anything in any other module because it's just some fix and nothing big change. You can see it here. https://github.com/liferay/clay/issues/2665

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
@matuzalemsteles, can you please run `ant format-source-all` from `portal-impl`? That should update all usages of clay packages that have been updated to match the new versions and avoid duplicates.

Also, try `npx yarn-deduplicate yarn.lock` before commiting the `yarn.lock` file to ensure we don't have extraneous versions floating around.

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1997. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
I've rebased this and resent to https://github.com/jbalsas/liferay-portal/pull/1997 for testing

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80263. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
