### PR TITLE
LPS-74749 - Recover glyphicons font for compatibility layer

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51707. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/ad8c4ac~1...ad8c4ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51708. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/eaa8bdd~1...eaa8bdd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51734. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/95bf003~1...95bf003) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51771. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/6e1053c~3...6e1053c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
