### PR TITLE
LPS-58035 Avoid escaping link URL

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31171. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/79982ed~1...79982ed) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
