### PR TITLE
[TECHNICAL-SUPPORT] LPS-74432

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @SpencerWoo

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey guys, I'm going to go ahead and send this forward, but this should *not be backported*. There is very little gain in this change an a high risk of regression, so this should be master-only.

/cc @antonio-ortega

**Comment by jbalsas** [comment]
Also, before pushing it forward, could either of you confirm if this [usage inside `move_boxes/page.](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/input_move_boxes/page.jsp#L93-L94) needs to be updated?

Thanks!

**Comment by SpencerWoo** [comment]
Hi @jbalsas I just confirmed that [move_boxes/page](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/input_move_boxes/page.jsp#L93-L94) _does_ need to be updated.  MOVE_LEFT and MOVE_RIGHT should have leftTitle and rightTitle switched.

Also noted on not backporting this.

**Comment by jbalsas** [comment]
Could you apply that change and resend it, please?

Thanks!

**Pull request closed without merging**
