### PR TITLE
LPS-100836 Regens lock file

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
Hey @john-co. Can you follow this PR and if you find everything is correct forward it to Brian? It is supposed to fix the error we had to revert last day...

Thx :-)

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by john-co** [comment]
Just started analyzing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
There's a lot of yarn issues muddying the tests but they're not related to the pull. Will forward to BChan.

**Comment by john-co** [comment]
pushed to https://github.com/brianchandotcom/liferay-portal/pull/78587

**Pull request closed without merging**
