### PR TITLE
LPS-107869 Update CKEditor to latest version (v4.13.1)

### PR DESCRIPTION
**Pull request by markocikos**
Hey @jbalsas ,

Please review the change.

Thank you!

/cc @julien

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @markocikos! I wonder how did you test this... without the `yarn.lock` file changing, did you ensure you were getting a new version of CKEditor? 

I would expect to see something like this:

```diff
Chema-Balsas:modules jose.balsas$ git diff
diff --git a/modules/yarn.lock b/modules/yarn.lock
index cba833ecfe4e..25ea936ca000 100644
--- a/modules/yarn.lock
+++ b/modules/yarn.lock
@@ -11025,10 +11025,10 @@ liferay-amd-loader@4.2.0:
   resolved "https://registry.yarnpkg.com/liferay-amd-loader/-/liferay-amd-loader-4.2.0.tgz#c166fa3723a7cf760deefb8e580d8892c6bf436b"
   integrity sha512-q+b2oU6zy6gDe6uKqHPY2/L9eUjhZAVatCAC5HNrHd+tMIk+MDBSCiHmRvihoJnmPylT+RZ4gNvWxtVwIQBF/Q==
 
-liferay-ckeditor@4.11.4-liferay.2:
-  version "4.11.4-liferay.2"
-  resolved "https://registry.yarnpkg.com/liferay-ckeditor/-/liferay-ckeditor-4.11.4-liferay.2.tgz#e76302c2ba1775121f47dd6477c9bcdfa8cb0657"
-  integrity sha512-M1XuKtSkuyh4rVXFS7usZmqE+sFe/tASLGpOSPa04WWTJfTDLl92Chj8qRvRLKoWeM85umgO51yhhSVd4IZgGQ==
+liferay-ckeditor@4.13.1-liferay.1:
+  version "4.13.1-liferay.1"
+  resolved "https://registry.yarnpkg.com/liferay-ckeditor/-/liferay-ckeditor-4.13.1-liferay.1.tgz#d2b9f865ac6553383c40c2a90561203b39329e59"
+  integrity sha512-TGgkYzkqBQukPClNJIMp4p+3PiETaGc8qVlqsVXQ2dWjFEuLuwBAxmF4+jlCsor6gXAkiYDkeRxCB749ZE+zKQ==
```

I can send on my own, but not knowing if this has been tested makes we worry a bit :)

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/markocikos/liferay-portal/pull/177. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/1255e06b03e9~1...1255e06b03e9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Please, test https://github.com/markocikos/liferay-portal/pull/177 and send to Brian if all is well

**Comment by markocikos** [comment]
> Hey @markocikos! I wonder how did you test this... without the `yarn.lock` file changing, did you ensure you were getting a new version of CKEditor?
> 
> I would expect to see something like this:
> 
> I can send on my own, but not knowing if this has been tested makes we worry a bit :)

Right, the generated bits. I did have them on testing, just forgot to add to PR. Sorry! 

I made sure that I was testing proper version by checking `CKEDITOR.version` in dev tools.

**Comment by jbalsas** [comment]
Forward it to Brian then! 👍

**Pull request closed without merging**
