### PR TITLE
LPS-107870 Fix z-index calculation after TinyMCE update

### PR DESCRIPTION
**Pull request by markocikos**
Hey @jbalsas 

I was looking at open issues related to TinyMCE and stumbled upon a bug related to upgrade. To reproduce, try to add an image by selecting one from document library. The bug is that z-index can no longer be acceded through editor API, we need to do it directly.

The other change in this PR is the increase of default height to 400. Without it, default height is set to 200px, which is too small with bigger toolbar in the new version. This can be a temporary solution, if we wish to reduce size of toolbar icons, but this is [not simple](https://github.com/tinymce/tinymce/issues/4777#issuecomment-552032353). 

Please review the code.

Thank you!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @markocikos, looks good to me, but there are formatting errors. Could you please address those and send to Brian?

Thanks!

**Comment by wincent** [comment]
Just reflecting here what I said in Slack, I suspect the reason why `gradle formatSource` didn't fix the SF problem when run inside `modules/apps/frontend-editor/frontend-editor-tinymce-web` is because that project doesn't have a `package.json` file and so `liferay-npm-scripts fix` never got run by the Java source formatter ([source](https://github.com/liferay/liferay-portal/blob/8e3eb3040123d4bec5990098c48d9194bdec18eb/modules/sdk/gradle-plugins/src/main/java/com/liferay/gradle/plugins/LiferayYarnPlugin.java#L156-L174)).

We might consider adding a simple `package.json` file to projects like this so as to avoid this kind of thing in the future.

**Comment by jbalsas** [comment]
Yeah, I considered moving the build from webjars-based to npm-based as the rest of them, but thought it would complicate the upgrade... I'll take note of this for the future

**Pull request closed without merging**
