### PR TITLE
LPS-85062 Replace language keys by their value in npm modules

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
hey @vicnate5, I'm going to re-run tests here one more time... could you analyze what's going on here, please?

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @vicnate5, do you think this is safe to push to brian?

**Comment by jbalsas** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/64532

**Pull request closed without merging**
