### PR TITLE
LPS-114058 Replace layout classes with new clay taglibs in staging-processes-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple code replacement, we don't expect to see any difference between the old code `<div class="sheet sheet-lg">` and the new one `<clay:sheet>`.

https://github.com/liferay/clay/blob/6244ab8aa35059cc681ead2c1530e6fe320eed2d/packages/clay-layout/src/Sheet.tsx#L81
https://github.com/liferay/clay/blob/6244ab8aa35059cc681ead2c1530e6fe320eed2d/packages/clay-layout/src/Content.tsx#L34

With `cssClass` instead of `className` https://github.com/brianchandotcom/liferay-portal/pull/89369/commits/532c1d8ba3610569df11056282b3392c4d79678e

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
ci:test:stable

**Comment by jbalsas** [comment]
Looks good, @eduardoallegrini! Based on the [SF error](https://github.com/jbalsas/liferay-portal/pull/2192#issuecomment-635914813), one tag is missing the import declarations.

Could you please:
- Rebase this PR
- Address the failing module
- Stack your work today on top so I can get one at the end of the day

Thanks!! 🤗

**Comment by eduardoallegrini** [comment]
https://github.com/jbalsas/liferay-portal/pull/2194

**Pull request closed without merging**
