### PR TITLE
LPS-101241 Remove remaining aui-io-request declarations

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
I tried reproducing the 1st unique error with 

```sh
ant -f build-test.xml run-selenium-test -Dtest.class="Forms#PreviewAndPublishForm"
``` 

Which did also fail locally, but with this error 

```
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.Forms#PreviewAndPublishForm] STANDARD_ERROR
     [exec]     [1568130088,448][SEVERE]: Unable to retrieve document state unexpected alert open
     [exec] 

```

/cc @john-co could you please have a look at this when you have time, to help me understand the error (I think the two other "unique" failures aren't related to theses changes)

**Comment by john-co** [comment]
Just started analyzing :)

**Comment by john-co** [comment]
Hi @julien, the failure looks unrelated. The Forms#PreviewAndPublishForm test looks flakey ~1-2% and the error matches with the other times it was a fluke.

**Comment by julien** [comment]
@john-co , thanks for the analysis and help.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78221. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78222. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/e5d9311797e2~1...e5d9311797e2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
