### PR TITLE
metal-cli removal for frontend-image-editor modules

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Nice find on the API module, the rest of the modules were easy to migrate over.

Also, I just realized there is another npmbundler preset called `liferay-npm-bundler-preset-liferay-standard` should we be using that instead of `liferay-npm-bundler-preset-liferay-dev`?

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65530. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
> Nice find on the API module, the rest of the modules were easy to migrate over.
> 
> Also, I just realized there is another npmbundler preset called `liferay-npm-bundler-preset-liferay-standard` should we be using that instead of `liferay-npm-bundler-preset-liferay-dev`?

@bryceosterhaus `liferay-npm-bundler-preset-liferay-dev` is based on `liferay-npm-bundler-preset-liferay-standard` - you can actually see it [here](https://github.com/julien/liferay-npm-bundler-preset-liferay-dev) if anything needs to be changed don't hesitate to send a pull request or file an issue.
 Thanks

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65531. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/482995547520~1...482995547520) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
