### PR TITLE
LPS-71967

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
Yeah, I have no idea how to "Gradle". This is the idea though.

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ithildir/liferay-portal/pull/723. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/64ff473~3...64ff473) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ithildir/liferay-portal/pull/724. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/6badd05~3...6badd05) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
