### PR TITLE
LPS-104384 Removes compat soy-based exports to improve load performance

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Possible test fix: path locator Treeview#NODE_SELECTED 
`Element is not present at "//div[contains(@class,'treeview-node-main') and contains(@class,'selected')]/div[contains(@class,'card-horizontal')]/div/div[2]/span[contains(.,'Test Page Name 1')]"`
NavigationMenus#AddNavigationMenuEntriesAllTypes
NavigationMenuWidget#EditNavigationMenuPageItemName
NavigationMenus#ViewSuccessMessageAfterAddingMenuItem

This PR seems to increase the lfr loading occurrences but I'm not able to reproduce locally. I'm guessing these would be resolved by https://github.com/jbalsas/liferay-portal/pull/2022

**Comment by john-co** [comment]
Created https://issues.liferay.com/browse/LRQA-53505 to include test fix.

Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=865574706&testrayRunIdA=866214261&statusB=2

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Sent to brian -> https://github.com/brianchandotcom/liferay-portal/pull/80800

**Pull request closed without merging**
