### PR TITLE
LPS-108270 Remove AUI from portal (episode 1)

### PR DESCRIPTION
**Pull request by izaera**
@jbalsas This is the PR that creates two control panel settings to enable AUI core and/or most used modules preload in the portal.

It is now working with both settings allowed but as soon as one is disabled we get a lot of console errors (even if we only disable AUI preload).

@markocikos proposes to send this PR for merge (with any change you see it needs) and then keep working on fixes in further PRs, given that nothing breaks unless someone disables AUI.

This comes from [this other pull](https://github.com/izaera/liferay-portal/pull/126).

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Mmm... tests here don't look so good... @john-co, would you mind taking a look?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Hi @jbalsas, @izaera

A lot of the tests fail when it tries to check for a js script `menu_toggle.js` 
Error output:
`java.lang.Exception: Element is not present at "//script[contains(@src,'/o/frontend-js-web/liferay/menu_toggle.js')]"`

Was it intentional to remove or not trigger the menu_toggle.js script?

Based on [LRQA-22289](https://issues.liferay.com/browse/LRQA-22289:) the waitForMenuToggleJSClick seems like it was intended to wait for the ellipsis to fully render the menu dropdown items. The script was present on every page of liferay portal, but in this PR it can't be found anymore.

**Expecting script:**
image

**Comment by john-co** [comment]
Separately, I noticed an opportunity to improve stability as test fix on QA side. It looks like the waitForMenuToggleJSClick was used to try to stabilize clicking on the Lexicon Cards in [LRQA-54839](https://issues.liferay.com/browse/LRQA-54839). Because of this, that's why many other tests are failing since they rely on adding a page.

I think a better fix to stabilize would be something like MetalComponent.waitForCard(card = "${pageTemplateName}"); which waits for the card to render. 

image

/cc @liulukiwi @david-gutierrez-mesa

**Comment by john-co** [comment]
**Comparison details:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1007856464&testrayRunIdA=1007849876&statusB=2

**Comment by jbalsas** [comment]
Hey @markocikos, can you take a look at what @john-co points out?

@izaera, I was expecting this to be in `System Settings > Third Party` rather than in `System Settings > Infrastructure`. I think I understand your rationale to put it there, but I'd rather keep it consistent with the rest of libraries we've allowed to include. Could you please move the setting into the `Third Party` group so it matches `jQuery` and `Lodash`?

Thanks!

**Comment by markocikos** [comment]
> A lot of the tests fail when it tries to check for a js script `menu_toggle.js`
> Error output:
> `java.lang.Exception: Element is not present at "//script[contains(@src,'/o/frontend-js-web/liferay/menu_toggle.js')]"`
> 
> Based on [LRQA-22289](https://issues.liferay.com/browse/LRQA-22289:) the waitForMenuToggleJSClick seems like it was intended to wait for the ellipsis to fully render the menu dropdown items. The script was present on every page of liferay portal, but in this PR it can't be found anymore.
> 
> Was it intentional to remove or not trigger the menu_toggle.js script? If intentional, is there maybe an alternative script that the test can wait for ellipsis dropdown menus to render?

Hey @john-co ,

This PR changes the path to AUI js files: it used to be `/o/frontend-js-web/`, now it is `/o/frontend-js-aui-web/`. CI tests are failing because they are looking on the old path:
- old: `//script[contains(@src, '/o/frontend-js-web/liferay/menu_toggle.js')]`
- new: `//script[contains(@src, '/o/frontend-js-aui-web/liferay/menu_toggle.js')]`

CI tests should be updated, after or parallel with this PR (+Ivan's changes). I am not sure what is the workflow in these kind of cases.

/cc @jbalsas @izaera

**Comment by john-co** [comment]
Thanks for clarifying that @markocikos! I will add the test fix commit from this PR and push to @jbalsas to rerun ci tests.

cc/ @izaera

**Comment by john-co** [comment]
Pushed to https://github.com/jbalsas/liferay-portal/pull/2139

**Comment by izaera** [comment]
I'm closing this as it has been resent with changes on top

**Pull request closed without merging**
