### PR TITLE
LPS-95564 Remove unnecessary `z-index` property on `lfr-portlet-title-editable`

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80798. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/8ef5bd68bd0d~1...8ef5bd68bd0d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80801. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/3f1be4081537~1...3f1be4081537) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
