### PR TITLE
LPS-96099 Fix aui:script tag generates wrong module dependencies

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by izaera** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @john-co, could you please review these test results? Trying to start pushing this out now that SP1 is done

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Hi @jbalsas, 

This unit-jdk8 test failure looks related:

```
    [junit] Testcase: testGenerateVariableStripsInvalidCharacters(com.liferay.portal.kernel.servlet.taglib.aui.ScriptDataTest):	FAILED
    [junit] var1 was not found
    [junit] junit.framework.AssertionFailedError: var1 was not found
    [junit] 	at com.liferay.portal.kernel.servlet.taglib.aui.ScriptDataTest.assertVariables(ScriptDataTest.java:89)
    [junit] 	at com.liferay.portal.kernel.servlet.taglib.aui.ScriptDataTest.testGenerateVariableStripsInvalidCharacters(ScriptDataTest.java:61)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.kernel.servlet.taglib.aui.ScriptDataTest FAILED
```
Functional test failures are unrelated.

**Comment by izaera** [comment]
ci:test

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79388. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
