### PR TITLE
LPS-104445 - Fix navigation in IE11

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
IMG_2662

**Comment by jbalsas** [comment]
Hey @holatuwol, @SamZiemer, can you please verify if this approach also fixes the issue or if there's some edge case that we might've overlooked?

Thanks!

**Comment by holatuwol** [comment]
@jbalsas, @marcoscv-work : The concept works, but we need the changes in a portlet .css, because adding changes to base themes when our target is a past release adds complications to the fix delivery process.

**Comment by jbalsas** [comment]
Closed in favour of https://github.com/jbalsas/liferay-portal/pull/2045

**Pull request closed without merging**
