### PR TITLE
LPS-94609 Personal Data Erasure: Selection toolbar persist even after navigating to a new page

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-94609](https://issues.liferay.com/browse/LPS-94609).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey @jbalsas, this is to ensure that the management toolbar keeps track of selection across pagination.

**Comment by jbalsas** [comment]
Hey @drewbrokke, this looks quite interesting!! I was thinking that maybe we could roll out this in general into the `ManagementToolbarTag` component, so that we could do a similar thing for other components and avoid having to handle this client-side...

We could by default add the request params already identified as "context-changers" to keep the backwards compatibility and the responsibility out of the calling code... what do you think?

I'll give this a try today or tomorrow to see if I can find the time to implement it. If not, I'll just push this forward and take note of this brilliant idea we had together 😉

**Comment by drewbrokke** [comment]
Hey @jbalsas, that sounds good to me :)  A couple of clarifying questions:
1. Taking this particular use-case as an example, if we rolled this util into the ManagementToolbarTag, would I then need to still manually re-create the effect in my SearchContainer component?
2. Given that there are some default "context-changers", will I have a way to identify some additional parameters that should fulfill that role for just my app?

**Comment by jbalsas** [comment]
Hey @drewbrokke, what I was thinking was to just add support for an API to provide your "context-changers" so that'd be the only thing you'd need.

Your question, however, made me remember something that's already available and used and that I briefly mentioned the other day but failed to click in connection to this.

The `RowChecker` that's assigned to the `SearchContainer` already has a `rememberCheckBoxStateURLRegex` property that you can set to identify when the searchcontainer selection should be kept. This is integrated in the MT already via the aforementioned [`isCacheable(uri)`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/ManagementToolbar.es.js#L85-L95) API, so that might be all you need to get this going safely :)

See how other apps were already using this in previous versions to keep selection throughout navigation:
- [setRememberCheckBoxStateURLRegex](https://github.com/liferay/liferay-portal/search?q=setRememberCheckBoxStateURLRegex&unscoped_q=setRememberCheckBoxStateURLRegex)
- [getRememberCheckBoxStateURLRegex](https://github.com/liferay/liferay-portal/search?q=getRememberCheckBoxStateURLRegex&unscoped_q=getRememberCheckBoxStateURLRegex)

It should be enough to create a "regex" that contains the currently specified search params (context-changers) so that changing them wouldn't match and the state won't be preserved.

**Pull request closed without merging**
