### PR TITLE
LPS-XXXXX Uses jest for tests

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @kenjiheigel, I'm testing a new testing approach here, and the `junit` reporter is spitting out a different xml.

```xml
<testsuites name="">
  <testsuite name="PortletBase" tests="10" errors="0" failures="0" skipped="0" timestamp="2017-08-30T16:44:16" time="0.301">
    <testcase classname="PortletBase PortletBase.all" name="should return an empty list if no elements are found" time="0.016">
    </testcase>
    <testcase classname="PortletBase PortletBase.all" name="should get all matching nodes within the root node tree" time="0.003">
    </testcase>
    <testcase classname="PortletBase PortletBase.all" name="should use the document as root node if one has not been specified or the default has not been found" time="0.001">
    </testcase>
    <testcase classname="PortletBase PortletBase.ns" name="should namespace objects with the portlet namespace using the provided Liferay.Util.ns helper" time="0.001">
    </testcase>
    <testcase classname="PortletBase PortletBase.one" name="should return null if no element is found" time="0.001">
    </testcase>
    <testcase classname="PortletBase PortletBase.one" name="should get the first matching node within the root node tree" time="0.001">
    </testcase>
    <testcase classname="PortletBase PortletBase.one" name="should use the document as root node if one has not been specified or the default has not been found" time="0.001">
    </testcase>
    <testcase classname="PortletBase PortletBase.rootNode" name="should set the root node by default" time="0">
    </testcase>
    <testcase classname="PortletBase PortletBase.rootNode" name="should use a specified root node" time="0.001">
    </testcase>
    <testcase classname="PortletBase PortletBase.rootNode" name="should override the default root node if specified" time="0">
    </testcase>
  </testsuite>
  <testsuite name="CompatibilityEventProxy" tests="10" errors="0" failures="0" skipped="0" timestamp="2017-08-30T16:44:16" time="0.05">
    <testcase classname="CompatibilityEventProxy" name="should not emit any event when no targets have been added" time="0.003">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should not crash if target has no method fire" time="0.001">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should emit adapted event with event name and event params to given targets when no namespace is specified" time="0.001">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should emit adapted event with event name and event params to given targets when namespace is specified" time="0.001">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should emit adapted event to given targets when target is not listening" time="0">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should emit adapted event to given targets when target is listening" time="0">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should maintain target original state of emitFacade after emiting events" time="0.001">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should maintain target original state of emitFacade after emiting events when component emitFacade is true" time="0">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should adapt the events according to specified RegExp" time="0.001">
    </testcase>
    <testcase classname="CompatibilityEventProxy" name="should emit events even if the event does not have a key property" time="0">
    </testcase>
  </testsuite>
</testsuites>
```

When I check in Travis, I don't see the test results... Do we need to keep the old xml format? If so, we'll need to build our own reporter. Maybe there's something in the CI that we need to adapt?

**Comment by kenjiheigel** [comment]
@jbalsas, the [junitreport](https://ant.apache.org/manual/Tasks/junitreport.html) task that we use to consolidate junit XML's doesn't support `testsuites` elements. Last time we got around it by https://github.com/liferay/liferay-portal/blob/master/build-test-batch.xml#L2592-L2599. Basically `<testsuites name="">` doesn't match the replace filter. The tests are running on CI, but the failure message is `[junitreport] [Fatal Error] TEST-frontend-js.xml:46:1: XML document structures must start and end within the same entity.` Will send a pull if I get a chance, but you could implement ANT fix and send to QA Engineering if anything. I'm at Jenkins World right now, and will be on EVP and vacation for two weeks, but that should at least give you direction towards how to fix it.

**Comment by kenjiheigel** [comment]
@jbalsas, sounds good! You can test your newly generated junit XML files on portal by running `ant -f build-test.xml merge-test-results` It will find files matching the pattern in the link below and will denote files that it finds and consolidated for jenkins. 

Also for file name generation, as long as you follow [these criteria,](https://github.com/liferay/liferay-portal/blob/644b19c/build-test.xml#L6120-L6138) you should be good to go. If you have any issues you can ask anyone from QA Engineering.

**Comment by jbalsas** [comment]
Resent as https://github.com/jbalsas/liferay-portal/pull/812

**Pull request closed without merging**
