### PR TITLE
LPP-31556

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPP-31556.

> On iPhones, the view will not scroll to the editor when selecting reply in Message Boards. This is due to the fact iOS does not do autofocus unlike in Android or Desktop.

> A solution to this is to create a method that will scroll the screen to the desired location when it detects an iOS device. This method is not needed for Android or Desktop since autofocus functions correctly. With this method, we are keeping the native behavior of iOS by not focusing the editor but we are making it user friendly by displaying the editor.

> @fortunatomaldonado 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @jonmak08, @fortunatomaldonado, this looks good. I think we still need to:
- Avoid using AUI for this. Specially since we're simply querying the DOM.
- Apply this to the rest of editors too (`tinymce`, `tinymce_simple` and `simple`)

Could you please take a look at those and resend?

Thanks!

**Comment by jonmak08** [comment]
Hey @jbalsas,

That was my questions was whether we want to just do this for the message boards or add the API for the editor.  I will just call it directly in the message boards then.

Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/64512

**Pull request closed without merging**
