### PR TITLE
LPS-87735 Pass mimeType param properly to the component and normalize it to supported canvas mimetypes

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @arthurchan35, could you please double check this before I sent it forward?

### CODE REVIEW

**Comment by arthurchan35** [comment]
Hi @jbalsas 
I have tested the code, it seems to work fine.
Just wonder, do we still need the normalize function?

**Comment by jbalsas** [comment]
Hey @arthurchan35, did you see the comment on the normalize function? It might be outdated in current browsers, but [`toDataURL` only supports some mime types](https://kangax.github.io/jstests/toDataUrl_mime_type_test/). 

The normalize function makes sure that we don't turn `jpg` into `png` because it's not a supported mime type.

You can test on different browsers to see to what type a specific input type will be converted to. So far, I rechecked Chrome, Firefox and Safari and none of them will properly encode `image/jpg`, which is the reason why we normalize it to `image/jpeg`.

Please, let me know if that makes sense and I'll push this forward.

Thanks!

**Comment by arthurchan35** [comment]
Hi @jbalsas

Thanks for the explanation, let's move it forward!

I had only be able to test the behavior today, I was previously thinking if we send mime type from server to client, the mime type will always be consistent ie image/jpeg


Thanks for your work again!

**Comment by jbalsas** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/65446

**Pull request closed without merging**
