### PR TITLE
LPS-97224 Bump Clay 2.x versions

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
Hey @alexancandidos, could you take a look on this?

**Comment by alexcandidos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alexcandidos** [comment]
Hey @diegonvs , as we discussed, I'll validate it once it is merged on the master. I've added Forms in the component of the ticket so it will fall in our boards when ready to validate (in resolved status).

**Comment by jbalsas** [comment]
Hey @diegonvs, take a look at the changes here. As you can see, we're doubling the size of the `yarn.lock` file because we're now downloading 2 different versions of everything.

This should've been caught by SF, but @hhuijser will take a look to figure out why it didn't.

We need to increase all versions in all `package.json` files to match the new clay versions. You'd know it's done right because the `yarn.lock` file has only one version of the clay components and not more than one.

Can you please do that and resend?

Thanks!

**Comment by diegonvs** [comment]
> Hey @diegonvs, take a look at the changes here. As you can see, we're doubling the size of the `yarn.lock` file because we're now downloading 2 different versions of everything.
> 
> This should've been caught by SF, but @hhuijser will take a look to figure out why it didn't.
> 
> We need to increase all versions in all `package.json` files to match the new clay versions. You'd know it's done right because the `yarn.lock` file has only one version of the clay components and not more than one.
> 
> Can you please do that and resend?
> 
> Thanks!

Sure!

**Comment by diegonvs** [comment]
Resent at https://github.com/jbalsas/liferay-portal/pull/1815

**Pull request closed without merging**
