### PR TITLE
LPS-79566 Generic success messages should not appear embedded

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @anthony-chu, @brianchiu, @jpince, can you help me decipher the errors we're having now? 🙏 

Where should I look to fix stuff? On manual inspection everything's looking good, but maybe I'm missing someplace?

**Comment by jbalsas** [comment]
ci:retest

**Comment by anthony-chu** [comment]
hi @jbalsas, on initial inspection, it looks like there are some additional test fixes that need to be made. i think also some of the failures were fixed by https://github.com/brianchandotcom/liferay-portal/pull/58746, where deleting virtual instances threw exceptions. i can take a further look into this pull today.

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @anthony-chu, @jpince, I've moved the modal buttons to the right (as expected by Lexicon). Looks like we still need test fixes, but everything seems to be working fine on my end.

We need to push this through asap. We can't be fixing just one issue at a time for days. Could you guys please figure out what's missing overall and either push to Brian or let me know so I can get try to fix all that's needed?

**Comment by anthony-chu** [comment]
hi @chema, thanks for the quick fix. i've made additional changes on my branch. i hope to be able to send the branch to Brian after making the necessary fixes for these changes.

**Comment by brianchiu** [comment]
This is being tested here: https://github.com/anthony-chu/liferay-portal/pull/483

**Pull request closed without merging**
