### PR TITLE
LPS-84472 Cannot create document if both Overall Maximum Upload Request Size and Maximum File Size are set to 0

### PR DESCRIPTION
**Pull request by IstvanD**
Hello @jbalsas 

I saw that https://github.com/jbalsas/liferay-portal/pull/1421 caused a regression, for which I'm really sorry.
I corrected the fix so that I still retains the client side `required` and other types of verification.

Could you please check it?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Reopenig as the failed tests are not related to the fix.

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63190. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Thank you for forwarding it, @jbalsas

**Pull request closed without merging**
