### PR TITLE
LPS-89705

### PR DESCRIPTION
**Pull request by jcampoy**
Always apply the default language and available languages of the groupId in where the content is created (/cc @ealonso) , also it is applied to ddl /cc @jeyvison, and documents and media /cc @adolfopa.

### CODE REVIEW

**Comment by jcampoy** [comment]
resent here https://github.com/jbalsas/liferay-portal/pull/1745

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/301. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
