### PR TITLE
LPS-70451

### PR DESCRIPTION
**Pull request by Ithildir**
Hi Chema!

Brian asked me to remove as many 3rd-party zips as possible, and use Gradle instead. Can you please review these changes and see if they're okay?

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @Ithildir, are the errors real? should I just reopen, or can you resend?

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Hi @jbalsas! I think that was a problem with the proxy, not related to this pull..

**Comment by Ithildir** [comment]
ci:retest

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46832. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
