### PR TITLE
LPS-107291

### PR DESCRIPTION
**Pull request by topolik**
Hi Chema, 

can you please review my changes? Especially I'm not sure about `Liferay.Util.escapeHTML` here: https://github.com/jbalsas/liferay-portal/pull/2095/commits/9142aedc21640886c781f6abb28260850567ffd2#diff-924c906a51996b62f1d66b9a383db233R42

https://issues.liferay.com/browse/LPS-107291

Thank you.

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by jbalsas** [comment]
Thanks @topolik!

/cc @4lejandrito, can you guys validate this does not regresses back to the issue we introduced in the past?

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Looks good guys, go ahead!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83583. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
