### PR TITLE
ThemeContributor

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Chema,

Attached is the ThemeContributorExtender without any verification of its' type.  So any bundle with Theme-Contributor-Type set in the manifest (or package.json) will be treated as a theme contributor.

Let me know if you want me to create a ticket for this, I'm just not sure if it should be a story, feature request, etc..

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by jbalsas** [comment]
Reviewed PR https://github.com/jbalsas/liferay-portal/pull/365

@mjbradford89, see the changes there.

Thanks a lot @csierra!

**Comment by mjbradford89** [comment]
@jbalsas, It all looks good to me.  @csierra improved it a lot :sweat_smile: 

Thanks guys!

**Comment by csierra** [comment]
hey @mjbradford89... thanks for your kind words :smile: 

but you did all the hard work... I just tuned some knobs here and there...

**Pull request closed without merging**
