### PR TITLE
LPS-46256

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-46256.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @jonmak08, @ckorbel, do you have something more to go on on this? Why is the button confusing? Do we remove existing functionality by getting rid of it?

**Comment by jonmak08** [comment]
Hey @jbalsas,

It was a ticket @blzaugg created, but in looking at tit, the ```Code``` button just formats the code to use a formatted style and the ```<pre />``` tags, it was causing buggy behavior in the source view.

If you wanted to input code, I think you would manually go to the ```Source``` mode of CKEditor and wrap everything in ```[code]``` yourself.

**Comment by jbalsas** [comment]
I see, thanks for the explanation! I'll push this forward today!

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56546. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
