### PR TITLE
LPS-79222

### PR DESCRIPTION
**Pull request by petershin**
Hi Chema!

Can you check if the new `transpileJS` task generates the correct output?

It combines `transpileJS` and `configJSModules` into one single task.

@Ithildir

### CODE REVIEW

**Comment by jbalsas** [comment]
Hi peter! Sorry I didn't have time to take a look... could you fix the conflicts and resend? I'll take a look first thing tomorrow!

**Comment by petershin** [comment]
Yup, rebased with the latest in master

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @petershin, this is showing 

```
     [exec] > Could not find method configJSModules() for arguments [build_c7o97npqqdaa17hys22duzu8w$_run_closure2@f0c27b8] on project ':apps:frontend-js:frontend-js-metal-web' of type org.gradle.api.Project.
...
```

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
Sent a new pull: https://github.com/jbalsas/liferay-portal/pull/1259

**Pull request closed without merging**
