### PR TITLE
LPS-100125 | Simple Input Modal 2

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey @jbalsas I've made the suggested changes.

A couple comments tho:
- I couldn't get the export working as you wanted, when exporting as default the jsp complained that it couldn't find the function
- After closing the modal there's this warning `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in SimpleInputModal`, unsure how to fix it, but it got introduced after switching to the new mounting/unmounting approach you suggested.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
I've force pushed a commit that brings back the checkbox.

**Comment by wincent** [comment]
LPS-100125___Simple_Input_Modal_2_by_kresimir-coko_·_Pull_Request__1989_·_jbalsas_liferay-portal

GitHub...

giphy

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1991. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Let's use https://github.com/jbalsas/liferay-portal/pull/1991 ;)

**Pull request closed without merging**
