### PR TITLE
LPS-91861 Adds default invalidation cache params to prevent navigations from carrying over component state

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
Hey @john-co, could you please monitor this and send to Brian if safe?

Thanks!

**Comment by john-co** [comment]
pushed to BChan: https://github.com/brianchandotcom/liferay-portal/pull/69319

**Comment by john-co** [comment]
ci:close

**Pull request closed without merging**
