### PR TITLE
[TECHNICAL-SUPPORT] LPS-92958

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-92958
> 
> The issue here is that the restore drop-down notification is not using Clay.
> 
> The fix is to apply the cssClass used by Clay that allows Clay-style modifications.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @jbalsas ,

Please let me know if you have any questions regarding the PR. Thanks.

**Comment by jbalsas** [comment]
Pull request forwarded to https://github.com/p2kmgcl/liferay-portal/pull/323. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
