### PR TITLE
LPS-66906

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
I added the option to set the NPM registry via project property/environment variable. I tried with these environment variables:
* `ORG_GRADLE_PROJECT_nodejs.npm.registry` = `https://registry.npm.taobao.org/`
* `ORG_GRADLE_PROJECT_nodejs.npm.remove.shrinkwrapped.urls` = `true`

...and apparently it downloaded everything from that Chinese mirror (the first one I found). I still don't know what happens if the post-install scripts start doing "crazy" things like downloading from direct URLs...

**Comment by antoniopol06** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @Ithildir, @natecavanaugh, I took some time measurements (over LAN) before and after these changes:

 | git clean -fdx && ant all | rm -rf node_modules* && ant all | ant all
--- | --- | --- | --- |
**master** | 9' 40" | | 8' 29"
**pr** | 10' 45" |  11' 18" | 8' 51" |
**increase** | 11% | | 4% |

I think the numbers aren't bad for now, but we need to run them on some other machines and slower network connections to be sure.

My only concern is that the build is still coupled to `npm-shrinkwrap.json`, or so it seems. 

```
cd modules/apps/foundation/frontend-image-editor/frontend-image-editor-web
vi build.gradle -> remove the cache plugin configuration
rm -rf .task-cache
gradlew clean deploy
```

> :apps:foundation:frontend-image-editor:frontend-image-editor-web:npmInstall FAILED
>
>FAILURE: Build failed with an exception.
>
>\* What went wrong:
>A problem was found with the configuration of task ':apps:foundation:frontend-image-editor:frontend-image-editor-web:npmInstall'.
>\> File '/Users/jose.balsas/dev/liferay/portal/master/portal/modules/apps/foundation/frontend-image-editor/frontend-image-editor-web/npm-shrinkwrap.json' specified for property 'shrinkwrapJsonFile' does not exist.

Even if we'd add the shrinkwrap before removing the cache for those modules, could we make sure this actually works without forcing us to do so?

Thanks!

**Comment by Ithildir** [comment]
Oh, that's a bug, I'll fix it!

**Comment by Ithildir** [comment]
Hi @jbalsas! I force-pushed the fix for the shrinkwrap, but I still haven't tried on the `frontend-js` modules, for now I focused on the themes. It should work though..

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @Ithildir, keeps failing for me 😢

Could you make sure it works following the reproduction steps I provided, please?

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Test failures seem unrelated

**Comment by Ithildir** [comment]
Hi @jbalsas!
This pull is only for themes, the `frontend-js` must still use the task cache.

**Pull request closed without merging**
