### PR TITLE
LPS-83431 Use escapeJS

### PR DESCRIPTION
**Pull request by csierra**
hey guys... could you please review the javascript code?

thx!

/cc @julien

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test

**Comment by csierra** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/stian-sigvartsen/liferay-portal/pull/120. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/7008ef77ef66~1...7008ef77ef66) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
