### PR TITLE
LPS-55175 Fix jsp

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/36. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/58f31c0~5...58f31c0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3216. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/d86431b~5...d86431b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3220. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/83df67c~5...83df67c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
