### PR TITLE
LPS-86123 Update lockfiles on hello-soy modules

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65932. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/48707d2df736~1...48707d2df736) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65933. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/c8d8e568e7a7~2...c8d8e568e7a7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65974. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/c204daf80681~2...c204daf80681) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
