### PR TITLE
LPS-78251

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56576

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56619. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/65fc0c05b001~2...65fc0c05b001) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56620. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/af0b02d3e10d~3...af0b02d3e10d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56639. [See changes here.](https://github.com/jbalsas/liferay-portal/compare/96497bab94cb~3...96497bab94cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
