### PR TITLE
LPS-73338 Wordsmith

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

I wanted to send this your way since it looks like you were brought into the conversation in LPP-25846 at some point. The code looks fine, just wanted to check with you if this was a pattern we're ok with incorporating.

**Comment by Robert-Frampton** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, unfortunately, there's a new Chema in town, because I don't think I've been involved in this one... or maybe I have, I can't really remember 😂 

At first glance, however, and I guess that's why you've sent it my way, I don't like what I'm seeing. Feels definitely a weird workaround for something that was done. Better address the originating issue than adding yet another API.

@JosemariaMunoz, @dustinryerson, could you guys please provide some context to explain why this is really needed? Isn't there a cleaner way to detect this? If we introduced a change in the tag behaviour, it should've been done in a way that the old behaviour was preserved, so that should be the first thing to look into.

**Comment by JosemariaMunoz** [comment]
Hi @Robert-Frampton, @jbalsas,

This is really needed because there is no way to add an input-date tag with attribute nullable to true and without a checkbox to disable this input-date.

On the other hand, this behavior is a problem in some customers because it was backported to 6.2 changing input-date tag lib behavior (currently is showing a new checkbox breaking the customer look&feel of this component).

Regarding the old behavior, is preserved with this implementation because by default is setting to false and is not required, so only affect if you add this attribute and set to true.

Robert, if you need more information please let me know, and yes, you can call me Chema :wink:

Thanks!
@dustinryerson

**Comment by jbalsas** [comment]
Hey @JosemariaMunoz, sounds then like this could be applied only to `6.2.x`...

**Comment by JosemariaMunoz** [comment]
Hey @jbalsas,

Maybe you're right, but we applied this to master thinking on fix this kind of LPSs: https://issues.liferay.com/browse/LPS-66957

Thanks!

**Comment by jbalsas** [comment]
@Robert-Frampton, thoughts? Maybe we can think of a different fix or better API?

**Comment by Robert-Frampton** [comment]
Hey guys,

From looking at LPP-25846, it looks like it was suggested that the hidden inputs get cleared when the date input is cleared, making the checkbox absolute. Looks like there was a commit for it as well https://github.com/JosemariaMunoz/liferay-portal-ee/pull/7

Is there any reason we abandoned that idea?

One potentially good thing about the `disableCheckbox` param, is that some customers have probably already accounted for the added checkbox, and removing it might break their implementations. So by creating another taglib param, the people that have accounted for it don't have to change anything, and those that don't want it can remove it. It's still ugly, but we should keep that in mind.

**Comment by JosemariaMunoz** [comment]
Hey Robert,

This PR is the same idea than that commit, when date input is cleared, hidden inputs are cleared but, in addition, we add the posibility to show an input date without a checkbox. (That LPP was only a test that I sent to @dustinryerson but he ask me about send current PR). 

Regarding broke implementations, this code shouldn't break this implementation because by default doesn't change the config of this component, you can check reviewing this code. 

Maybe it's an ugly solution but, in my opinion, it's already not a very clear behavior that users have to click in a checkbox to send an empty input date and, if it's not necessary click in this checkbox to send an empty input data, what is the meaning of this checkbox? I guess that has a reason and that's why we can do whatever you think is the best solution for this, even we can only apply this code in 62x. 

Anyway, we can not remove this checkbox now because, like you say Robert, we could break some implementations, but we can add the funtionality to doesn't show this checkbox, at least in 62x because we need to fix this in customers.

Thanks!

**Comment by JosemariaMunoz** [comment]
Hey @Robert-Frampton,
Do you have any update about this?
Thanks!

**Comment by Robert-Frampton** [comment]
Hey @JosemariaMunoz 

I went ahead and pushed this through to Brian. https://github.com/brianchandotcom/liferay-portal/pull/50290

The only change I made was updating the attribute name to `showDisableCheckbox` so that it's purpose is a little more clear.

**Comment by JosemariaMunoz** [comment]
Awesome @Robert-Frampton!

Thank you very much!

**Pull request closed without merging**
