### PR TITLE
LPS-62035 Iterate over all children to check if selected

### PR DESCRIPTION
**Pull request by carloslancha**
Guardar el nodo creado como seleccionado si procede no funciona, ya que no es el mismo tipo de objeto que le llegaba hasta ahora al restore y que contiene el select.

Una vez ha creado todos los nodos setea el atributo children de la instancia y al hacerlo pasa por el setter de children de aui-tree-data, que lo convierte en el tipo de objeto que necesita.

Lo he hecho como te había enseñado al principio porque entiendo que corre prisa, pero si ves otra manera (que no tarde 2 días) me parece genial :D

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged please re-run this particular pull request.

Sorry for the inconvenience.

**Comment by mjbradford89** [comment]
Hey @jbalsas,  After looking into this issue a bit more, I actually think it's behaving the same way on 6.2 and master.  I tested it on 6.2 in the Site Administration -> Site Pages tree, by navigating to a child page in the tree and then just refreshing the page, the child page isn't highlighted.  So I think it's the same issue, just more likely to happen in the situation on master. I will continue looking into this tomorrow, but it looks like this fix might be the right way to go.

**Comment by jbalsas** [comment]
Hey @mjbradford89, where did you test this?

I've tested on http://stable-6.2-ee.liferay.org.es/ and it does keep the selected page highlighted no matter which level it is in. I've noticed that it seems to be expanding the nodes one by one, so maybe that has something to do...

**Comment by mjbradford89** [comment]
Oh interesting, I tested it locally on my ee-6.2.x branch (c0481076a1e1e5764c1393c09b7f0abc02ce4138).  I attached a gif, sorry for the terrible quality.

But I am unable to reproduce it on http://stable-6.2-ee.liferay.org.es/.  do you happen to know what commit that build is on?  I wonder if there was a backport that brought this issue from master to 6.2...

tree

**Comment by mjbradford89** [comment]
Ah I think I found the offending commit.  It's https://github.com/liferay/liferay-portal/commit/60856e55e0987927f154613487267260c8373687 on master and https://github.com/liferay/liferay-portal-ee/commit/332bd05a5822c0df045b626ad1b124bc1e9c2a6f on 6.2.

**Pull request closed without merging**
