### PR TITLE
LPS-87269 Clean up, simplify and SF

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
I need to add another commit, so I stopped the tests

**Comment by izaera** [comment]
ci:test

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1639. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
